### ISSUE TITLE
ConversationList scrolls over TopBar

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1000]
When the cursor is in the ConversationList and we scroll, the ConversationList is in front of the TopBar.

![Screenshot 2021-02-16 at 16 44 40](https://user-images.githubusercontent.com/49147864/108088216-8124ef80-7078-11eb-89f8-0692b4743f68.png)

**Comment by lucapette** [comment]
can't reproduce. Please feel free to re-open with more information

**Comment by bitboxer** [comment]
It is still there. Go to the chat, make the window smaller than out defined minimum height. Scroll. And see the wonderful overlap.

**Comment by bitboxer** [comment]
See recording:

https://user-images.githubusercontent.com/56195/109012243-14ca7180-76b2-11eb-9ef3-11fd38e509b0.mov
