### ISSUE TITLE
Bug: Rich Card Renders on Lefthand Side

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1003]
The rich card should render in the messaging UI on the right side - but currently, it renders on the left.

![screenshot_2021-02-16_at_18 14 25](https://user-images.githubusercontent.com/74183162/108102776-4b3c3700-7089-11eb-8128-3f96ba80d676.png)

**Comment by bitboxer** [comment]
Maybe @thorstenairy will fix it with his work in #1011

**Comment by lucapette** [comment]
done in #1011
