### ISSUE TITLE
Bug: Carousels in Chat Plugin - Relevant Message

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1005]
In carousels, clicking a button in the chat plugin doesn’t send the relevant message (compared to rich cards - where it works as expected).
![screenshot_2021-02-16_at_18 17 10](https://user-images.githubusercontent.com/74183162/108103546-63f91c80-708a-11eb-9b04-7e3b598a7d99.png)

**Comment by bitboxer** [comment]
This will be fixed by [my PR](https://github.com/airyhq/airy/pull/1021).
