### ISSUE TITLE
Bug: Cookies + 2 Chat Plugins

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1007]
Have two chat plugins - one called `testing6` and the other one `aditest`.

When I initialize `aditest`, it pulls up the previous conversation with `testing6` and adds the message to the other conversation.

![screenshot_2021-02-16_at_18 31 02](https://user-images.githubusercontent.com/74183162/108108335-c9e8a280-7090-11eb-81ef-fb83f7a767ff.png)

**Possible problem:** might be the cookies -- they are too infringing and disregard the url parameters. Once I delete the cookie, it initializes the right plugin and creates a new conversation.

**Comment by lucapette** [comment]
I think the problem here is that we don't scope the localstorage by channel id?
