### ISSUE TITLE
Bug: Chat Plugin Carousel - jumps to beginning

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1008]
Carousels work, but when I click to the very right, it jumps back to the first card.

![2021-02-16_chat_plugin_carousel_360](https://user-images.githubusercontent.com/74183162/108108497-fd2b3180-7090-11eb-8db0-328308a167a0.gif)

**Comment by bitboxer** [comment]
This can be closed because #1021 will fix it all 😉
