### ISSUE TITLE
Wait for resources to be created on airy create

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1015]
Instead of waiting for services to start with the bash `wait-for-service` function, we need to implement this logic inside the CLI, for the full workflow of the `airy create` command.

**Comment by ljupcovangelski** [comment]
Note: We will need to wait for resources also when we start Airy Core, probably this will be the `airy start` command

**Comment by lucapette** [comment]
@ljupcovangelski we didn't discuss a start command so can you please expand on that? It's not clear to me what we expect the start command to do exactly

**Comment by ljupcovangelski** [comment]
> @ljupcovangelski we didn't discuss a start command so can you please expand on that? It's not clear to me what we expect the start command to do exactly

As `airy create` creates a new Airy core, I assume `airy stop` would stop the instance temporary and `airy start` would resume/start it again.

That is probably more relevant locally, as in the cloud we might not use an actual instance, but a Kubernetes service.

Neads further discussion for sure, I just wanted to point out that at the moment when somebody does `vagrant halt` and `vagrant start` - we do use similar scheduling & waiting of the components, as we do on `./scripts/bootstrap.sh`.

**Comment by pascal-airy** [comment]
I believe @ljupcovangelski  said to solve this with *Kubernetes Init Container* in which we wait for pods that we depend on. E.g. Kafka waits for Zookeeper. So 👍 from me for that!

I just wanted to mention [Helm Hooks](https://helm.sh/docs/topics/charts_hooks/). Which we could use to launch Kubernetes Jobs before or after *all* pods have been created for things like making sure config maps are there before any pod is deployed or printing what our `status.sh` does after the successful deployment

**Comment by ljupcovangelski** [comment]
Since we want the `airy create` command to be in control and to wait/schedule until everything is there - I think we better do that in the code, instead of the `init containers`.

As for helm hooks, I think we shouldn't make ourselves more dependent on `Helm` at this moment.

**Comment by lucapette** [comment]
TIL helm hooks. I like them :) I'm not sure why we wouldn't make ourselves more dependent on helm. I don't think we plan to ever get rid of it (it does way too many things for us we'd have to do on our own).

**Comment by ljupcovangelski** [comment]
Not sure if `helm hooks` can help us in terms of `wait for a service to be available` then start this.
But the `post-install` hook can definitely be helpful. It is actually a great way to execute one-time jobs such as the `create-topics` task.

**Comment by ljupcovangelski** [comment]
@pascal-airy instead of the `init-containers` I thought another option is to do that inside the cli, with go code. For example:
- We install the helm charts with `helm install`
- Scale up Kafka
- Inside the cli code we wait for the Kafka services to be up
- We scale up the Schema registry
- We wait inside the cli code for the Schema service to be up
- We scale up the components
- We wait until everything is up and running and we exit (unless error or timeout is reached).
However, that way the whole process is more dependent on the cli.

If we do with `init containers` then:
- We scale everything to the desired number of replicas with `helm install`
- The `init container` for the schema registry waits for the kafka service, before starting the Schema registry. The `init containers` in each component wait for both Kafka and the Schema registry to be there before allowing the component to start.
- We wait until everything is up and running and we exit (unless error or timeout is reached).

I'm ok with both approaches. The first we put all the logic in the go code. For the second - the logic is outside of the cli and if we change a dependency or add new dependent services - no need to release new version of the cli.

**Comment by ljupcovangelski** [comment]
Done.
