### ISSUE TITLE
Create topics with Kubernetes job

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1016]
Currently we create the Kafka topics with a bash script. Instead we need to do it with a Kubernetes job, which looks for the Kafka connection and the topics in a configMap and creates the topics if they aren't there.

**Comment by lucapette** [comment]
Conceptually it's clear to me what we plan to do here. I'm unsure I understand who's responsible for scheduling the job

**Comment by paulodiniz** [comment]
@lucapette 

You mean if it's the responsability of `airy create` or the `airy config apply` command?

**Comment by ljupcovangelski** [comment]
@lucapette At the moment we can deploy the job with `helm`, with the hook `on install`. That way it will run only once, when the chart is installed. The job will wait for the Kafka service to be available and will the create the topics.
In the future, we can also choose to create the job via the `airy create` command and wait for it to complete, before proceeding.

For facilitating the preview of the status with `airy create` (and `helm instlall` also), one option would be to schedule a `status` job which waits for all the prerequisites, provisioning and components to be there. When everything is created - it will complete. It can also read the provisioning checklist from a configMap if we want to get more granular and exact to the stage the process is in particular moment. Almost all the outputs which are generated on the fly, are written to a configMap from helm (random tokens and strings), so no need to output anything in particular from this job. It will have the sole purpose to check that all the components are deployed correctly.

**Comment by ljupcovangelski** [comment]
Creating topics implemented with kubernetes job.
