### ISSUE TITLE
Download the kubeconf file from the created Kubernetes cluster

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1019]
When we run `airy create` a new Kubernetes cluster will be created, either on the local machine or in the cloud. We need to download the kubeconf file for the CLI to be able to access the cluster.

**Comment by lucapette** [comment]
this is also part of the issue where we introduce airy create?

**Comment by lucapette** [comment]
Actually no. this is provider dependent based on how we envision `airy create` to work. The code of this command will dependent on a valid `kube.conf` so each create provider we write (just invented this name... don't have anything better than "call things what they do") will be responsible for fetching this information and pass it down to the create command.

I will close this issue then as it's redundant (and can't be done separated from the providers)
