### ISSUE TITLE
Print status after creating Airy Core

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1020]
After the successful creation of Airy Core, we need to print-out the output for how to access the platform.

Currently we print out:
- The webhooks
- The API endpoint
- Info about how to create the first user

**Comment by lucapette** [comment]
as I understand it, this should be part of the work we do in #1017 so I will close for now and bring the description there as a content

**Comment by ljupcovangelski** [comment]
I envisioned #1017 only for creating the local instance. This issues was meant to integrate and unify the status messages both when deploying locally and in the cloud.
