### ISSUE TITLE
Re-evaluate the hostnames for Airy Core

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1022]
It will be more convenient for local deployment to have one hostname and instead of additional subdomains, have a path in the request.

This will impact the ingress and probably the path will only be needed for the `frontend` services. An example mapping of the requests:

```
api.airy.core/*        -> airy.core/*
webhooks.airy.core/*   -> airy.core/*
ui.airy.core/*         -> airy.core/ui/*
chatplugin.airy.core/* -> airy.core/ui/chatplugin/*
tools.airy.core/*      -> airy.core/tools/*
```

**Comment by bitboxer** [comment]
This is a bit dangerous because we need to make sure that the localstorage and the cookie handling of the frontend apps is namespaced. They will share the same storage because it's the same domain.

**Comment by chrismatix** [comment]
@bitboxer That's a good point. However, we have to remember that the `chatplugin` needs to namespace its storage anyway because it will run on user websites. Then we are left with the `ui`. Infact: This allows us to make the CORS of the local version more secure, because we can narrow it down to a single host.

**Comment by ljupcovangelski** [comment]
> This is a bit dangerous because we need to make sure that the localstorage and the cookie handling of the frontend apps is namespaced. They will share the same storage because it's the same domain.

I am not aware of this and if this. What would be the solution? Only the frontend apps to have their own subdomain (`ui.airy.core` and `chatplugin.airy.core`)?

**Comment by ljupcovangelski** [comment]
Done.
