### ISSUE TITLE
Replace manual mapping code with npm library

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1028]
**Current state**

Our API returns all data in `snake_case`, but by popular JS convention we use `camelCase` variable names. Therefore we have a large-ish module in `lib/typescript/httpclient/mappers` dedicated to mapping backend response payloads.

**To discuss**
This library ([camelcase-keys](https://www.npmjs.com/package/camelcase-keys)) seems well tested, lean and widely used. Should we use it to replace our mappers.

**Comment by lucapette** [comment]
Yes. It will also "solve" #707

**Comment by bitboxer** [comment]
Can this be closed now?

**Comment by lucapette** [comment]
yes!
