### ISSUE TITLE
Introduce minikube provider for airy create 

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#1041]
We require minikube to be present on the machine already. We make it as explicit as possible in the docs and provide suggestions for CPU/RAM.

- [x] provision Kubernetes cluster
- [x] store path to the kubeconfig file and kubecontext 
- [x] provision endpoint
- [ ] remove vagrant bootstrap code
- [ ] Update docs

**Comment by lucapette** [comment]
About minikube, I'm not sure what the advantage of specifically require minikube would be. But if there's any, all up for it as it'a lovely project. For sure, we should recommend people trying this locally to install kubernetes via minikube (probably with some specific requirements for cpu/ram).

I think `local` is somewhat a strange name, so here's what I'm thinking:

- if we require minikube (maybe this is a good excuse to do so) I would call it minikube
- k8s may be another name... but maybe it's a little too generic (and I'm not sure we should have this door open via the airy create command of "installing it in a bare kubernetes cluster". Being in control of the env, via the face we know the provider, can simplify how you'd interact with your airy core instance).

And now after I wrote this, I'm leaning toward 1) calling it minikube 2) require minikube 3) leverage minikube commands to expose the airy instance locally

**Comment by lucapette** [comment]
One more argument for making minikube required (and thefore calling the provider minikube):  we can offer a better development experience by using minikube locally as it's somewhat more comfortable to create a container registry and therefore providing a better workflow for developers (change something, compile, ship to minikube). Obviously this is out of the scope of the provider itself but it'd help us long term

**Comment by chrismatix** [comment]
I agree with the points mentioned above: So we go with `--provider=minikube` and fail if it's not installed.

**Comment by paulodiniz** [comment]
👍 On calling it `minikube`

@lucapette When you say we `require` minikube it means that we don't bundle it in the cli correct? (I like that idea)

If we agree on that the checklist should be:

- [ ] Change the provider name to `minikube`
- [ ] Update the docs to convey that minikube is a dependency that should be installed beforehand
- [ ] Spit out minikube specific commands

**Comment by lucapette** [comment]
@chrismatix @paulodiniz  I would agree with that. We write the docs of the provider so that we explain people how to install minikube (also helpful for us so we can communicate basic requirements CPU/RAM to actually have a decent experience with core locally).

I will update the issue now 🎉

**Comment by ljupcovangelski** [comment]
I agree that `minikube` is a good option for the local provider. I don't quite understand which option are we gonna go for:
- We check that there is a `minikube` binary and we create the k8s cluster for the user, with specific cpu/ram parameters
- We instruct people to create their own minikube cluster. When they call the provider (example `airy create --provier minikube`) we check that there is a running minikube instance, we connect to it and use the `minikube` commands to expose ports and similar things.

I think we are talking about the first one, which I also recommend.

Using Minikube will facilitate the approach of talking to VirtualBox and creating a k8s cluster in a VM (for example with K3s). A note on using k3s - it can be used without VirtualBox, docker or other VM. It runs as a standalone process.
```
$ curl -sfL https://get.k3s.io | sh -
$ sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get nodes
NAME         STATUS   ROLES                  AGE   VERSION
laptop   Ready    control-plane,master   72s   v1.20.4+k3s1

$ sudo systemctl stop k3s
$ sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get nodes
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?

$ sudo k3s-uninstall.sh

```
Though this is lightweight and I can recommend it for running inside an empty instance or VM, I wouldn't recommend this approach on a local developer machine, as it installs local services and modifies the local network configuration.

One more interesting thing `Minikube` is that it adds a record `host.minikube.internal` to `/etc/hosts` by default, so we can access the services (example the `host.minikube.internal/api` without modifying the `/etc/hosts` file ourselves. However, having `airhy.core/api` in the URL is much more appealing, so I guess we would end-up adding this to the hosts file anyway.

**Comment by lucapette** [comment]
> I agree that `minikube` is a good option for the local provider. I don't quite understand which option are we gonna go for:
> 
>     * We check that there is a `minikube` binary and we create the k8s cluster for the user, with specific cpu/ram parameters
> 
>     * We instruct people to create their own minikube cluster. When they call the provider (example `airy create --provier minikube`) we check that there is a running minikube instance, we connect to it and use the `minikube` commands to expose ports and similar things.
> 
> 
> I think we are talking about the first one, which I also recommend.

No we're not. @chrismatix wrote:

> I agree with the points mentioned above: So we go with --provider=minikube and fail if it's not installed.

And that's what we agreed on. I don't think that prevents us from improving the minikube provider _after_ we ship a first working version of it (right now the goal is finishing https://github.com/airyhq/airy/milestone/22 anyway). I proposed the very same idea on #1018 (I also expected us to come up with good things but out of the scope of the current milestone. so the idea is to capture all the good ideas in follow ups. Otherwise we'll definite creep the scope)

> 
> Using Minikube will facilitate the approach of talking to VirtualBox and creating a k8s cluster in a VM (for example with K3s). A note on using k3s - it can be used without VirtualBox, docker or other VM. It runs as a standalone process.
> 
> ```
> $ curl -sfL https://get.k3s.io | sh -
> $ sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get nodes
> NAME         STATUS   ROLES                  AGE   VERSION
> laptop   Ready    control-plane,master   72s   v1.20.4+k3s1
> 
> $ sudo systemctl stop k3s
> $ sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml  get nodes
> The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
> 
> $ sudo k3s-uninstall.sh
> ```
> 
> Though this is lightweight and I can recommend it for running inside an empty instance or VM, I wouldn't recommend this approach on a local developer machine, as it installs local services and modifies the local network configuration.

I'm not sure why k3s is being brought up? The `airy create` command will treat minikube as any other provider. We pass it a kube.conf (that's the bit to figure out here in this issue) and the airy create command will do the exact same thing it would in other providers (because it only relies on kubernetes. That's the core point of the design decision we took about `airy create`). 

> 
> One more interesting thing `Minikube` is that it adds a record `host.minikube.internal` to `/etc/hosts` by default, so we can access the services (example the `host.minikube.internal/api` without modifying the `/etc/hosts` file ourselves. However, having `airhy.core/api` in the URL is much more appealing, so I guess we would end-up adding this to the hosts file anyway.

This is interesting and I'd be inclined to say "let's do it" but I can't quite picture the docs looking as nice (basically agreeing with you we have to change the host file anyway)
