### ISSUE TITLE
Allow managing of Webhook Redis Queue for Errors

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#1043]
As an Airy Developer consuming events via the webhook at my custom app,
whenever my custom app produces errors that send back an unsuccessful response instead of HTTP Status Code 200,
then the webhook consumer / redis queue should not go to state where no further events are being processed anymore because there are too many jobs that got stuck in the queue

#### Error Logs from the Webhook Consumer Pod:

```
2021/02/19 11:42:25 error when processing message for queue 339ab777-92aa-43a5-b452-82e73c50fc59
https://airy-ca-productdemo.herokuapp.com/webhook returned status code 400
retry %i 1
2021/02/19 11:42:27 error when processing message for queue 339ab777-92aa-43a5-b452-82e73c50fc59
https://airy-ca-productdemo.herokuapp.com/webhook returned status code 400
retry %i 2
2021/02/19 11:42:31 error when processing message for queue 339ab777-92aa-43a5-b452-82e73c50fc59
https://airy-ca-productdemo.herokuapp.com/webhook returned status code 400
retry %i 3
2021/02/19 11:42:39 error when processing message for queue 339ab777-92aa-43a5-b452-82e73c50fc59
https://airy-ca-productdemo.herokuapp.com/webhook returned status code 400
retry %i 4
2021/02/19 11:42:55 error when processing message for queue 339ab777-92aa-43a5-b452-82e73c50fc59
https://airy-ca-productdemo.herokuapp.com/webhook returned status code 400
```

In this state no further events for messages or metadata events where processed anymore.

The only way to resolve this state was to log in to the Redis-Cluster, flush all relevant keys and restart the webhooks-consumer pod.

**Comment by chrismatix** [comment]
I can think of two ways we can go here: 
1. Messages can have a terminal failure state where we will either remove them from the queue or move them to a dead letter queue (SQS terminology)
2. Provide users with an http hook to empty the queue

While we are at it, I think we should also move the routes hosted at the admin `WebhooksController` to the `webhook-publisher`.

**Comment by steffh** [comment]
@chrismatix  I think 2. alone won't help because it just addresses how to fix it and still requires action from the app developer, so some form of 1. would be required anyways in my perspective to have no old jobs getting stuck and blocking the queue.

We should also think about notifications for 1. - e.g. sending an email to warn about failing webhooks would be nice after a certain time (e.g. Facebook last 10 minutes) or when jobs permanently fail or go to the dead letter queue.

**Comment by pascal-airy** [comment]
@lucapette mentioned that this issue is also revealing the missing observability of the system. I suggest instead of emails, all components should provide endpoints that [Prometheus](https://prometheus.io/) can consume. We can also include Prometheus and even [Grafana](https://prometheus.io/docs/visualization/grafana/) for visualization.
But I would have to do more research on the tools and how they would interact with our system.

If the team approves this approach I could do that and start to work on an `observability` milestone.

Since we will also need observability of the cloud instances for ourselves when we start launching instances for real customers.

**Comment by lucapette** [comment]
That is a much better approach and I suggest we proceed with it right away. I will close this issue then as we'll approach the problem in a more structured way
