### ISSUE TITLE
Remove airy init 

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#1051]
As `airy create` will effectively do all the work `airy init` does, the command is redundant from a UX perspective. 

We use this issue as an "excuse" to also restructure the CLI looks for config. Now we have different flags for different things (actual cli config, kube.conf.... airy.yaml file). I suggest we let users only choose a `config-dir` which will contain all the configuration of an airy core instance. 

That way we can also add some nice docs that suggest how to deal with multiple instances as you'd only need to point your cli to different directories and "everything just works" then (proposing some aliases in the docs would make this very nice to work with)

In the context of this change, we can also restructure the integration tests of the CLI a little:

- the runner generates a temp dir
- we put "golden files" in the temp dir
- we point the cli to this temp dir
- run all the tests in a single integration file 
- delete the temp dir

After the conversation in the comments, here's what we plan to do:

- [ ] introduce the concept of `configdir` while removing the file config flags (we point the CLI to a dir with `airy.yaml`, `kube.conf` `cli.yaml`)
- [ ] Because of the previous point, we refactor the integration tests as described (look up in this description)
- [x] move cli to the root directory (#1401)
- [ ] re-organise the packages internally (this point can be further discussed at pr time I think)
- [ ] remove the init command
- [ ] add the --init flag to the create command (so we cover the case @ljupcovangelski brought up)
- [ ] Update all the docs :)

**Comment by ljupcovangelski** [comment]
I agree, however I think we must take into consideration that there is an already created `Airy core` and somebody is downloading the cli for the first time on a new machine, to interact with this existing `Airy core` instance.
But this can be made part of the `airy config` workflow, to add configuration for an already created instance.

**Comment by lucapette** [comment]
that's such a good point! I didn't think about it. But I feel like we're going toward the right direction anyway:

- we remove `airy init` anyway
- `airy create --name instance` creates a dir `instance` with the config files according to the creation process the user choose
- we add `airy create --init instance` which only does the scaffolding of the dir part (in case you need to attach the cli to an existing instance you have the config for already somewhere else)

That should cover all the use cases. There's one more thing I would probably add to this process since we're at it. The CLI accepts a dir config as input or defaults to `./` (instead of `$HOME/.airy`). If we do that, one can achieve a very nice workflow where you have things like:

- `cd staging-instance; airy whatever # runs commands in staging`
- `cd prod-instance; airy whatever # runs commands in prod`
- `airy --config-dir foo whatever # runs commands in foo`

**Comment by lucapette** [comment]
@chrismatix didn't see the direct connection between the two at first but then it started growing on me. I don't want to over due it but since we're at it maybe worth re-evaluating if `infrastructure/cli` is the right place. I never thought it was but I knew it would become more obvious. Maybe we creep-scope this issue a bit but I would be happy with:

- move cli to the root directory
- re-organise the packages internally
- remove the init command
- add the `--init` flag to the create command (so we cover the case @ljupcovangelski brought up)

**Comment by chrismatix** [comment]
@lucapette that's a good scope for now. My main motivation for going a step further is the point you mentioned about scoping the cli config to each workspace. I think this would already facilitate testing. What do you think?

**Comment by ljupcovangelski** [comment]
If I understand correctly, `airy create --init` will just copy one or two config files to a default directory. If that is the case, using it like that seams wrong to me, as the command doesn't create anything, but just `attaches` configuration for an existing instance to the configuration.

Also what would be the opposite command? To remove an instance from the configuration? I assume `airy destroy` or `airy delete` would be the opposite of `airy create`. Will we use something like `airy delete --config-only`. I don't quite get it.

For me this opens another topic for discussion: How do we manage multiple instances with the single `airy` cli? Do we want to do that in the first place? I think this deserves a more broader discussion.

**Comment by lucapette** [comment]
> If I understand correctly, `airy create --init` will just copy one or two config files to a default directory. If that is the case, using it like that seams wrong to me, as the command doesn't create anything, but just `attaches` configuration for an existing instance to the configuration.
> 

I mean... you're saying it right? It doesn't do enough to deserve its own command. And you argue (that's the point) that "it creates the workspace for an existing instance". When it does more than what you just described we'll re-introduce a command (and probably with a more apt name? something like `airy import`. But I have to say it: `airy create --init-only` or something like that will probably _always_ look better to me)

> Also what would be the opposite command? To remove an instance from the configuration? I assume `airy destroy` or `airy delete` would be the opposite of `airy create`. Will we use something like `airy delete --config-only`. I don't quite get it.
>

Why would it need an opposite? That's a strange argument in general.

> For me this opens another topic for discussion: How do we manage multiple instances with the single `airy` cli? Do we want to do that in the first place? I think this deserves a more broader discussion.

Yes we want and that's why we agreed on on what we agreed on in this issue. From [this](https://github.com/airyhq/airy/issues/1051#issuecomment-783277595) comment:

<img width="844" alt="Screenshot 2021-03-03 at 08 54 09" src="https://user-images.githubusercontent.com/124274/109772210-06261200-7bfe-11eb-9379-889a2898495b.png">

t;dr The proposed (and agreed upon) design already covers the case
