### ISSUE TITLE
Various Docs UI Improvements

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#1094]
### **Introduction**

Replace Start Installation Icon with 🚀 (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/1F680.svg

Replace Quick Start Icon wit 💎  (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/1F48E.svg 

**Core Components** 

_Remove current section & replace with button boxes and intro:_

Airy Core includes all components you need for your conversational infrastructure:

Link to: https://airy.co/docs/core/sources/introduction

💬  
Connectors for all conversational sources
Connect anything from our free open-source live chat plugin, Facebook Messenger, Google's Business Messages to your Airy Core. This is all possible through an ingestion platform that heavily relies on Apache Kafka to process incoming webhook data from different sources. We make sense of the data and reshape it into source independent contacts, conversations, and messages.

---------------------

Link to: https://airy.co/docs/core/api/introduction

⚡ 
APIs to access your data
An API to access conversational data with blazing fast HTTP endpoints.

---------------------

Link to: https://airy.co/docs/core/api/websocket

🔌 
WebSockets to power real-time applications
A WebSocket server that allows clients to receive near real-time updates about data flowing through the system.

---------------------

Link to: https://airy.co/docs/core/api/webhook

🎣 
Webhook to listen to events and participate programmatically in conversation
A webhook integration server that allows its users to programmatically participate in conversations by sending messages (the webhook integration exposes events users can "listen" to and react programmatically.)

---------------------

Link to: https://airy.co/docs/core/apps/ui/introduction

💎 
UI: From an inbox to dashboards
Not every message can be handled by code, this is why Airy comes with different UIs ready for you and your teams to use.

---------------------

Link to: https://airy.co/docs/core/integrations/rasa

🛠️
Integrations
Pre-made integrations into popular conversational tools, for example NLP tools like Rasa

### Installation

Replace CLI Icon with 🚀 (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/1F680.svg

### Deployment

-> This section will be merged with Installation either way

Replace Kafka Icon with 
https://upload.wikimedia.org/wikipedia/commons/0/05/Apache_kafka.svg 

Deployment Production

Add TLDR on Top:
Run Airy Core in production environment with Kafka

### Quickstart

_Change infobox to button box:_

Link to: https://airy.co/docs/core/getting-started/installation 

🚀 
Have you already installed Airy?
To get going with the Quickstart, you must install Airy first. Once the CLI is up and running you are good to go.

---------------------

_Change color of token font to black_

![image](https://user-images.githubusercontent.com/12533283/109280207-0350a900-781b-11eb-9d2d-e269f9b2d12c.png)

### API Introduction

Replace HTTP API Icon with ⚡ (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/26A1.svg 

### Apps UI Introduction

Replace UI Quickstart with ⚙️  (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/2699.svg 

Replace Inbox with 🖥️  (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/1F5A5.svg 

Replace Tags with 🏷️  (if emojis possible, if not, following svg)
https://openmoji.org/data/color/svg/1F3F7.svg

**Comment by lucapette** [comment]
so unfortunately the colorful icons look _really_ bad compared to the existing approach (current vs proposed):

<img width="399" alt="Screenshot 2021-02-26 at 12 30 08" src="https://user-images.githubusercontent.com/124274/109295060-639d1600-782e-11eb-843b-7ce62a739279.png">

**Comment by lucapette** [comment]
So I relabeled this as "needs discussion" because the proposal made is not good enough. To recap:

- svg proposed make the button boxes look _really_ bad. I think we all agree the branding is a good exception for the sources icons... but this is hardly justifiable for the rest of the buttons (case in point the screenshot... it looks bad and we'd have the same problem everywhere)
- Using emojis doesn't cut it as they do not scale well enough (after all that's why everyone uses svgs for this use case)

Given the state of this, @AitorAlgorta and I agreed that a good plan is to use colorless svg of the emoji (they're available in the same place with a different link, for example https://openmoji.org/data/black/svg/1F680.svg).
