### ISSUE TITLE
Inbox: name/information editing section

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1102]
In Airy Core, we do not have the ability to edit the contact's information within the Inbox.

<img width="293" alt="Screenshot 2021-02-26 at 17 08 16" src="https://user-images.githubusercontent.com/74183162/109333160-5fd5b780-785f-11eb-98fb-f2e9ee61394e.png">

We would like to include something similar to the above image, as a means of editing contact details within Core. We would like to place this section on the righthand side, when viewing an open conversation.

**Comment by lucapette** [comment]
There's more to come about this in the form of a structured milestone (as the concept of contact isn't really anywhere data model wise so we have to introduce it first and then can build features on top of it)
