### ISSUE TITLE
Introduce chat plugin docs section

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#1105]
As per [this](https://docs.google.com/document/d/19JJtDGO9csT50E4yteWcyercHc9bUy-ieAYaUBKWNLQ/edit) document

**Comment by AitorAlgorta** [comment]
I think this one is good to go. The documents has all the sections needed @lucapette

**Comment by lucapette** [comment]
@AitorAlgorta there's an open question though :)

I just talked to @sgarroum about this off-line and we both think it's better to keep it under source.
