### ISSUE TITLE
Introduce themeConfig to the chatplugin

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#1111]
Our current api for the widget is somewhat too polarized toward both ends of the spectrum "plug&play" vs "full autonomy for customisation".

The idea is to introduce a _very limited_ set of options you can pass to the widget so that you can start off with a plug&play integration and move to render props only if you have very specialised needs for the widget rendering. 

Here's the proposed list of options:

- `welcomeMessage` - The automatic message the widget sends out once someone opens it
- `primaryColor` - what we use for the background
- `bubbleIcon`
- `exitButtonIcon`
- `sendButtonIcon`

I think we may need a bit more about colors/fonts to make it usable (probably a secondary color at least)

**Comment by AitorAlgorta** [comment]
@lizhutter @lucapette if we are good with these options, I will start working on it

**Comment by lucapette** [comment]
@AitorAlgorta this is in needs discussion because

> I think we may need a bit more about colors/fonts to make it usable (probably a secondary color at least)

**Comment by AitorAlgorta** [comment]
@bitboxer @thorstenairy @AudreyKj @chrismatix @ogbeche77 I would like to know your opinion about what attributes you think are relevant and we should let people change in an easy way. Please comment here your thoughts.

**Comment by AudreyKj** [comment]
I think users would want to customize **_welcomeMessage_** and _**primaryColor**_ the most.

**Comment by ogbeche77** [comment]
Looking at it from the perspective of a user introducing a chatplugin to my website. I want to be able to adapt the plugin to the color I associate my brand with. In this case, people should be able to change the color of the header, the color of the send button and the Airy bubble

**Comment by chrismatix** [comment]
> very limited set of options
This is key for me. I think it's hard anticipating user needs here so I can only speak to the obvious: **welcomeMessage**, **primaryColor**, and **secondaryColor** because of what @AudreyKj wrote

**Comment by bitboxer** [comment]
Hm. This one is difficult. There is at least on color missing: **borderColor**. We might be okay with just these and try to use automatic calculations to get enough colors with changing the saturation of those colors for the rest of the elements. 

Font and font size and the border radius might also be important to match the theme of the website.

**Comment by bitboxer** [comment]
For reference this is what intercom is doing:

https://www.intercom.com/help/en/articles/178-customize-the-intercom-messenger-basics

**Comment by AitorAlgorta** [comment]
so my idea, with all the feedback I got, is to have a `config` object with this:

```
{
   welcomeMessage: JSONObject //The automatic message the widget sends out once someone opens it
   primaryColor: string  // headbar or bubble color
   accentColor: string  // send button or input border onfocus
   bubbleIcon: string // url of the icon
   sendMessageIcon: string // url of the icon
   bubbleIcon: string // url of the icon
}
```

I would keep the fonts out of the first version. Since I don't see any competitor doing this and it's way more complex
@airyhq/codeowners-frontend @lucapette

**Comment by thorstenairy** [comment]
Thought about the possibility to maybe set the width of the entire chat. Depending on the conversation, maybe it would be helpful to have a wider window.

**Comment by AitorAlgorta** [comment]
I think it's a good idea, we can do it together with the font and font size in the second version of this. Good idea.

**Comment by lizhutter** [comment]
Please see the image below for a possible design (you do not need to follow it exactly).

<img width="556" alt="Screenshot 2021-03-29 at 12 27 19" src="https://user-images.githubusercontent.com/74183162/112825431-02b26900-908c-11eb-943c-0f6614a23b1e.png">

**Comment by lizhutter** [comment]
Adding to this, we should make it possible to customize the background color of the chat as well. Another option could also be: have a standard light theme and a standard dark theme with a leading color that can be customized.

This way, the chat plugin will not look strange on black/dark websites.
