### ISSUE TITLE
Remove empty response and request payloads

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1163]
**Current state**

- API requests that have an optional body need to be called with an empty body `{}`
- All API responses that don't return data return `{}`

**Proposal**

While the former is annoying to clients, the latter is a bit surprising and we cannot come up with a reason to keep it. So to keep the API clear and consistent with other HTTP APIs we want to get rid of empty bodies, because they don't have a special meaning compared to sending nothing in HTTP.

Empty responses should have a 204 status code.

**Comment by AitorAlgorta** [comment]
I think it's a great idea. Will the API responses change the status code accordingly?

**Comment by chrismatix** [comment]
@AitorAlgorta I think that's a good point and I think they should so I will update the issue.
