### ISSUE TITLE
Document and improve `messages.upsert`

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1164]
Sending fields that are not string values silently fails, but there should be an error. We also took decisions around implicitly mapping fields ending with `count` to integers and fields ending with `content` to objects, so we should document that.

Also we will fix the glossary:

Currently it says: Metadata is data attached to a conversation consisting of a set of Key/Value pairs. A key can use the dot notation to represent namespaces. which is not accurate anymore as we now can attach metadata to more things.

**Comment by lucapette** [comment]
Agreed! The docs change should incorporate also a fix for #1160
