### ISSUE TITLE
AWS provider must have a --aws-profile flag

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#1190]
As a result of the discussion on https://github.com/airyhq/airy/issues/1018 we decided the user should pass a `--aws-profile` flag to the airy command in order to set the profile

```
airy create --provider=aws --aws-profile=staging
```

**Comment by ljupcovangelski** [comment]
To keep consistent flags to the `airy create` sub-command, we can use a generic flag we pass to all the providers, regarding the configuration of the provider. 

Example:
```
airy create --provider=aws --provider-config="access_key=abc" --provider-config="secret_key=abc"
airy create --provider=minikube --provider-config="cpu=2" --provider-config="memory=4"
```

**Comment by ljupcovangelski** [comment]
This is currently done by inheriting the exported AWS_PROFILE env variable. In the future, we might introduce the `--provider-config` flag for overriding the defaults we set for the providers.
