### ISSUE TITLE
Create Cluster network

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#1191]
AWS demands for the following network to exist, in order for the EKS cluster creation

- [ ] Create a VPC
- [ ] Create two subnets contained in the VPC

Both of the subnets *must be* contained in the VPC, and they *must be* in different regions.
e,g:

- VPC with Cidr block `10.0.0.0/16`
- First subnet on region `us-east-1a` with Cidr `10.0.1.0/24`
- Second subnet on region `us-east-1b` with Cidr `10.0.2.0/24`

**Comment by ljupcovangelski** [comment]
Currently this is done like that - we create a new vpc with two subnets.
