### ISSUE TITLE
Create a AWS cluster with a running node

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#1193]
AWS demands two steps to have a kubernetes running cluster, an eks cluster instance and a node group that is attached to the cluster.

- [ ] Create a cluster
- [ ] Create a node group on the cluster

When creating a cluster, you must pass a unique name, which will be referenced when creating the node group on it

Documentation: [](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/eks)

**Comment by ljupcovangelski** [comment]
Done. A random id is generated for the name of the new cluster.
