### ISSUE TITLE
Create a Load Balancer

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#1195]
After adding the node group to the EKS cluster, we might need to expose it using a ELB.

https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html

> The cluster control plane is provisioned across multiple Availability Zones and fronted by an Elastic Load Balancing Network Load Balancer.

This might indicate that we don't actually need to create a new ELB

**Comment by ljupcovangelski** [comment]
The LoadBalancer is created automatically by AWS, once the service with the type=loadbalancer is created in the EKS cluster.
