### ISSUE TITLE
Https setup for traefik

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1212]
For Airy core to be safely usable in cloud environments, we need to configure the ingress controller to use https and some default certificates.
As this connection will be insecure, we should also add documentation for how to modify the default certificates.

**Comment by ljupcovangelski** [comment]
We discussed few options on how to enable `https` for Airy Core, among which:
1) Put https in core, in traefik with some default certs and instructions on how to change them
2) Put https in core, in traefik with letsencrypt
3) Use per-provider solution. For example, for AWS - write docs on how to create AWS ACM certificate and update the service to use that certificate with the loadbalancer them with the loadbalancer
4) Instruct people how to deploy ngrok and have the access to the ngrok public webhook

We decided not to put https in core and to put https on a `per-provider` basis (option 3).

Therefore this ticket is not needed anymore.

**Comment by steffh** [comment]
As talked with @ljupcovangelski, we should have another look at this topic as HTTPS is crucial due to the requirements of conversational sources we integrate with.

I would suggest to reassess the position to have another ingress pod inside the Kubernetes cluster e.g. that could run certbot (https://certbot.eff.org/) to renew SSL certificates automatically via Let's Encrypt.

**Comment by ljupcovangelski** [comment]
After some research and discussions, best approach would be to put the ingress controller in a separate helm chart, so that:
- HTTPS is not part of the core chart.
- When deploying `Airy Core` one can choose if he wants to use https and what is the hostname.
- We can put a per-provider defaults (don't use for Minikube, use specific annotations for AWS or Google).

For choosing the certificates, there are two options:
- Use letsencrypt (will require the hostname to be defined upfront).
- Use existing certificates that the user has and put them in Kubernetes secrets.

**Comment by AitorAlgorta** [comment]
@steffh @lizhutter

**Comment by steffh** [comment]
@ljupcovangelski that sounds like a good idea! please proceed with this plan! thank you!

**Comment by ljupcovangelski** [comment]
I created an initial deployment with letsencrypt. After creation, the ingress controller reads the `host` entries in the `ingress` resources and creates the letsencrypt certificates. Renewals and redirect from HTTP->HTTPS is configured. Letsencrypt doesn't work with the loadbalancer url (because the url is very long) so a custom domain must be used.

The following variables determine the behavior https://github.com/airyhq/airy/pull/2133/files#diff-ffe3c279bc151d521a2e415d826a6ed84d085f428990445dca6b08ff9478e7ad
Example:
```
global.ingress.https = true
global.ingress.letsencrypt.email: "sre@airy.co"
```

Potential usage:
- Run `airy create --provider (some cloud provider)`
- Add DNS entry for `myairy.mydomain.com` -> created loadbalancer
- Patch the ingress resources
```
for ingress in $(kubectl get ingress --no-headers -o custom-columns=":metadata.name"); do kubectl get ingress ${ingress} -o json |  jq '(.spec.rules[0].host="myairy.mydomain.com")' | kubectl apply -f -; done
```

For minikube we will not put the helm overrides, so it will be created like it was until now, http only.

**Comment by ljupcovangelski** [comment]
As we need the `letsencrypt.email` setting inputted by the user, I think there are two potential use-cases we can go for:

1. Add configuration flags for https to the cli:
- `airy create --provider aws --hostname=myairy.mydomain.com --letsencryptEmail=sre@airy.co`
- Manually add DNS entry for myairy.mydomain.com -> created loadbalancer/Minikube instance (will not be needed when we use Terraform for the providers)
(No need to patch the ingress resources)

2. Use a generic flag `--airy-config` or `--set` which overwrites and sets some of the settings which can be found in `airy.yaml`
- `airy create --provider aws --set hostname=myairy.mydomain.com --set letsencryptEmail=sre@airy.co --set kubernetes.appImageTag=develop`

I don't think it is good to add `https` to the `airy config` subcommand as: 1) It is an infrastructure thing and it shouldn't be part of `Airy Core`, 2) We will move the ingress controller in a separate chart in the future, so that people can deploy in their existing Kubernetes environment.

**Comment by steffh** [comment]
Thank you @ljupcovangelski , to me it looks fine to ask for hostname and email. Also agree to separate it from the airy config subcommand.

However, thinking about the user flow I think people might pick the provider in the first step running `airy create --provider aws` but might be unsure about SSL at that point. Could they also run the command later again with hostname and email flags defined or would that lead to issues because it would try to create a new instance?

Otherwise a separate command like `airy ssl --hostname somedomain --email someemail` might work as well?

**Comment by ljupcovangelski** [comment]
Thanks @steffh for the feedback.

> However, thinking about the user flow I think people might pick the provider in the first step running `airy create --provider aws` but might be unsure about SSL at that point. Could they also run the command later again with hostname and email flags defined or would that lead to issues because it would try to create a new instance?
> 
Yes, at this moment, if you run `airy create...` again - it will create a new instance.

> Otherwise a separate command like `airy ssl --hostname somedomain --email someemail` might work as well? (other open source projects like ghost solved it this way)

To make it more generic, this is something we should use `airy upgrade` for. We can use the same sub-command if people want to change something on an infrastructure level or upgrade to a new version.
```
airy upgrade --set httpsEnable=true --set httpsHostname=myairy.mydomain.com --set httpsEmail=myemail
```

**Comment by steffh** [comment]
Yeah sure, whatever works. I just find the repeated --set flags a bit confusing, so I could see people running into issues there.

I thought of `airy upgrade` more in terms of upgrading from version 0.26.0 to e.g. 0.27.0, or would you combine both actions in the same command?

What would be also good is not only to be able to set/write but also to read the current infrastructure configuration as well.

**Comment by chrismatix** [comment]
I'd refrain from introducing new CLI commands like `upgrade` before we completed this milestone https://github.com/airyhq/airy/milestone/32

**Comment by ljupcovangelski** [comment]
> Yeah sure, whatever works. I just find the repeated --set flags a bit confusing, so I could see people running into issues there.
> 
The `--set` flag is intended so that we don't define all the possible configuration items as flags, but have a generic flag and then whatever we pass as an argument or a map - it gets treated in the same way. It can also be like this:
```
airy upgrade --set httpsEnable=true,httpsHostname=myairy.mydomain.com,httpsEmail=myemail
```

> I thought of `airy upgrade` more in terms of upgrading from version 0.26.0 to e.g. 0.27.0, or would you combine both actions in the same command?
> 
Correct, I was thinking that we combine both actions in the same command.

> What would be also good is not only to be able to set/write but also to read the current infrastructure configuration as well.
>
The current configuration should be in the `kubernetes` section of the `airy.yaml` file.

Perhaps the proper way would be to:
- Run `airy create` to create your `Airy Core`
- Modify your `airy.yaml` to change the version or add some HTTPS configuration
- Run `airy upgrade` to apply what you put in the `airy.yaml` file - to the cluster.

But then it is very similar to `airy config apply`, so I'm not sure.
Similar topic is how to modify the settings for Kafka for example? Those settings should go into a `prerequisites.kafka` section.

We had a discussion few months ago, to create multiple config files in the workspace:
- cli.yaml (also created now)
- airy.yaml (also created now)
- prerequisites.yaml
- ingress.yaml
- provider.yaml
This way, we can create the defaults with `airy create --provider aws --init-only`, modify what we want and run `airy create` which should read all the config files and create everything.

An alternative is also to get rid of the Airy controller and `airy config apply` and practically use helm for everything:
- `airy create` creates the proper infrastructure and runs `helm install`. If we have `airy.yaml` in the workspace - it applies those values.
- `airy upgrade` (or some other sub-command) runs `helm upgrade` and updates everything: kafka, https, Airy Core components...

Related issues/discussions:
- https://github.com/airyhq/airy/issues/740
- https://github.com/airyhq/airy/issues/1017
- https://github.com/airyhq/airy/issues/2142

**Comment by ljupcovangelski** [comment]
> I'd refrain from introducing new CLI commands like `upgrade` before we completed this milestone https://github.com/airyhq/airy/milestone/32

I agree, but modifying HTTPS settings is not in the scope of `airy config apply` and the discussion is how do we do that after `airy create` is done.

**Comment by ljupcovangelski** [comment]
For now I propose that we do it like this:
If you want to create Airy Core with a LetsEncrypt certificate, you need to do the following:
```
airy create --provider aws --init-only (initialize a workspace and generate config files)
(add hostname and email to the airy.yaml file)
airy create --provider aws (to create the act
```
This way we don't need to add any flags to the `airy create` command. After the creation, there will be no way (at this moment) to modify these settings. If you don't add this configuration, it will work the same like it does now.

In the future, when we refactor the cli on how it works with providers, whatever is not in the scope of Airy Core will be in a separate config file (prerequisites.yaml, provider.yaml...). Then we will solve the problem how that configuration (related to the infrastructure of Airy Core and not related to Airy Core itself) will be applied/updated.

**Comment by steffh** [comment]
@ljupcovangelski wouldn't an `airy init` command make more sense when you are not actually creating anything in the first step but just downloading config files?

**Comment by ljupcovangelski** [comment]
> @ljupcovangelski wouldn't an `airy init` command make more sense when you are not actually creating anything in the first step but just downloading config files?

@steffh as far as I understand `airy create --init` is intended to generate config files which you can then modify, in order to change the default behavior or `airy create`. Then when you run `airy create`, the updated config files are used when creating the `Airy Core` instance.

I am not in favor of having a separate command at this stage `airy ssl...` or have specific flags such as `airy create --hostname ... --email ...`.
If we use flags, my preference would be to use something like `--set` as a generic flag, to override any of the config items at create time. In that sense, the command would look something like:
```
airy create --provider aws --set hostname=myairy.mydomain.com --set letsencryptEmail=mymail@mydomain.com
```

**Comment by steffh** [comment]
@ljupcovangelski I was mainly referring to using the flag "--set" multiple times which is a pattern I have never really seen.

I think the pattern you used before is easier to read: 

`airy upgrade --set httpsEnable=true,httpsHostname=myairy.mydomain.com,httpsEmail=myemail`

That's also how Helm seems to do it: https://helm.sh/docs/intro/using_helm/#customizing-the-chart-before-installing

Adopting their strategy by either specifying these additional values in a file or alternatively the `--set` flag generally makes sense I think as it's kind of the same use case.

**Comment by chrismatix** [comment]
@steffh We can support the comma separated style, too, but passing a flag like `--set` multiple times is also a very common pattern. [`docker --env`](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file) comes to mind and Ljupco probably knows many many more 😄

**Comment by ljupcovangelski** [comment]
Auto-generated certificates using Let's Encrypt, added to a separate ingress controller.

**Comment by steffh** [comment]
@chrismatix okay, thank you for the explanation. i didn't know any examples, so thank you for sharing a very prominent one apparently. ;)
