### ISSUE TITLE
Index Metadata

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1215]
System already filters + you can already write the data, but we need to properly index metadata

**Comment by chrismatix** [comment]
This is feasible to do. The query syntax could be something like `metadata.unread_count` etc. where you can query all the conversation metadata in dot notation under the metadata field. 

@lizhutter What's the motivation for doing this? :)

**Comment by lizhutter** [comment]
@chrismatix We want to be able to add more filtering options that will be in the metadata, like the unread count

**Comment by lucapette** [comment]
@chrismatix we don't allow nesting? We have to take that into account in the syntax

Also `metadata.` may be confusing as users can only access `user_data` so maybe that should be part of the prefix? It may be saying something about the fact we package user data and "system metadata" into the same place (I'm starting to regret my own suggestion here :D)

**Comment by chrismatix** [comment]
> we don't allow nesting? 
Maybe I am misunderstanding that, but why don't we allow nesting? 🤔 

I am not sure I understand the other point either: For filtering users can access all the metadata, which is why I thought prefixing it with `metadata.` would make that explicit. Now we can of course remove the prefix and we could even put `user_data` on its own field, but I think it's more natural if the query syntax follows the structure of the JSON that users get.

**Comment by chrismatix** [comment]
So the current proposal would be that you can query any metadata under the `metadata` field using dot notation. I.e. with a `conversation.metadata` document that looks like so:
```json5
{
    "unread_count": 2,
    "contact": {
        "displayName": "Grace"
    },
    // This field is populated by the platform user using the /metadata.upsert endpoint
    "user_data": {
        "salesforce": {
             "id": 123"
         }
     }
}
```

Examples of metadata queries:
`metadata.unread_count:[0 TO 5]`
`metadata.contact.displayName:*ace`
`metadata.user_data.salesforce.id:123`

**Comment by lucapette** [comment]
works for me ™️ 

I wonder if that means we should extract the indexer from the current `api-communication` pod. Not sure the timing is right, but surely it's worth bringing it up?

**Comment by paulodiniz** [comment]
@lucapette Maybe we should extract it, but I don't see why now.

But I'm probably missing something 😂

**Comment by chrismatix** [comment]
Agree with what @paulodiniz said. It would definitely work well as a library, but I would probably delay the effort until we have at least one other app that uses it.

Unless I have misunderstood the entire issue and this is about indexing all the metadata and not just the conversation metadata 🙈

**Comment by lucapette** [comment]
@chrismatix @paulodiniz oh that's a valid point. I like this "we delay extracting this until we need to index all the things". As it's conversation specific, as far as I can say, I think this is ready
