### ISSUE TITLE
Observability Milestone

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#1229]
This ticket serves the purpose to discuss the issues needed for the observability milestone:

**Comment by pascal-airy** [comment]
The tricky part that I see is that we have to serve two use cases

1. Observing multiple Kubernetes Clusters for our paying customers
2. Observing the local Core instance in Minikube

[Prometheus](https://prometheus.io/docs/introduction/overview/) can resolve both problems in my opinion. Since it integrates well into the Kubernetes infrastructure and stores data locally. Furthermore, it provides tools for analyzing time-series data, alerting, and visualization.

**Comment by pascal-airy** [comment]
We are going to need tickets for the different components that we want to monitor.

- Java apps
- Redshift
- Postgres
- Webhooks

 All apps that we want to monitor more closely than what Prometheus can get from Kubernetes will need `/metrics` endpoints.

**Comment by lucapette** [comment]
@pascal-airy good starting point!

As for the apps, we use spring boot for most of them so that's relatively easy. 

How would namespacing the metrics would work? I guess because pometheus pulls, it can be decided from that side?

**Comment by pascal-airy** [comment]
closed in favor of the Observability milestone
