### ISSUE TITLE
Add demo templates and message suggestions for testing

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#1259]
I suggest adding a Cypress test that creates the demo messages and opens them in the Inbox

**Comment by bitboxer** [comment]
I would not use cypress for this because cypress also needs a connected chat plugin that you configure manually right now. Ideally, we have a seed script that we can also use to seed the environment for cypress to run. No manual step is necessary then 😉

**Comment by pascal-airy** [comment]
@ogbeche77 and I are also creating a test for connecting a chatplugin at the moment and I would add the requests to create the messages in the Cypress test directly. I think that way we can structure testing and setting up prerequisites for tests better and we could *force* more people to get familiar with Cypress ;)

**Comment by lucapette** [comment]
I agree with @pascal-airy 

We can catch two birds with one stone when we do #1049  (as running all the tests will indeed seed an instance) so I will close this issue and add a note about this conversation there
