### ISSUE TITLE
Introduction Revamp: Explanation Graph, Improved Navigation, Quickstart Box

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#1262]
Welcome to Airy!

What is Airy Core?

>> Airy Core is an open source, fully-featured, production-ready messaging platform.

![Airy_Explainer_highlevel_final_docs](https://user-images.githubusercontent.com/12533283/111980839-25320880-8b07-11eb-8c75-a94ec47785e6.png)

Box Button 1:
Icon: Airy Icon
What are Airy's components?
Learn about Airy's messaging platform and components
-> Link to the component page

Box Button 2:
Icon: Rocket Emoji
Installation
Install Airy locally or in the cloud of your choice
-> Link to the installation page

Box Button 3:
Icon: Gem Emoji
Follow the Quickstart
Connect your first source and learn the Airy Basics
-> Link to the quickstart page

Add a quickstart like this, With the Airy create commands:
<img width="1118" alt="Screenshot 2021-03-16 at 15 48 25" src="https://user-images.githubusercontent.com/12533283/111329038-1531a900-866f-11eb-843a-65b76dfc546f.png">

**Get Started**

#Install Airy
brew install airyhq/airy/cli

#Start Airy Core
airy create

**What Airy is used for**

With Airy Core you can process conversational data from a variety of sources:

- Facebook Messenger
- WhatsApp Business API
- Google's Business Messages
- SMS
- Website Chat Plugins
- Your own conversational channels

You can then use Airy Core to:

- Unify your messaging channels
- Stream your conversational data wherever you want
- Integrate with different NLP frameworks
- Mediate open requests with Agents via our messaging UI
- Analyze your conversations

Since Airy's infrastructure is built around Apache Kafka, it can process a large amount of conversations and messages simultaneously and stream the relevant conversational data to wherever you need it.

_Current Get Started Section: rename to Next Steps_

**Comment by lucapette** [comment]
The colors proposed here don't really work with the color scheme we have

**Comment by sgarroum** [comment]
I created a lightmode version of the explainer asset with transparent bg so @AitorAlgorta & @lucapette don't need to rep

![Airy_Explainer_Highlevel_Lightmode](https://user-images.githubusercontent.com/12533283/112179903-5f7cd200-8bfb-11eb-9f27-f4d07e4614c3.png)

**Comment by sgarroum** [comment]
I also made a lightmode version with white boxes that fits better:
![Airy_Explainer_Highlevel_Lightmode_Whiteboxes](https://user-images.githubusercontent.com/12533283/112311056-8e4f8280-8ca5-11eb-9aa0-ca17dc8e8600.png)
