### ISSUE TITLE
Make Cypress tests independent from each other

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#1272]
We can use https://docs.cypress.io/api/plugins/before-run-api.html#Log-the-browser-and-the-number-of-specs-that-will-be-run to set up the env before running the tests. We need to:

1. create a user
2. connect a chatplugin channel
3. create a conversation

**Comment by pascal-airy** [comment]
So I now think we should not use requests to set up test contexts. As discussed with @lucapette it is better to duplicate the test code so that every test sets up the context through the UI so they are proper integration tests.
Also, @ogbeche77 if you do it please also fix the `create_tag` test in a way that you can run it multiple multiple times. My suggestion would be to delete the tag after you verified that it exists.

**Comment by ogbeche77** [comment]
@pascal-airy  Great idea, deleting the tag after it has been created should give us the possibility to re-run the test multiple times.
