### ISSUE TITLE
Strategy for dealing with kube configuration

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1284]
Currently the `minikube` provider writes the kubernetes configuration to the default kubeconf file on the system - `~/.kube/config`.

We would like to have the option, when we do `airy create --provider minikube` to write it to an external file, so that we can leave the system kubeconf intact (for example to write it to `~/.airy/kube.conf`).

**Comment by chrismatix** [comment]
This is now irrelevant as there is no more minikube and the cli no longer talks to Kubernetes
