### ISSUE TITLE
MessageTextArea in inbox doesn't shrink when extended it before with a long text

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1298]
![Screenshot 2021-03-19 at 10 03 44](https://user-images.githubusercontent.com/49147864/111756955-16471e00-889b-11eb-9262-a819d906521e.png)

**Comment by bitboxer** [comment]
This was fixed in #677

**Comment by bitboxer** [comment]
I just found another edge case while testing something else. Will fix it now
