### ISSUE TITLE
Research on theme for Docs 

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#1302]
**Current state**

Our Docs website does not use a theme, but customizes Docusaurus' default theme.

**To do**
Investigate whether we should use a theme for our Docs website (https://www.npmjs.com/package/@rasahq/docusaurus-theme-tabula).

It would enable us to have the search bar in the left sidebar which we tried to do in (#773)

**Comment by sgarroum** [comment]
We could also customize Docusaurus' default theme and publish it as our own theme

**Comment by AudreyKj** [comment]
issue's outcome: the Rasa Docusaurus theme could be a good option for us, but it is still pretty much WIP, and I think we should wait for the release of the npm package (there is still a lot of Todos in the package)

@sgarroum regarding customizing Docusaurus' default theme, I think it's a good idea, but to change the default layout, we would need to _swizzle_ components, which at this stage is discouraged by the Docusaurus' team at this stage (https://docusaurus.io/docs/using-themes#swizzling-theme-components)

**Comment by lucapette** [comment]
As I understand it, the most sensible way to proceed it here is to wait a little for themes to mature so I'm adding the waiting label
