### ISSUE TITLE
Long messages from contacts shrink the avatar size

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1303]
![Screenshot 2021-03-19 at 10 17 56](https://user-images.githubusercontent.com/49147864/111759615-1268cb00-889e-11eb-82ea-e1f03de750fe.png)

Actually a nice feature, but it leads to a different start of the message bubble so the date string doesn't fit anymore.
Maybe we should discuss about whether we really wanna shrink the avatar and I would like to talk about the bubble sizes.
It looks kinda odd, that the bubbles use 100% width, this is kinda uncommon when you compare this to iMessage, Whatsapp, Messenger etc.

**Comment by AitorAlgorta** [comment]
the avatar needs a `min-width`, with that it should work fine

**Comment by thorstenairy** [comment]
and set the the max-width of the bubble to 65%? 70%?

**Comment by AitorAlgorta** [comment]
I think it might work if you use just `min-width`

**Comment by bitboxer** [comment]
the actual solution is a `flex-shrink: 0`. Will implement it now.
