### ISSUE TITLE
Remove additional sentAt string from Facebook button template

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1305]
![Screenshot 2021-03-19 at 12 29 37](https://user-images.githubusercontent.com/49147864/111773751-de49d600-88ae-11eb-8a65-a7e0664bbabc.png)

as the MessageInfoWrapper already adds the sentAt string, we need to remove it from the ButtonTemplate component

**Comment by AudreyKj** [comment]
already fixed by PR https://github.com/airyhq/airy/pull/1297
