### ISSUE TITLE
Core Components: Change title, Add Explainer Image and TLDR

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#1318]
Change Title from "Core Components" to "Airy Core Components"

Add TLDR:
Airy Core comes with all the components you need for a fully-featured conversational platform

![Airy_Explainer_Components_docs](https://user-images.githubusercontent.com/12533283/111981351-dafd5700-8b07-11eb-9940-04955bf1fdc1.png)

The Airy Core platform contains the following core components: -> Airy Core contains the following components:

**Comment by lucapette** [comment]
<img width="1277" alt="Screenshot 2021-03-22 at 12 31 43" src="https://user-images.githubusercontent.com/124274/111983606-9d4dfd80-8b0a-11eb-9ec2-c2e5719442c3.png">

<img width="1221" alt="Screenshot 2021-03-22 at 12 31 51" src="https://user-images.githubusercontent.com/124274/111983612-9fb05780-8b0a-11eb-8a5b-62e794cf18f0.png">


It looks good in dark mode as his... but with the light theme the background is really heavy. Probably a transparent background image would be already better (even though I'm not so sure about the font...)

**Comment by AitorAlgorta** [comment]
We could just turn the background transparent and then it just uses the background of the page. No need of changing the image depending on the mode. @lucapette

**Comment by sgarroum** [comment]
I created a Lightmode Version with transparent BG & Dark Font, so we have the best of @AitorAlgorta & @lucapette's worlds

![Airy_Explainer_Highlevel_Lightmode](https://user-images.githubusercontent.com/12533283/112179575-17f64600-8bfb-11eb-8a6f-e2fba31a4698.png)

**Comment by sgarroum** [comment]
I also made a lightmode version with white boxes that fits better:
![Airy_Explainer_Highlevel_Lightmode_Whiteboxes](https://user-images.githubusercontent.com/12533283/112310698-2a2cbe80-8ca5-11eb-83e5-d3c46b757a7b.png)
