### ISSUE TITLE
Change size of message bubble

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1383]
![Screenshot 2021-03-25 at 17 07 20](https://user-images.githubusercontent.com/49147864/112504969-9cc49980-8d8c-11eb-819d-faba2af9337d.png)

It looks kinda odd that we use 100% width for the message bubble, we should set the max-width to anything around 50%!?

**Comment by AitorAlgorta** [comment]
I agree, maybe 60% of the full width would make more sense

**Comment by AitorAlgorta** [comment]
@lizhutter

**Comment by lizhutter** [comment]
I agree with both of you about this; I think 60% of full width would be more aesthetically pleasing for users :) and we can revisit this when/if we decide to make some changes focusing on mobile browser users

**Comment by bitboxer** [comment]
The implementation broke the display of messages in the chat plugin. We reverted it and will need a better fix.

**Comment by bitboxer** [comment]
Maybe `max-width: min(500px, 100%)` would be a better solution. Might need to play around with the pixel value till the box looks nice. Another hint: this should only be applied to text boxes, the carousel and other rich content might need as much width as possible?

**Comment by lizhutter** [comment]
I agree with @bitboxer that it should only apply to text boxes; rich cards/carousels should have 100% width, or as much as possible
