### ISSUE TITLE
Live Chat Docs: Overview Comparison Table

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#1405]
- [ ]  New Component: a simple comparison table for each Message Type : Code on the left with the payload, Gif on the right of each 

@lucapette you said you saw a good implementation of such a component in another docusaurus?

**Comment by AitorAlgorta** [comment]
I understand it's just the payload of our own source, the chatplugin. Right? @sgarroum @lucapette

**Comment by lucapette** [comment]
yes @AitorAlgorta I think the idea is we provide contextual/visual info about how to the payload renders. I'm not sure "gif" is the right format on the right (after all there may be a way to actually use our own render lib?).

Also comparison table is a little misleading as a title (even thought I think we get what it means). The idea is:

`{"text": "this payload looks like this"}` -> picture/gif/actual html

In a table, surely the information would look tidy but I'm unsure how readable would be the format. So I'm thinking more left side of a div (so to speak): snipped of code, right side visual representation
