### ISSUE TITLE
API and media-resolver configuration sections not working

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1430]
The sections for `api` and `media-resolver` in the `components configuration` of the docs https://airy.co/docs/core/getting-started/installation/configuration#components are currently not working, because at the moment we don't consider them with the `airy config apply` command.

**Comment by chrismatix** [comment]
Then this is a duplicate of #1150, correct?

**Comment by ljupcovangelski** [comment]
Correct, it is a duplicate and I will close it.
