### ISSUE TITLE
Docs Search broken (shows old docs, probably needs to be re-indexed) 

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#1437]
If I am currently searching for AWS for example I see:
![image](https://user-images.githubusercontent.com/12533283/113135547-88681d00-9222-11eb-95f0-eda924f83ce1.png)
![image](https://user-images.githubusercontent.com/12533283/113135555-8aca7700-9222-11eb-80ae-bc0cfd5fd2c2.png)

Instead I should be send to
https://airy.co/docs/core/getting-started/installation/aws

**Comment by steffh** [comment]
I have reached out the Algolia support and inquired about reindexing the site.

**Comment by lucapette** [comment]
we opened a pr https://github.com/algolia/docsearch-configs/pull/3920 and waiting for it to be merged

**Comment by lucapette** [comment]
it was merged and works now!
