### ISSUE TITLE
Release starts cluster with app image tag develop

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1535]
**Issue**
Since this app image tag is hardcoded users of the release CLI version will always start their cluster with images tagged `develop`
https://github.com/airyhq/airy/blob/cde029352e1e973e3cfa02ac7bcf21c36eb9a99c/cli/pkg/workspace/template/airy.yaml#L2

**Desired state**
The image tag should be the same as the release version

**Comment by lucapette** [comment]
![maxresdefault](https://user-images.githubusercontent.com/124274/114549223-0b489900-9c61-11eb-9154-90ea48458270.jpg)
