### ISSUE TITLE
AWS Provider Docs - Add Recommendation to enable HTTPS

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#1558]
Since we want users to run and connect to their Airy instance securely in the cloud, we should recommend to enable HTTPS by adding SSL certificates (for example using [Let’s encrypt](https://letsencrypt.org/)).

The recommended way of doing this seems to be to enable SSL on either the ingress controller or the load balancer serving the ingress. 

We should refer to the documentation of AWS or the relevant cloud provider / ingress controller.

To the extent this is necessary for HTTPS to work, we should also show how the configuration needs to be adjusted in the relevant Airy instance.

**Comment by steffh** [comment]
depends on: https://github.com/airyhq/airy/issues/1212

**Comment by ljupcovangelski** [comment]
We had a discussion and we decided to solve https on a `per-provider` basis. Therefore I closed #1212 and for AWS we will write docs on how to create AWS ACM certificate and update the loadbalancer service to use that certificate with the loadbalancer them with the loadbalancer

**Comment by ljupcovangelski** [comment]
We added instructions on howto enable HTTPS for AWS in the docs, however we are using a self-signed certificate and that is not an ideal solution.
We need to instruct on how to create a HTTPS tunnel with a generated `let's encrypt` certificate and also make `Airy core` available on a configurable domain name (example `myairy.customer.com`)

**Comment by ljupcovangelski** [comment]
When trying to create Airy Core on Google Cloud, we realized that the HTTPS approach we have in the docs for AWS works completely different for Google.

So in my opinion we should again explore the option of adding HTTPS capabilities to our Traefik ingress, so that we can unify the process for different types of cloud providers.

**Comment by ljupcovangelski** [comment]
This is done.
