### ISSUE TITLE
Configuring the prerequisites when creating airy core instance

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1575]
When deploying prerequisites, one option would be when we do airy create that the command looks for kafka.yaml, postgres.yaml, ... in the {config-dir} and check whether to create new kafka/postgres or use an existing ones.

We have to decide whether these files are in the scope of `configuration` and should be considered by `airy config apply`.

**Comment by chrismatix** [comment]
Closing this as it's no longer relevant
