### ISSUE TITLE
Checkmark svg broken

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1602]
Currently, all uses of the checkmark svg are broken as seen in the screenshot.

![image](https://user-images.githubusercontent.com/4403838/115517250-3cd7ea80-a287-11eb-8ee1-9dd66e337d25.png)

**Comment by AudreyKj** [comment]
When we moved back the components lib back to the monorepo, the svgs were optimized with svgo, which removed the viewBox attribute, and this is why the svgs got out of place: https://github.com/svg/svgo/issues/505
