### ISSUE TITLE
Fix flickering of Facebook profile images 

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#1679]
**Current State** 
-> profile images from FB are flickering 

-> it looks like the flickering is due to  images that are hosted via FB; the link seems to be a download link so the browser is making requests to download the media 

example: https://platform-lookaside.fbsbx.com/platform/profilepic/?psid=3725986624164757&width=1024&ext=1622212474&hash=AeSmHaNQG2Z2OInzXAg

**Comment by AitorAlgorta** [comment]
we discovered that this was fixed by a different PR and it's not happening in the last version of develop anymore.

**Comment by AudreyKj** [comment]
Reopening this because this bug can be observed on develop

**Comment by AudreyKj** [comment]
Facebook profile images URLs are request links so a solution could be to upload the images to an AWS bucket and store this url in redux.

**Comment by AudreyKj** [comment]
closed by #2006
