### ISSUE TITLE
Optimize the Docker images

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#169]
The size of the Docker images has a direct impact on the time that it takes to get the Airy Core Platform up-and-running. Also, since we package some of the images in the Vagrant box, this will have an impact on the size of the box and the time it takes for downloading it.

Currently used Docker images include:
- Kafka, Zookeeper, Kafka schema registry
- Postgres, Redis
- Airy Core apps
- Images required for Kubernetes to run properly

**Comment by ljupcovangelski** [comment]
This is the current status of the images:

For the base services:
```
confluentinc/cp-kafka            598MB
confluentinc/cp-zookeeper        598MB
confluentinc/cp-schema-registry  1.21GB
postgres                         158MB
redis                            40.9MB
```
For the apps:
```
ghcr.io/airyhq/api/admin                       365MB
ghcr.io/airyhq/sources/twilio-events-router    361MB
ghcr.io/airyhq/sources/twilio-webhook          354MB
ghcr.io/airyhq/webhook/publisher               368MB
ghcr.io/airyhq/sources/facebook-sender         361MB
ghcr.io/airyhq/sources/google-events-router    361MB
ghcr.io/airyhq/sources/chat-plugin             366MB
ghcr.io/airyhq/sources/facebook-events-router  361MB
ghcr.io/airyhq/sources/google-webhook          349MB
ghcr.io/airyhq/sources/facebook-webhook        349MB
ghcr.io/airyhq/frontend/demo                   26.4MB
ghcr.io/airyhq/webhook/consumer                27.1MB
ghcr.io/airyhq/sources/twilio-sender           366MB
ghcr.io/airyhq/api/auth                        310MB
ghcr.io/airyhq/sources/google-sender           363MB
ghcr.io/airyhq/frontend/chat-plugin            21.9MB
ghcr.io/airyhq/api/communication               366MB
```

At the moment, we will focus the most at Kafka, Zookeeper and the Schema registry.

**Comment by ljupcovangelski** [comment]
The image for `Kafka` and `Zookeeper` has been optimized. Both statefulsets at the moment use the same image, only with different arguments to the entrypoint of the container.

Still left is the `Schema registry` image.

**Comment by lucapette** [comment]
finished in #596 🎉
