### ISSUE TITLE
Displaying video icon in conversationList when lastMessage sent is suggestedReply

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1729]
![Screenshot 2021-05-05 at 10 38 03](https://user-images.githubusercontent.com/49147864/117118908-a381fb80-ad91-11eb-974d-6449c317da84.png)
<img width="1038" alt="Screenshot 2021-05-05 at 10 38 13" src="https://user-images.githubusercontent.com/49147864/117118912-a54bbf00-ad91-11eb-9e63-977f487b95ee.png">

**Comment by steffh** [comment]
fyi - it also happens when the last message is a template
