### ISSUE TITLE
Checkmark is missing in state of channel in channelsList

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1767]
![Screenshot 2021-05-10 at 16 03 58](https://user-images.githubusercontent.com/49147864/117672448-264bf180-b1aa-11eb-96c0-b7eb8f14108e.png)

**Comment by AudreyKj** [comment]
<img width="233" alt="Screenshot 2021-05-11 at 09 36 03" src="https://user-images.githubusercontent.com/38159391/117776890-5348e480-b23c-11eb-9124-ec67571750f6.png">

Here checkmark svg not scaled properly
