### ISSUE TITLE
Bad calls to conversations.info when opening inbox

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#1768]
**Problem**

When opening the inbox, the current conversation is being requested with `/conversations.info` but the request payload is empty which results in a loop of `400 Bad Request` calls.

This does not impact the app behavior.

![image](https://user-images.githubusercontent.com/4403838/117675867-4335f400-b1ad-11eb-822c-1b3931ed8cfb.png)

**Expected behavior**
The endpoint is called with a conversation id when needed.

**Comment by AudreyKj** [comment]
this happens when there are no conversations in the inbox
