### ISSUE TITLE
Airy Live Chat: Add Documentation on Source Connection Page

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1784]
To improve system user experience, we should provide the Airy documentation corresponding to each source on the screen where users will be connecting their sources.

For Airy Live Chat, we should include a link below the large `Airy Live Chat` heading.

<img width="750" alt="Screenshot 2021-05-12 at 09 57 03" src="https://user-images.githubusercontent.com/74183162/117944369-78595800-b30d-11eb-937b-1014a7d6b592.png">

### Design Note
We can display an info button alongside [Relevant Documentation](https://airy.co/docs/core/sources/chatplugin/overview).

**Comment by AudreyKj** [comment]
closed by #1797
