### ISSUE TITLE
Channels page breaks when there are too many channels 

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#1809]
https://johnreed.airy.co/ui/channels/connected/facebook

<img width="1418" alt="Screenshot 2021-05-19 at 09 45 58" src="https://user-images.githubusercontent.com/54705263/118775256-05a92900-b887-11eb-9d29-74e3fae123b8.png">

Also, the number of connected channels is not correct.

<img width="1418" alt="Screenshot 2021-05-19 at 09 47 37" src="https://user-images.githubusercontent.com/54705263/118775505-4bfe8800-b887-11eb-9fb0-16149a116916.png">

**Comment by AudreyKj** [comment]
update: the number of channels actually works so the issue is just fixing the UI
