### ISSUE TITLE
Sending messages UX improvement: focus on input and send on Enter

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#1820]
For the UX I would focus the messageInput after clicking on a conversation so the user can instantly start typing

**Comment by AudreyKj** [comment]
yes!! I would also enable sending messages on press Enter

**Comment by AudreyKj** [comment]
@lizhutter what do you think?

**Comment by lizhutter** [comment]
@AudreyKj @thorstenairy I agree with both ideas :)

**Comment by AudreyKj** [comment]
Focus on messageInput after clicking on conversation in conversationListItem + send on Enter
