### ISSUE TITLE
Bug on Pagination / Conversations   

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#1838]
**Current State** 
- Right now on the Tedi instance, on the latest develop version, when the conversations are filtered by Facebook channels, the oldest conversation is from May 18th. There are +40k conversations so data is missing; perhaps the pagination isn't working well.

below screenshot of the oldest conversations scrolled (no more conversations appear after that)

<img width="425" alt="Screenshot 2021-05-25 at 17 07 34" src="https://user-images.githubusercontent.com/38159391/119522000-ebd27f00-bd7b-11eb-8cb4-17f9019e3dcc.png">

**Comment by chrismatix** [comment]
I checked the network tab and it looks like this is actually a frontend bug: The first pagination request does not include the filter.

**Comment by AudreyKj** [comment]
OK, will look into it
