### ISSUE TITLE
Start webhook integration by default

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1917]
We had a discussion with @steffh if it makes sense that we enable the webhook-integration component by default.

At the moment, we have the convention that components which are `mandatory` are started by default. And all the other components can be started after `airy create` is finished by updating the `airy.yaml` file and running `airy config apply.

The `integration-webhook` is not a `mandatory` component but it is one of the more common use-cases for `Airy core`. Also there are no secrets required from the user in the `.components.integration.webhook` section of `airy.yaml` at the moment. We had a similar situation with the `source-chatplugin` component (which is also not a `mandatory` component for the system to run) but we we marked it as `mandatory` so it can be started by default.

I suggest we open a discussion in this issue:
- Do we mark the integration-webhook as a mandatory component
- Do we add a mechanism that you can specify non-mandatory components to be started with `airy create`.
- Do we use stay with the current convention to use `airy config apply` to start all non-mandatory components, which were not started by default.

**Comment by chrismatix** [comment]
This seems like a cloud deployment issue. The mechanism in question already exists via the `--init-only` flag that one can use to edit the `airy.yaml` before creating a cluster. So in my opinion the webhook should remain turned off by default and we fix this in the cloud configuration.

It's important to keep the core as lean as possible to allow for fast startup and a leaner runtime for new users.

**Comment by ljupcovangelski** [comment]
> This seems like a cloud deployment issue. The mechanism in question already exists via the `--init-only` flag that one can use to edit the `airy.yaml` before creating a cluster. So in my opinion the webhook should remain turned off by default and we fix this in the cloud configuration.

I think it is not exclusively related to cloud deployment but to a general expectation - what should be started by default. Also the mechanism doesn't quite work at the moment because:
- you can run `airy create --init-only` and create a starting `airy.yaml` file.
- then you can edit the `airy.yaml` file and add for example
```
components:
  integration:
    webhook:
      name: Airy
      maxBackoff: 10
```
- if you run airy create afterwards however, the integration-webhook pods will not be started by default, because the `integration-webhook` configmMap is **only** created by running `airy config apply`. 

> It's important to keep the core as lean as possible to allow for fast startup and a leaner runtime for new users.

I agree.

**Comment by chrismatix** [comment]
@ljupcovangelski That's very true! Therefore should also run `config apply` in the cloud context after installation. It's part of the installation lifecycle anyway. 

There's a separate discussion to be had about automatically applying the config after `creation`. I'd be in favor.

**Comment by steffh** [comment]
I think the confusion also comes from `/webhooks.subscribe` letting you subscribe to a url without the required configuration in `airy.yaml` being there and the pod even running in the first place.

In case it was possible to check for this and give an error on `/webhooks.subscribe` it might be less confusing to people. 

We have also discussed adding more examples to the docs how the configuration in `airy.yaml` could look like so people have a better chance to realize they need to edit `airy.yaml`, apply the configuration and only then will be able to subscribe to a url with the pod being up and running, sending actual events.

I am also not sure how much resources a webhook pod running by default would consume on top of the existing configuration.

**Comment by chrismatix** [comment]
Closing this issue since we decided on implementing improvements here: https://github.com/airyhq/airy/milestone/32
