### ISSUE TITLE
Docs: Polishing, rough edges & flow improvement

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#1926]
**Configuration section**:
- Example airy.yaml

**Sources**:
- Disclamer for the sources and the webhook that they are not enabled by default and that they need to be enabled.
- On how to enable them - code blocks with example configuration, per source.

**Installation**:
- When clicking on "Installation -> CLI", the green block "Deploy Airy core" leads back to Installation. Next step should be choose the provider (Instalation of the CLI should be separated from Minikube/AWS, either on a separate page or a separate block).
- Logical path: Installation of the cli -> Install Airy (choose your provider) -> Secure your instance -> Quickstart -> Setup other sources (Sources->Introduction)

**Security**:
- "Secure your instance" should link to the Authentication document (Perhaps that document should be moved outside of the "API" block and under "Setup & Deployment"
- Remove the "Create a self-signed certificate" error. We assume that people have certificate and put in a link for Traefik and Let's encrypt
- Add a disclamer for recommendation of HTTPS on AWS.

**Chat plugin installation**:
- Update the code

**Comment by AudreyKj** [comment]
chat plugin: 

installation code: `j.src = w[n].host + '/chatplugin/ui/s.js';`

**Comment by ljupcovangelski** [comment]
Done.
