### ISSUE TITLE
Optional: Notes About Conversations in UI

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#1998]
**Currently:** the only contact information available in the Inbox is the the name of the contact and any tags related to the conversation.

<img width="930" alt="Screenshot 2021-06-15 at 13 39 37" src="https://user-images.githubusercontent.com/74183162/122098681-23fb3980-cddf-11eb-914f-cd198e9f4ed1.png">

**Ideally:** we should offer Airy system users to write and view notes below the Tags section within the contact information.

**Requirements:**

- If the conversation is displayed and I click on the notes field, I will be able to manually type in and edit notes
- If I am editing the notes field and I hit enter, I will be able to save the written note
- If I have a long note above 500 characters and I want to see the note, I will only be able to see part of the note (maximum 3 lines of text/special characters/numbers visible at a time)
- If I have multiple notes and I want to see an older specific note, I can scroll down to access older notes

**Notes:**

- Allowed input: text, special characters, numbers
- No character limit

**Comment by chrismatix** [comment]
@lizhutter It's not quite clear to me how this is supposed to look like. Could you perhaps add some mockups for the placement of the "notes field" and how this should work with multiple notes?

**Comment by lizhutter** [comment]
@chrismatix this is similar to what I think it would look like:

![ad9a6c224e8c327a1d72e0bbe3d666da-screenshot-2019-07-08-at-18-17-47](https://user-images.githubusercontent.com/74183162/122203685-49825480-ce6c-11eb-95af-b36f393a5fb6.png)

The notes can be moved up further in the column, but it could have a vertical scrollbar so you can look back at previous notes.

Users should also be able to delete these notes if they're no longer relevant.

**Comment by chrismatix** [comment]
Thanks. This makes it clearer. I guess there would be an "add note" button at the bottom and perhaps a trash icon per note to allow for deletion.

**Comment by chrismatix** [comment]
Also `no character limit` is not very practical. I would suggest that we settle on something that is large, but technically feasible. Say 50k characters?

**Comment by lizhutter** [comment]
50k characters would be sufficient, thanks for the comment! @chrismatix
