### ISSUE TITLE
Improving Chat Plugin Code Generator

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2002]
**Currently:** the code generator for the Airy Live Chat Plugin has both singular and double quotation marks.

<img width="1383" alt="Screenshot 2021-06-16 at 07 30 54" src="https://user-images.githubusercontent.com/74183162/122211940-46d82d00-ce75-11eb-9546-26de8d66fe12.png">

We should change this so that all quotation marks are double.

**Comment by AitorAlgorta** [comment]
since this is a `good first issue` I will remove it from the engineering board @lizhutter
