### ISSUE TITLE
Add Commas to Inbox Conversation Count

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2005]
### Currently:
The Inbox conversation count looks like the image below:

<img width="342" alt="Screenshot 2021-06-16 at 10 48 33" src="https://user-images.githubusercontent.com/74183162/122242915-b3f9bb80-ce91-11eb-86a8-82975677e017.png">

In addition to this, the conversation count visible within the tab appears the same way:

<img width="228" alt="Screenshot 2021-06-16 at 10 48 41" src="https://user-images.githubusercontent.com/74183162/122243380-118e0800-ce92-11eb-9f5f-10dd3f63d726.png">

### Requirements

We should put a comma when there are more than a thousand conversations. Whether it is 1,000 or 1,000,000 -- we should be able to successfully include these commas.

**Comment by brennanw31** [comment]
Could I give this a try?

**Comment by lizhutter** [comment]
@brennanw31 Absolutely, let me know if you have any questions!

**Comment by brennanw31** [comment]
@lizhutter Sorry I'm very new to GitHub, could you direct me to the file destination of the code regarding the issue?

**Comment by AitorAlgorta** [comment]
Hey @brennanw31 I can help with this. We have a component called `InboxConversationCount` that you can find under `frontend/ui/src/pages/Inbox/ConversationListHeader`, there is where the fix is needed. Let me know if you need more help and looking forward to approve your pull request :)

**Comment by AudreyKj** [comment]
fixed by #2606
