### ISSUE TITLE
Instagram Source 

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2051]
Requirements: 

- [x] Documentation

**Backend**
- [x] Connect Instagram channel via API
- [x] Receive Messages and Messaging_postback Webhooks from Instagram: https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook
- [x] Fetch profile information (name, profile_pic) via the [User Profile API](https://developers.facebook.com/docs/messenger-platform/instagram/features/user-profile)
- [x] Sending of Messages via the [Send API](https://developers.facebook.com/docs/messenger-platform/instagram/features/send-message)

**Frontend**
- [x] Display Instagram conversations with source icon
- [x] Render Instagram messages

**Comment by chrismatix** [comment]
@steffh I updated the ticket a bit to reflect minimum functionality in the inbox. This assumes that users can only connect channels via the API.
