### ISSUE TITLE
Render Images within UI and Chat Plugin

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2080]
We need to be able to render images in the UI as well as the Airy Live Chat Plugin.

The file types must include (but are not limited to):
- JPG/JPEG
- GIF
- PNG
- PDF

Please include any other file types that you believe to be crucial for this feature to work properly.

**Comment by AudreyKj** [comment]
we already render images (PNG, JPEG, GIF) in the UI and Chat Plugin - I guess the feature to add would be PDF. maybe with https://www.npmjs.com/package/react-pdf?

**Comment by AitorAlgorta** [comment]
These tickets about rendering stuff should tell the sources. We cannot render images for SMS for example. Rendering images for Facebook is not the same as rendering images for Whatsapp. Can we even render images for Google? The ticket is too general @lizhutter
