### ISSUE TITLE
Update Rasa Integration documentation. The linked connector file points to the outdated airy.py file 

### ISSUE THREAD

**Issue by armanjindal** [airyhq/airy#2100]
I was connecting Rasa (V 2.7) with Airy (0.25) for the first time. In the documentation:

"The first step is to create a new directory channels/ in our Rasa project and copy **this connector** file into it. "

The link for "this connector" is https://github.com/airyhq/rasa-demo/blob/master/channels/airy.py - which is an outdated connector, as the Airy webhook no longer conforms with that format. 

The up-to-date version I found clicking through the demo repository available here: https://github.com/airyhq/rasa-demo/tree/main/channels - which works!

The proposed change is to update the link on the documentation!

**Comment by chrismatix** [comment]
Thanks for spotting that @armanjindal!

**Comment by armanjindal** [comment]
Hi @chrismatix! My pleasure. Really enjoyed your L3 AI talk at Rasa 😄  Could I make the PR? Would be my second PR in an open-source project and it feels quite cool to contribute in any small way!

**Comment by chrismatix** [comment]
Glad that you liked it. And I would definitely appreciate the PR a lot! 😄
