### ISSUE TITLE
Render/Send File Attachments via Facebook Messenger

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2109]
The Messenger Platform allows you to attach assets to messages, including audio, video, images, and files. The maximum attachment size is 25 MB. The maximum resolution for images is 85 Megapixel. There are three ways to attach an asset to a message:
- URL
- File
- attachment_id

The Messenger Platform supports the following attachment types, specified in the `attachment.type` property of the message:
- audio
- video
- image
- file

With video files, we should not have a video player in the beginning. Instead, we should allow users to download the file and then watch it. 

### Send an attachment from a URL
Submit a POST request to the Send API, with message.attachment set in the request body. The attachment object includes the asset type (image, audio, video, or file), and a payload that includes the asset url:

### Design Note

In terms of design for the UI, we can use the image below as a reference.

<img width="618" alt="122225089-bf91b600-ce82-11eb-9a1b-012bfacda270" src="https://user-images.githubusercontent.com/74183162/124493881-1f91c300-dd84-11eb-90c0-1f6a200856ca.png">

We can use the same order of the icons within the input bar that we already have (emojis, templates, attachments).

### Design Note
Please use the paperclip icon from [this website](https://www.zwicon.com/cheatsheet.html):
<img width="1011" alt="Screenshot 2021-06-16 at 08 56 56" src="https://user-images.githubusercontent.com/74183162/122223261-02eb2500-ce81-11eb-9709-bfe334980227.png">

### Technical Notes

- Obtain a media URL by uploading a file using the [media.uploadFile](https://github.com/airyhq/airy/blob/a88c16fc52834e9d33b6030816ee29b82fa8379a/docs/docs/api/endpoints/attachments.md#L9) endpoint
- The button has to be disabled if the `media-resolver` component in the `/client.config` is not running

Finally, call the `/messages.send` endpoint with a payload like so:
```json5
{
	"conversation_id": "20c3eb36-f151-5a28-94d6-b3d2769db974",
	"message": {
		"attachment":{
			"type":"image", 
			"payload":{
				"url":"https://picsum.photos/200/300"
			}
		}
	}
}
```

**Comment by chrismatix** [comment]
@lizhutter The frontend should use the "Send by URL" approach by calling the #2078 API endpoint. As such I think it does not make sense to implement the file attachment approach right now.
