### ISSUE TITLE
Contact Name update is not saved in Inbox UI

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2114]
**Describe the bug**

**To Reproduce**
1. Log in to the Inbox UI of any Airy Instance
2. When you update the name of a contact of a conversation in the sidebar, such update is reflected in the conversation list and the sidebar 
3. But it is not saved in the backend properly, so when you reload the page in the browser, the previous name shows up again

**Expected behavior**
The updated contact name change should be updated in the metadata of the conversation in the backend.

**Screenshots**

The Change is reflected in the frontend:

![Screenshot 2021-07-06 at 11 14 06](https://user-images.githubusercontent.com/9045481/124575222-80380300-de4b-11eb-96d8-604297d7c2c7.png)

Upon loading the page again, the change is reverted to the previous state:

![Screenshot 2021-07-06 at 11 13 48](https://user-images.githubusercontent.com/9045481/124575327-9776f080-de4b-11eb-9764-c88fc06fe9dd.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 91

**Additional context**
-

**Comment by chrismatix** [comment]
This is related to our roll-out to the cloud instances: We did not update our routing so the endpoint is never properly called.
