### ISSUE TITLE
Move the ui settings to the settings endpoint

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#2195]
**Is your feature request related to a problem? Please describe.**
Currently, the tag configuration is hardcoded in `frontend/ui/src/pages/Tags/FAKESETTINGS.ts`. 

**Describe the solution you'd like**
As originally intended this configuration should also be served by the `/client.config` endpoint

**Describe alternatives you've considered**
We can keep it as such for longer, but cleaning it up would be beneficial to the codebase.

**Comment by AitorAlgorta** [comment]
We need to decide what do we do with this @juan-sebastian @chrismatix
