### ISSUE TITLE
Facebook Source: Add message metadata for message_reaction events

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2197]
**Is your feature request related to a problem? Please describe.**

As an Airy developer / user I want to be informed when Facebook users react to my messages e.g. with an emoji, etc..

**Describe the solution you'd like**

Once we receive message_reactions events in the following format:

```
{
   "sender":{
      "id":"<PSID>"
   },
   "recipient":{
      "id":"<PAGE_ID>"
   },
   "timestamp":1458668856463,
   "reaction":{
         "reaction": "smile|angry|sad|wow|love|like|dislike|other",
         "emoji": "\u{2764}\u{FE0F}",
         "action": "react|unreact",
         "mid": "<MID_OF_ReactedTo_Message>",
   }
}
```
Source: https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/message-reactions

THEN update the message metadata for the relevant message when requested via the HTTP API and send a metadata event as follows:

```
{
  "type": "metadata",

  "payload": {
    "subject": "message",
    "identifier": "message id",
    "metadata": {
       "from_contact": BOOL,
       "user_id": "SOME_ID", // alternative to from_contact, feel free to remove as we don't have user_ids
       "reaction":{
         "reaction": "smile|angry|sad|wow|love|like|dislike|other",
         "emoji": "\u{2764}\u{FE0F}",
         "action": "react|unreact",
         "mid": "<MID_OF_ReactedTo_Message>",
       },
       "sent_at": "TIMESTAMP",
    }
  }
}
```

**Describe alternatives you've considered**

Feel free to adjust the payload as you think makes most sense, e.g. move `from_contact`, `user_id`, `sent_at` into the `reaction` object.

**Additional context**
-

**Comment by chrismatix** [comment]
Payload after considerations of the current data model:
```
{
  "type": "metadata",

  "payload": {
    "subject": "message",
    "identifier": "message id",
    "metadata": {
       "reaction":{
         "emoji": "\u{2764}\u{FE0F}",
         "sent_at": "TIMESTAMP"
       }
    }
  }
}
```
- `from_contact` is implied in the message record this metadata is about
- `mid` we want to have a unified reaction schema so no Facebook-specific ids
- `reaction` the emoji property seems easier to generalize between sources
- `action` the metadata webhook always reflects the final metadata state (including non-reaction data like suggested replies). So when a reaction is removed, the same payload would be sent only with the reaction data cleared.

**Comment by steffh** [comment]
thanks @chrismatix
