### ISSUE TITLE
Instagram UI: Alternative Version

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2213]
We have already made it possible to connect Instagram via the API but we should give system users the option to connect via the graphical UI also.

Option A: Connect an Instagram Account with Facebook Login -- Facebook Login Button
Option B: Connect an Instagram Account manually

This alternative version of connecting the Instagram UI should be available via a button above the `more information about this source` button. This additional button should allow users to connect their account with Facebook Login.

<img width="260" alt="screenshot_2021-07-26_at_18 13 45" src="https://user-images.githubusercontent.com/74183162/127025190-87b2587a-7150-4536-a2cf-f91c7a6b1697.png">

<img width="667" alt="screenshot_2021-07-26_at_17 47 49" src="https://user-images.githubusercontent.com/74183162/127019221-9a2f52b9-bd10-4f92-8d9b-a90db323ed75.png">

### Design Note
Once the system user clicks `Login with Facebook` we will inform system users:

To get started with Instagram Messages you need to make sure that:
- You have an Instagram Business Account ([documentation: how to switch to a Business account](https://www.facebook.com/help/instagram/502981923235522))
- Your Instagram Business Account needs to have at least 1,000 followers
- Your Instagram Business profile needs to be a connected to a Facebook page ([documentation](https://help.instagram.com/399237934150902?fbclid=IwAR1ekAUj69Zz9v6LduTdGbirlLjFcnTQv73TaVaC01tNi2iZtrkwsSlrhms)). We should make a note that linking can only be done via the Instagram mobile app.
- You need to allow API Access in Settings > Privacy > Messages in the Instagram App ([documentation](https://www.facebook.com/help/instagram/791161338412168))

**Comment by elhe26** [comment]
Any updates?

**Comment by lizhutter** [comment]
@elhe26 thanks for following up on this one! Can you explain your use case so that we have a better idea how this may be influential?

**Comment by elhe26** [comment]
Sure thing. I don't know if it's possible but here is our case:

We're a  B2B/B2C logistics startup. We offer our users a platform to send and track their packages. We're planning on offer unifed communications (mainly ig) on our platform. 

We're looking for solutions and we stumbled upon this awesome project.

Will it be possible to configure airy for separate users? The flow will be the following:

- User A configures its ig and get access only to his/her ig.

I don't know if this makes sense.
