### ISSUE TITLE
Telemetry for Airy Core usage

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#2223]
After few discussions that we had with @pascal-airy, @steffh and @sgarroum, I am opening this issue so that we can discuss and determine what kind of metrics do we need to determine how much people are using `Airy Core`, without giving an impression that we are threatening their privacy.

Metrics such as:
- Downloads of the airy cli
- Number of Ngrok tunnels
- Pulled images from Github

Please write your thoughts in this issue and after we agree on what do we need, we can build the tools and get/store proper metrics.

**Comment by steffh** [comment]
Another approach of implementation of telemetry in an open source project:
https://github.com/airbytehq/airbyte/tree/master/airbyte-analytics

They provide a way to opt out via config variables (https://docs.airbyte.io/faq/getting-started#can-i-disable-analytics-in-airbyte), plus a switch for anonymization of telemetry events when starting their UI for the first time.

Also, email is a required field for new instance we the option to sign up for security updates and/or product news:

<img width="2048" alt="Screenshot 2021-07-09 at 22 48 58" src="https://user-images.githubusercontent.com/9045481/127343813-14ca2f48-b070-41d3-a3b9-fe705814805d.png">

**Comment by pascal-airy** [comment]
Opened a milestone and umbrella ticket #2245
