### ISSUE TITLE
Instagram Source: Show Story Reply in Inbox UI

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2227]
**Is your feature request related to a problem? Please describe.**
As an Airy inbox user I want be able to see that an incoming message is in regards to a Instagram story.

**Describe the solution you'd like**

When the `message.content.message` object contains a link to a story 

```
{
"message":{
   "mid":"<MESSAGE_ID>",
   "text":"<MESSAGE_CONTENT>",
   "reply_to":{
          "story":{
          "url":"<CDN_URL>",
          "id":"story_id"
           }
    }
}
```

then display the relevant story as a status next to the message.

The CDN Link might expire with the story, so we should only display a link with target=_bank for message.sent_at + 24 hours, thereafter only indicate that the message originated from a story, but don't link to it anymore (removing icon, HTML link tag and bold font type).

Design Suggestion (please feel free to adjust):

![mock-story-inbox](https://user-images.githubusercontent.com/9045481/127656803-78ae776b-670f-44a7-ba05-cc739b5f6456.png)

Resources:
https://icons.getbootstrap.com/icons/play-circle/ (Open Source)

**Describe alternatives you've considered**

**Additional context**

**Comment by chrismatix** [comment]
![image](https://user-images.githubusercontent.com/4403838/129025752-cd96b4dc-cf62-43af-a74f-0c118308eedf.png)

Very small design comment. I would move this story reply bit to the top of the text message for two reasons:

- Code structure: Everything above the time box is concerned with rendering source specific messages. All components outside it are agnostic
- On Instagram it's also above which suits the natural flow reading flow. I would guess that we would also reference regular message replies like so.
