### ISSUE TITLE
Viber Source

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2228]
**Is your feature request related to a problem? Please describe.**

As an Airy user I want to be able to connect a new source of type `viber` to my Airy instance, 
consuming events from it and sending back messages,
and being able to look at conversations of type `viber` in the Inbox UI.

**Describe the solution you'd like**

- Store credentials in `airy.yaml` configuration for source - or on channel level (comparable to page tokens)

- Requests are authenticated via header `X-Viber-Auth-Token`: https://developers.viber.com/docs/api/rest-bot-api/#authentication-token

- Webhooks to subscribe for: https://developers.viber.com/docs/api/rest-bot-api/#setting-a-webhook

Conversation Started Event (https://developers.viber.com/docs/api/rest-bot-api/#conversation-started):
```
{
   "event":"conversation_started",
   "timestamp":1457764197627,
   "message_token":4912661846655238145,
   "type":"open",
   "context":"context information",
   "user":{
      "id":"01234567890A=",
      "name":"John McClane",
      "avatar":"http://avatar.example.com",
      "country":"UK",
      "language":"en",
      "api_version":1
   },
   "subscribed":false
}
```
This event needs to be responded with HTTP 200 + optional: a Welcome Message in the body (https://developers.viber.com/docs/api/rest-bot-api/#sending-a-welcome-message)

The welcome message should be used to convert the user to send a message which subscribes the user, otherwise the Send Message via API route can't be used to reach users that haven't subscribed yet.

Receive Message from User Event (https://developers.viber.com/docs/api/rest-bot-api/#receive-message-from-user):
```
{
   "event":"message",
   "timestamp":1457764197627,
   "message_token":4912661846655238145,
   "sender":{
      "id":"01234567890A=",
      "name":"John McClane",
      "avatar":"http://avatar.example.com",
      "country":"UK",
      "language":"en",
      "api_version":1
   },
   "message":{
      "type":"text",
      "text":"a message to the service",
      "media":"http://example.com",
      "location":{
         "lat":50.76891,
         "lon":6.11499
      },
      "tracking_data":"tracking data"
   }
}
```

Subscribed Event (https://developers.viber.com/docs/api/rest-bot-api/#subscribed) - Requirement to send messages to a User:

```
{
   "event":"subscribed",
   "timestamp":1457764197627,
   "user":{
      "id":"01234567890A=",
      "name":"John McClane",
      "avatar":"http://avatar.example.com",
      "country":"UK",
      "language":"en",
      "api_version":1
   },
   "message_token":4912661846655238145
}
```

Corresponding Event: https://developers.viber.com/docs/api/rest-bot-api/#unsubscribed

Message Receipts: https://developers.viber.com/docs/api/rest-bot-api/#message-receipts-callbacks

APIs to send to: 

- Send Message via API: https://developers.viber.com/docs/api/rest-bot-api/#send-message

There is a hourly rate limit of sending 100 individual messages per recipient without responses via the API. 

Alternatively, Broadcast Messages can be send to subscribers via Broadcast Message via API (https://developers.viber.com/docs/api/rest-bot-api/#broadcast-message).

The Response  for sending a message contains a `message_token` property which should be tracked for following `delivered` and `seen` events: 
```
{
  "status": 0,
  "status_message": "ok",
  "message_token": 5602570000333709000,
  "chat_hostname": "SN-CHAT-24_"
}
```
Delivered Event:
```
{
  "event": "delivered",
  "timestamp": 1627814555340,
  "chat_hostname": "SN-CHAT-25_",
  "message_token": 5602570000333709000,
  "user_id": "BtrgXI7x1u6hYXaOi+GQyw=="
}
```
Seen Event:
```
{
  "event": "seen",
  "timestamp": 1627814556898,
  "chat_hostname": "SN-CHAT-25_",
  "message_token": 5602570000333709000,
  "user_id": "BtrgXI7x1u6hYXaOi+GQyw=="
}
````

The metadata status of the messages and conversations should be updated accordingly.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by chrismatix** [comment]
> The welcome message should be used to convert the user to send a message which subscribes the user, otherwise the Send Message via API route can't be used to reach users that haven't subscribed yet.

For this we need to introduce a new conversation metadata key: `sending_disabled` which is source agnostic so that the `message.send` endpoint can always check it.

**Comment by steffh** [comment]
@chrismatix I think it's a bit dangerous predicting the value of a remote property.

The flow they envision for the welcome message is a bit different (https://developers.viber.com/docs/api/rest-bot-api/#welcome-message-flow) because the welcome message needs to be send with the HTTP 200 as the request body, so we cannot send it later asynchronously, but we would have to store it with the system e.g. as a config variable when connecting the channel.

Then again, if the user wouldn't interact with the bot he would not be subscribed, but there are no further events / questions asked, so no reason to interact with them anyways.

As soon as the user would send an inbound message, he would be automatically subscribed until he actively unsubscribes. When testing the source I didn't get a separate `subscribed` event for this, so this remote value can change implicitly.

Your suggestion makes sense to try to track this, but I feel getting it right might be hard. I also wouldn't manipulate the value that heavily because `sending_disabled` is a predictation we make, but `subscribed` true or false as delivered in the `conversation_started` event is effectively a bit different:

```
{
  "event": "conversation_started",
  "timestamp": 1627813725714,
  "chat_hostname": "SN-308_",
  "message_token": 5602566522375795000,
  "type": "open",
  "user": {
    "id": "ABCDEFG",
    "name": "Steffen",
    "language": "en",
    "country": "DE",
    "api_version": 10
  },
  "subscribed": false
}
```

**Comment by chrismatix** [comment]
> The welcome message should be used to convert the user to send a message which subscribes the user, otherwise the Send Message via API route can't be used to reach users that haven't subscribed yet.

Then I misread `Send Message via API` as meaning our send message endpoint. All good then: We won't track it. 

On that note: If we ever want to address message delivery failures and resending messages these are fairly easy to implement.
