### ISSUE TITLE
Future of `/channels.explore`

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#223]
Current problems of `/channels.explore`:

- Only needed for UI implementations
- Redundant for Facebook as it offers you a dialogue with pages you can connect
- For Facebook, we require a user token while on the connection endpoint it's a page access token (confusing)

**Comment by lucapette** [comment]
We're standardizing our relationship with sources and the idea is the following:

- Sources bring their own explore (so if you need an explore endpoint, it's going to be `/source.explore`). For example, right now the only source using the explore endpoint is facebook (also being the only one we believe it's redundant). For that reason, we should probably just get rid of the concept for now
- `/channels.connect` `/channels.disconnect` become `/source.connect` `/source.disconnect`. This will simplify dealing with payloads that necessarily differ from each other (due the very different nature of some sources)
- As we're introducing (already started in #528) a `SourceConnector` service that manages the data relationship with the source (it sends messages to the source, it extracts metadata information from it), this service is the most _natural_ place for the webhook integration as well. This way we also make the run time slimmer

The way we planned to do this is:

- Add a milestone called "standardize connectors"
- Add an issue to it for each source (the facebook one needs less work) in which we introduce the connector/update the api docs

**Comment by lucapette** [comment]
we addressed everything in #541
