### ISSUE TITLE
Telemetry Configuration Option for Airy Core

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2244]
**Is your feature request related to a problem? Please describe.**

As an Airy user I want the option to switch off sending telemetry events from my instance to Airy which should be on per default

**Describe the solution you'd like**

1. The default should be to have telemetry enabled.

2. To prevent any events from being sent even before the installation, we could add a flag such as `airy create --set airy_telemetry_enabled=false`

3. We could add a configuration variable in `airy.yaml` to later change the setting for `airy_telemetry_enabled: true` to `false` (or vice versa) and then ask users to apply the configuration 

**Describe alternatives you've considered**

We could add separate subcommands in the Airy CLI such as `airy telemetry disable` and `airy telemetry enable` instead of the `airy.yaml` config solution. 

In addition to the binary switch we could have an additional configuration option to send only anonymized data, which should be the default anyways, so we can live without this for the time being.

**Additional context**

All payloads above are only suggestions. Please feel free to adjust according to what makes sense.

**Comment by steffh** [comment]
I cannot find any information in the docs around telemetry and how to switch it on or off.

I am reopening this ticket and will add a docs request.

**Comment by pascal-airy** [comment]
@steffh it is here under [tools](https://airy.co/docs/core/getting-started/installation/configuration#tools)
and you can also switch it off by passing `--disable-tracking` to the airy create command  like described [here](https://airy.co/docs/core/cli/usage#create)
