### ISSUE TITLE
Analytics and Dashboard Demo

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#2257]
As a data scientist or engineer I want to experience the power of Airy's conversational analytics dashboard (powered by Metabase) in a quick 20min demo.

This will be the diy analytics project that shows off the power of the Airy platform and our conversational analytics know how, described in 
https://blog.airy.co/introducing-data-lakes-for-conversational-data/
https://blog.airy.co/a-guide-to-conversational-metrics/
https://blog.airy.co/how-to-build-your-conversational-dashboard/

**The demo repo should include everything a data scientist needs to:**
- Set up their Airy Instance

- populated with (real-ish looking, so perhaps GPT-2 generated) conversations in it

- have a running Metabase dashboard running in the end with the following metrics:
-- Number of Conversations
-- Active Conversations by Day and Source
-- Most active Hours
-- Channels
-- Average Human Response Time
-- Conversation Count
-- Conversations responded by Bot
-- Conversations responded by Humans

![image](https://user-images.githubusercontent.com/12533283/128728445-7514fd5c-611e-45e6-819d-6f5b8b38a56e.png)
![image](https://user-images.githubusercontent.com/12533283/128728457-75a6c101-1198-4eb9-8532-153c10582b83.png)

**Deliverables**
- Repo with Readme
- Readme includes a guide on How To Set it up
- Fake but real-ish looking conversations (so perhaps GPT-2 generated)

**A good comparison:**
Good example Machine learning Repo that comes with a data set, a 20min video, in-depth explanations and guide
https://github.com/kaiwaehner/hivemq-mqtt-tensorflow-kafka-realtime-iot-machine-learning-training-inference

**Comment by pascal-airy** [comment]
Proposed solution:

- Minimal Terraform setup that launches airy core via Helm in the users AWS account
- Kafka image that contains preloaded data
- Metabase pod launched and configured automatically to access the same data from a preloaded data lake bucket

Limitations:

- Users need an AWS account with enough permissions to create EKS cluster, S3 Bucket and several IAM roles
- There is no live connection between Kafka/Inbox and the data-lake

Stretch Goals

- Jupyter Notebook connected to the data lake to play around with the data

**Comment by pascal-airy** [comment]
Own Metabase instance is too complex because it involves user-owned Glue tables and crawlers etc..
So instead we will provide a link to our Metabase instance where users can have a look at the dashboard and dive deeper into the data itself stored on our public S3 bucket via a Jupyter Notebook
