### ISSUE TITLE
Chatplugin configuration options for mobile websites

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2273]
**Is your feature request related to a problem? Please describe.**

As a user having installed the Airy Chatplugin on a specific website, I would like to have more control on the way the chat plugin is rendered on a mobile phone.

Depending on the design of the relevant mobile website, the current standard settings could lead to suboptimal experiences of visitors, especially when using older mobile phones with smaller screen sizes (e.g. the chat plugin is expanded, taking up all the space on the screen, navigation elements like close / minimize buttons might be outside of the view, so the user needs to scroll the chat plugin to reach the relevant elements)

**Describe the solution you'd like**

1. We could read the max-width of the screen to determine if it's a mobile device or not (i.e. phone vs. tablet) that the current web browser is running to adjust the CSS accordingly for mobile . 

2. We could change the standard behavior as follows (suggestions from customer):
- set the standard to not to open on first page load on mobile
-  have a height setting in the css of "-webkit-fill-available" with a fallback of "100vh" for browsers that don't support that.

3. We could provide for additional configuration options to finetune the experience depending on the design of the relevant website and preferences of the user installing the Airy Chatplugin on their website:

- configuration option to always minimize the Airy Chatplugin on a mobile device
- configuration option for the Airy Chat Plugin to take up only a specific height of the screen (e.g. 50-80%), so navigation elements of the mobile website on top always stay visible
- configuration option to not render the Airy Chatplugin on a mobile device at all
- configuration option to hide the close button (x) or minimize button (-) entirely to reduce the complexity of the Airy Chatplugin

**Describe alternatives you've considered**
Feel free to suggest any changes to the above as there seems to be a better fit / technical restrictions.

**Additional context**
-

**Comment by AitorAlgorta** [comment]
fixed by https://github.com/airyhq/airy/issues/2273
