### ISSUE TITLE
Introduce Contacts as a separate entity

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2293]
**Is your feature request related to a problem? Please describe.**

So far Airy handles contact profile information as metadata of conversations due to path dependency from sources such as `facebook` or `google` where conversations can only be initiated by the contact. 

The reasons to include the concept of `Contacts` as a separate entity from `Conversations` are: 

- A contact could be imported or created before the first message is sent (e.g. imported from lists or CRM systems), so that for sources that don't require to initiate the conversation by the contact (e.g. SMS or WhatsApp), the first message in a conversation could be sent from the Airy instance to the contact   
- There could be several conversations that all relate to the same physical person i.e. contact (e.g. the same person on WhatsApp, Facebook, Google or talking to different Facebook pages)
- It would generally be the better fitting place to store and modify profile information (names, avatar images, etc.) instead of the metadata store of conversations syncing information in the way they are stored in existing CRM systems (Salesforce, etc.)

**Describe the solution you'd like**

1. Introduce Contact Objects as a separate Topic:

```
{
  "id": "UUID",
  "first_name": "Mike",
  "last_name": "Smith",
  "display_name": "Mike Smith",
  "avatar_url": "SOMEURL",
  "title": "Chief Developer Evangelist",
  "gender": "somevalue",
  "timezone": 2.00, // relative to GMT
  "locale": "en_US",
  "organization_name": "Airy GmbH", 
  "contact_details": {
    "phone": "+49123456789",
    "email": "liz@airy.co",
    "key": "value" // would be freely extendible
  },
  "address": {
    "organization_name": "Airy GmbH"
    "address_line1": "Some Street"
    "addess_line2": "",
    "postcode": "12346",
    "city": "Berlin",
    "state": null,
    "country": "DE"
  },
  "conversations": [
    {
      "conversation_id": "UUID",
      "source":  "chat_plugin"
    },
    {
      "conversation_id": "UUID",
      "source":  "facebook"
    }  
  ],
  "metadata": {
    "facebook": { 
      "psid": "1234567890",
      "page_id": "9876543210"
    },
    "salesforce_id": "ABC123",
    "zendesk_id": "XYZ789",
    "key": "value" // would be freely extendible
  },
  "created_at": "TIMESTAMP",
  "updated_at": "TIMESTAMP"
}
```

2. Introduce HTTP API Endpoints:

- POST `/contacts.create`: Creates a single contact object

- POST `/contacts.import`: Imports an Array of contact objects, e.g. names and phone numbers

- POST `/contacts.list`: Array of all contacts, should be queryable

- POST `/contacts.info`: Return contact information by contact id

- POST `/contacts.update`: Updates the contact object with additional information; empty values having `{ "key": ""}` should clear/remove the relevant property

- POST `/contacts.refetch`: source-specific, for a list of contact ids, refetch the contact information from the original source, e.g. Facebook  

- POST `/contacts.merge`: target contact_id and array of contact ids to be "merged" into target contact_id, by adding the relevant conversation in the conversations property to target and hiding the formerly separate contact_ids; when a formerly separate contact_id is queried, e.g. from a conversation, the information   

- POST `/contacts.delete`: contacts without a conversation should be deletable, otherwise only if the relevant conversation was archived or "removed" first

3. Consume Events for Contacts topic

Depending on the relevant source of the events the Contacts topic should be able to consume events from external systems, such as `contact.created`, `contact.updated`, `customer_created`, `customer_updated` to the extent the relevant events and their properties have been properly mapped to the contacts topic.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by chrismatix** [comment]
@steffh 
**3.**
> Depending on the relevant source of the events the Contacts topic should be able to consume events from external systems, such as contact.created, contact.updated, customer_created, customer_updated to the extent the relevant events and their properties have been properly mapped to the contacts topic.

This is an interesting requirement. Could you give an example of that? More to the point: Can those external systems be the same or different from messaging sources? In my mind, this is partially solved by `contacts.import`.

But it brings to mind another question: Should each existing conversation automatically create a contact in this database?

**2.**
>POST /contacts.refetch: source-specific, for a list of contact ids, refetch the contact information from the original source, e.g. Facebook

Implementation note: Since this data is stored at the conversation level, this will send a conversation metadata record indicating to the relevant source app that the data needs to be refetched.

> POST /contacts.delete: contacts without a conversation should be deletable, otherwise only if the relevant conversation was archived or "removed" first

Since we had agreed in#2294 that communication is not dependent on contact at all, all contacts are safe to remove at any time, right?


--- 
Overall I think this ticket is ready to be worked on. It also seems possible to make this data model fit a regular postgres database since the conversations → contacts pipeline is a one-way road. ("send message to contact only uses contacts for the conversation lookup")

**Comment by steffh** [comment]
@chrismatix

Sorry for the slow response here. Regarding your questions:

> This is an interesting requirement. Could you give an example of that? More to the point: Can those external systems be the same or different from messaging sources? In my mind, this is partially solved by contacts.import.

The idea was both, but usually the messaging sources don't provide for pushing events like `contact.updated`, but rather have a pull logic. That was the idea behind `POST contacts.refetch` e.g. to update the profile information for a Facebook contact. 

Some sources like Google deliver contact information with every message, so in that case we could extract that information from the message and update the contact in case the information differs from the information we have stored. 

The original idea behind the event listener referred to above was to listen to external sources like CRM systems, e.g. Salesforce that would provide for the corresponding events, e.g. an account or contact was updated.

A generic version of that would be to have to have a Segment-style ingestion logic for events relating to contacts, i.e. to have one `identify` action that creates or updates the contact and one `track` action that tracks events in regards to a contact such as clicks or purchases and stores them for the relevant contact.

> But it brings to mind another question: Should each existing conversation automatically create a contact in this database?

That's a good question. It depends on the design of the contact store and how you envision cleanups / merging of contacts to work. In a streaming logic I would say rather yes, so contacts would exist independently from conversations and any conversation would also create a contact, pointing to the conversation.

The way I understood our latest discussion, the contact could be safely removed or merged with another contact, as there would just be no contact pointing to the conversation anymore, or in case of a "merged" contact the remaining contact would point to more than one conversation in that case.

The `POST /contacts.info` or `POST /contacts.list` queries could take a `conversation_id` parameter, so the clients could look up contact information by just having the `conversation_id`. 

Depending on how we populate the relevant data tracked with the contact e.g. recent purchases, etc. such information could be considered by a human agent or a bot. Concrete use case: someone bought a product yesterday and asks a question a day later. It would be very beneficial for both the human agent and the bot to access those past purchases via the contact.   

> Since we had agreed in#2294 that communication is not dependent on contact at all, all contacts are safe to remove at any time, right?

Correct.

**Comment by chrismatix** [comment]
Hi @steffh,

perfect then I think we are aligned already. 
> The idea was both, but usually the messaging sources don't provide for pushing events like contact.updated, but rather have a pull logic. That was the idea behind POST contacts.refetch e.g. to update the profile information for a Facebook contact.

>Some sources like Google deliver contact information with every message, so in that case we could extract that information from the message and update the contact in case the information differs from the information we have stored.

Since this data fetching (both push and pull) happens on a source level it makes sense to me that: 
1. Contacts are automatically created from incoming conversations. 
2. Refetching triggers the sources to refetch the conversation metadata, which will get passed to contacts using the same ingestion as for `1.`

The rest is also very clear. I will write the docs first now and share them.

**Comment by steffh** [comment]
One more thought. It seems you are thinking in a RDBMS context for contacts. In a B2C logic, contacts usually exist independently from each other and are just grouped together e.g. in audiences based on tags, past purchae behavior (e.g. "VIP customers"). 

In a B2B logic, several contacts can belong to the same account, e.g. another company you are dealing with. 

I assume it shouldn't be a problem to add further relations to the contact model, such as accounts grouping contacts together later, otherwise I would add that requirement in the ticket above directly.

**Comment by chrismatix** [comment]
@steffh understood. I've opted for our existing approach to metadata for storage. This will make it easier to ingest messaging data and we can apply any sort of grouping using tagging. The only constraint that this will introduce is that - like with metadata - lists on the contact model won't be supported (see upcoming PR).

**Comment by juan-sebastian** [comment]
All the endpoints for the `api-contacts` service are implemented
