### ISSUE TITLE
Allow messaging new contacts (creating conversations)

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2294]
**Is your feature request related to a problem? Please describe.**

We would like to be able to start new conversations with contacts on messaging sources where this is possible. Currently this is only possible via Twilio so we will use it as a first case.

AS an Airy user
GIVEN I have a messaging source that supports sending messages to contacts connected (e.g. Twilio)
WHEN I send a message to a phone number that has not previously messaged me
THEN that message is delivered and the conversation is created on Airy.

AS an Airy user
WHEN I send a message to a source that **does not support** messaging contacts that have not messaged you yet
THEN the API call should fail

**Describe the solution you'd like**

Extend the `POST /messages.send` endpoint to include this mode of sending messages:

```json5
{
  "source_recipient_id": "+49 1234567", // or an email address
  "channel_id": "<airy uuid>",
  "message": {} // regular message body
}
```

Users will also be able to send messages to existing conversations this way.

**Comment by chrismatix** [comment]
It's important to note that conversations are a materialized view of messages in Airy. Therefore you cannot create a conversation without sending the first message. Respecting this rule has the added benefit of _preventing the creation of orphaned conversations without any messages_ (an issue in the previous platform).

Furthermore, we should not make this API depend on contacts, because they are not part of the messaging system and because each contact can have multiple messaging sources, which makes disambiguation in this endpoint tricky.

Therefore I would propose that we allow users to either provide the `conversationId` or the `sourceConversationId` when sending a message. 

`POST /messages.send`

```json5
{
  "source_conversation_id": "+49 1234567", // or an email address
  "channel_id": "<airy uuid>",
  "message": {} // regular message body
}
```

**Comment by steffh** [comment]
I can relate to the restriction to materialize conversations from messages, so thank you @chrismatix for explaining this.

I think the `source_conversation_id` property can be ambiguous as we usually can't influence the way these are created on the level of the source, so having this property for a phone number, an email address, etc. looks a bit strange to me.

The suggested design would also not fulfill the part if the requirement "having previously imported contacts" but actually extend it in a way to support use cases where no contact information has previously been imported, which might be a valid case.

Making it not dependent on contacts is actually a fair point, but that doesn't mean that previously imported contacts can't be referenced still.

What do you think of sth like this? 

`POST /messages.send`
```
  "recipient": { "phone": "+14151234567" }, // or "email": "some@address.com"
  "contact_id": "<airy uuid>", // optional value
  "channel_id": "<airy uuid>",
  "message": {} // regular message body
```   

We should be able to get the source type and sender from `channel_id`, so this design even would work for Facebook e.g. `recipient: {id: "PSID"}` given that even getting the PSID is equivalent to a receiving a conversation_id from the source. So I could send messages without looking up the Airy `conversation_id` as long as I know a unique identifier on the level of the source and the `channel_id`.

**Comment by chrismatix** [comment]
> I think the source_conversation_id property can be ambiguous as we usually can't influence the way these are created on the level of the source, so having this property for a phone number, an email address, etc. looks a bit strange to me because the actual conversation_id on the level of the source can still be <UUID> instead of +49151123456789.

I don't quite understand this point. The ambiguity is resolved by the `channel_id` which defines the source and thus the interpretation of the `source_conversation_id`. Those SCIds are by our own definition represented by a single string, so there is no need to nest them in a `recipient` field.

> The suggested design would also not fulfill the part of the requirement "having previously imported contacts" but actually extend it in a way to support use cases where no contact information has previously been imported, which might be a valid case.

It's true, but this case is much stronger since it fits the messaging sources without the need for the concept of sources. 

> Making it not dependent on contacts is actually a fair point, but that doesn't mean that previously imported contacts can't be referenced still.

Agreed and I am not unfavourable to the suggestion. However in an effort to strictly separate the concepts I would propose adding an endpoint to the planned contacts app #2293 

`POST /contacts.sendMessage`

```
{
  "contact_id": "<airy uuid>",
  "channel_id": "<airy uuid>",
  "message": {} // regular message body
}
```

This route looks up the contact's `source_conversation_id` given the messaging source of the channel and in turn calls the aforeproposed `/messages.send` endpoint. This way we provide both functionalities and cleanly separate contacts and messaging. 

If you are ok with this design I would create a separate `/contacts.sendMessage` ticket 🙏

**Comment by steffh** [comment]
I just meant we shouldn't call a property `source_conversation_id` when the actual `conversation_id` on the level of the source could be something totally different (e.g. a UUID and not a phone number), as it might be confusing to people. E.g. when you start a conversation on Twilio by sending a messages you just use their Send Messages endpoint with the payload `{"to": "+491234567", "from": "+123456789", "body": "some-text" }` and then they assign as conversation ID. That seems to be case for most sources that support the relevant use case so we can't possible know what the `source_conversation_id` will be before sending the message and creating the conversation on the level of the sources. So I would use a name that is more generic.

E.g. in supporting the use case you describe, we could even do sth. like:

`POST /messages.send`
```
{
  "to": "+14151234567", // or "to": "some@address.com"
  "contact_id": "<airy uuid>", // optional value
  "channel_id": "<airy uuid>",
  "message": {} // regular message body
}
```

I would actually prefer that design which is rather close to what you suggested before to introducing another route with the payload as referenced above. 

We still lack consistency in naming routes at the moment (we mix camelCase, snake case and names separated by dots). Also having two routes that send messages that are called `POST /messages.send` for conversations and `POST /contacts.sendMessage` seems to inconsistent to me.

In case you wanted to separate both use cases which adds complexity for the developer, a consistent way would be to do sth. like `POST /conversations.messages.send` and `POST /contacts.messages.send`.

**Comment by chrismatix** [comment]
> I just meant we shouldn't call a property source_conversation_id when the actual conversation_id on the level of the source could be something totally different (e.g. a UUID and not a phone number), as it might be confusing to people. E.g. when you start a conversation on Twilio by sending a messages you just use their Send Messages endpoint with the payload {"to": "+491234567", "from": "+123456789", "body": "some-text" } and then they assign as conversation ID. That seems to be case for most sources that support the relevant use case so we can't possible know what the source_conversation_id will be before sending the message and creating the conversation on the level of the sources. So I would use a name that is more generic.

@steffh Thanks for the explanation! In the Twilio case, the `source_conversation_id` is the `to` phone number. For every source that supports starting a new conversation without previous messages from the contact, there has to be some sort of identifier (like a phone number or an email) that we can use to send messages. 

Following our offline conversation however I can understand why `source_conversation_id` would looks surprising to users. Hence I propose `source_recipient_id`. (💡 By convention we prefix all ids not managed by Airy, but by sources with `source_`)

## contacts.sendMessage

We realized that while this endpoint seems convenient, a contact could have multiple identities within a given source (i.e. Facebook page scoped user ids or phone numbers). Therefore even a `<channel id, contact id>` tuple is insufficiently unambiguous to receive messages.

## Conclusion
We favor this extension of the message send endpoint.

`POST /messages.send`

```json5
{
  "source_recipient_id": "+49 1234567", // or an email address
  "channel_id": "<airy uuid>",
  "message": {} // regular message body
}
```

**Comment by steffh** [comment]
@chrismatix Thank you & I couldn't agree more.

**Comment by chrismatix** [comment]
@steffh I will edit the ticket body now to reflect that.
