### ISSUE TITLE
Check if new version is available when using the CLI

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#2305]
After one runs the CLI, we should check if there is a newer version available and inform the user to upgrade his CLI and his Airy Core instance.

**Comment by steffh** [comment]
This would be really helpful as currently `airy version` and `airy upgrade` don't indicate that there is a new version of the CLI available.

People could believe they are running the latest version of Airy while in fact they are just running the latest version that is known to the latest version of their CLI.

Running `airy upgrade` with CLI version `0.31.0` returns the following:

![Screenshot 2021-09-28 at 18 13 07](https://user-images.githubusercontent.com/9045481/135126469-798beec1-4f50-4686-89d9-1d121308761f.png)

Upgrading the CLI, then running `airy upgrade` with CLI version `0.31.1` returns the following:

![Screenshot 2021-09-28 at 18 13 23](https://user-images.githubusercontent.com/9045481/135126414-71419db2-43c2-4be0-9a9e-e54d3f8d2387.png)
