### ISSUE TITLE
Chatplugin bookmark bar overflow

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#2310]
**Describe the bug**
When opening a chatplugin page with the bookmarks open on Chrome, it overflows beyond the window

**To Reproduce**

1. Open a chatplugin installation like airy.co
2. Open the chatplugin
3. (see system and browser) and observe 

**Expected behavior**
There should be spacing between the top of the browser window and the top of the chat plugin.

**Screenshots**
![image](https://user-images.githubusercontent.com/4403838/129928292-395a4314-7742-427d-96d5-fba7cd072d15.png)

**Desktop (please complete the following information):**

- OS: Mac
- Browser: Chrome
- Version: 92

**Comment by AitorAlgorta** [comment]
![Screenshot 2021-08-25 at 12 20 20](https://user-images.githubusercontent.com/6797037/130773560-b86df46c-9199-4313-84aa-8ae68065a3fa.png)
This doesn't happen anymore. it was fixed with #2314 by https://github.com/airyhq/airy/pull/2315/files
