### ISSUE TITLE
Display any source in the inbox

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#2328]
## Is your feature request related to a problem? Please describe.

Whenever we add a new [source](https://airy.co/docs/core/getting-started/glossary#source) to Airy the inbox will crash when it receives messages for that source.

This is because there are some places where we hard-code the available sources with a switch ([example](https://github.com/airyhq/airy/blob/b1dd87e30365195345581314566d62c60b87310a/frontend/ui/src/components/IconChannel/index.tsx#L38)).

## Describe the solution you'd like

- [x] Display an unknown source with a default icon
- [x] Render messages for unknown sources by simply displaying the `message.content` of the message as text. If possible we could visually distinguish these messages from messages that can be rendered.
- [x] There's no need to display them on the channels page

**Comment by AudreyKj** [comment]
what if we receive a template, or an image (something other than text) from an unknown source? Should we display 'unknown message type'?

**Comment by chrismatix** [comment]
@AudreyKj good question! Both are usually in some sort of payload. I.e.
```
{
  "message": {
    "content": { // source specific content
      "attachment": {
        "url": "some image url"
      }
    }
  }
}
```

I'm arguing for displaying the `content` field that we try and parse in the renderer as a string. I.e. by using `JSON.stringify(message.content, null, 2)`:

![image](https://user-images.githubusercontent.com/4403838/130647988-6472a95f-6900-4950-bea5-06b86747da9a.png)

Bonus points: Adding some visual cue (color, small header), to point out that this is the raw source message payload :)

**Comment by AitorAlgorta** [comment]
It's a good idea. What do you think @lizhutter?
