### ISSUE TITLE
Prevent second 'Enter' or double click when sending messages

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2358]
Currently in the Inbox, a system user is able to send a message twice (or even three times) if they accidentally click the `Send` button more than once or press `Enter` more than once.

We should disable this so that users are prevented from accidentally resending the same message within a few seconds. We could possibly run a script in the background to block the button from being clicked multiple times, possibly within 3 or 5 seconds - happy to discuss this.

**Comment by AudreyKj** [comment]
A good solution would be to prevent any action to happen when the user clicks on the send button when the input, the templates and selected reply are empty (which means that there isn't anything to send)
