### ISSUE TITLE
Icons for Rendering/Sending File Attachments

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2405]
When a system user sends or receives a file attachment, we should change the icon displayed below the contact's name.

<img width="320" alt="screenshot_2021-09-15_at_12 50 06" src="https://user-images.githubusercontent.com/74183162/133425410-9be7a1e6-5b4c-48a4-b9aa-4e4241fe3be0.png">

For example, we can use these images (and others as well if we have the capabilities) from [this website](https://www.zwicon.com/cheatsheet.html) to display the correct file type that has been sent/received.

### Images
<img width="842" alt="Screenshot 2021-09-15 at 13 27 38" src="https://user-images.githubusercontent.com/74183162/133425621-4fa18aca-2ff2-4072-9d45-82d507d8b09f.png">

### Audio
<img width="832" alt="Screenshot 2021-09-15 at 13 27 50" src="https://user-images.githubusercontent.com/74183162/133425617-e57f36b7-56ea-4916-8651-4558a41487fd.png">

### Video
<img width="862" alt="Screenshot 2021-09-15 at 13 27 16" src="https://user-images.githubusercontent.com/74183162/133425619-de56e6fb-e49d-4bb8-98b4-48fa842ddeaa.png">

### File
<img width="830" alt="Screenshot 2021-09-15 at 13 40 04" src="https://user-images.githubusercontent.com/74183162/133426806-9b96ed03-dd44-4aac-9f63-797da4fb747b.png">

**Comment by AudreyKj** [comment]
follow up #2109
