### ISSUE TITLE
Instagram Source: Render Messages with Media & Share in Inbox UI

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2406]
**Is your feature request related to a problem? Please describe.**

Messages with Media in Instagram are currently rendered as "Unknown Message Type" in the Inbox UI.

<img width="500" alt="Screenshot 2021-08-01 at 15 03 27" src="https://user-images.githubusercontent.com/9045481/127771907-d7455038-312c-49c8-8bc7-a904c5bdc456.png">

**Describe the solution you'd like**

Messages with Media / Shares

Source: https://developers.facebook.com/docs/messenger-platform/instagram/features/webhook/#message-with-media--permanent-image-video-file-media-share-

```
 {
      "id": "2d6e6111-a149-570c-b101-553ac50ff4a7",
      "content": {
        "sender": {
          "id": "0987654321"
        },
        "recipient": {
          "id": "1234567890"
        },
        "timestamp": 1631741660550,
        "message": {
          "mid": "aWdfZAG1faXRlb",
          "attachments": [
            {
              "type": "share", // or one of {video|audio|file|image} = direct message
              "payload": {
                "url": "https://lookaside.fbsbx.com/ig_messaging_cdn/?asset_id=abc&signature=defghij"
              }
            }
          ]
        }
      },
      "sent_at": "2021-09-15T21:34:20.550Z",
      "delivery_state": "delivered",
      "source": "instagram",
      "metadata": {},
      "from_contact": true
    } 
```

should be rendered as:

- Case `type: image`: Preview Image like attachments + Link to fullscreen overlay or with `target=_blank`

- Case `type: video`: Media Icon / "Video" + Link to fullscreen overlay or with `target=_blank`

- Case `type: audio`: Media Icon / "Audio" + Link to fullscreen with `target=_blank`

- Case `type: file`: Media Icon / "File" + Link to fullscreen with `target=_blank`

- Case `type: share`: Text "Shared Post" + Link to fullscreen with `target=_blank`

Unlike Stories we can assume the links will not expire, even though the CDN eventually will expire. We are also not allowed to cache Instagram content.

**Describe alternatives you've considered**

-

**Comment by AudreyKj** [comment]
depending on #2109
