### ISSUE TITLE
SideBar does not appear on Install & Customize (Chatplugin)

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#2407]
## Describe the bug

The sidebar does not appear when you go to Channels / Edit a connected channel and click Install & Customize.

## To Reproduce

1. Connect a chatplugin channel
2. Edit this channel
3. click on Install & Customize
4. See missing sidebar

## Expected behavior

On this screen the sidebar should appear 

## Screenshots

<img width="1440" alt="Screenshot 2021-09-16 at 14 40 17" src="https://user-images.githubusercontent.com/49147864/133614507-2b85c1ad-84f8-4370-84c2-c1633e8815bc.png">

## Environment

- Browser: [e.g. Chrome, Safari]
- Version: [e.g. 22]

**Comment by AitorAlgorta** [comment]
closed by #2431
