### ISSUE TITLE
Previously installed Vagrant Box still used on major infrastructure upgrades

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#243]
## Actual Result:

- GIVEN: As a user having installed Airy Core previously with vagrant box `mrvantage/centos7-minikube` (vs. 1.1.1-20200929),
- and having pulled the latest code from the `main` branch of the repo specifying `generic/alpine310` as the new vagrant box,
- and having *NOT* destroyed the previous VM via `vagrant destroy`,
- WHEN I run `./scripts/bootstrap.sh` again,
- THEN the new vagrant box `generic/alpine310` is not downloaded and used for the build,
- THEN the old vagrant box `mrvantage/centos7-minikube` (vs. 1.1.1-20200929) is still used for the new build, 
- THEN an update check is still performed for the old box `mrvantage/centos7-minikube` (vs. 1.1.1-20200929), 
- THEN a warning message is displayed as follows:

```
Bringing machine 'airy-core' up with 'virtualbox' provider...
==> airy-core: Checking if box 'mrvantage/centos7-minikube' version '1.1.1-20200929' is up to date...
==> airy-core: A newer version of the box 'mrvantage/centos7-minikube' for provider 'virtualbox' is
==> airy-core: available! You currently have version '1.1.1-20200929'. The latest is version
==> airy-core: '1.1.2-20201105'. Run `vagrant box update` to update.
```

## Expected Result:

- The previously used VM should be destroyed on major infrastructure updates,
- The relevant vagrant box should be removed,
- The new vagrant box should be downloaded and applied to the build as specified in the configuration of the updated code,
- All existing data should be successfully migrated to the extent this is possible

**Comment by lucapette** [comment]
duplicated of #186
