### ISSUE TITLE
Error when trying to connect a Channel without having provisioned the relevant Source

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#244]
## Actual Result:

- As an Airy developer trying to connect a new Channel 
- GIVEN I have *NOT* successfully provisioned the relevant Source before trying to connect (i.e. I have not changed the `airy.conf` standard settings and/or I have not run `vagrant provision --provision-with airy-conf`) 
- GIVEN I have a valid token to connect the Channel
- WHEN I send an authenticated request to `/channels.connect`
- THEN I receive a Status Code 500 Error with the following message: 
```
{
  "message": "400 Bad Request: [{\"error\":{\"message\":\"Invalid Client ID\",\"type\":\"OAuthException\",\"code\":101,\"fbtrace_id\":\"AyK7B3rSZvhyIDyvudx304X\"}}]"
}
```

## Expected Result:

- The relevant request is not send to the Source as we can expect it to fail
- Instead a 403 HTTP Status (Forbidden) should be send back to the Client indicating that the request could not be processed due to a missing precondition (Provisioning of the source and/or configuration variables missing)

**Comment by lucapette** [comment]
this will automatically get "solved" by the new design discussed in #223 (another sign we're going into the right direction with this). So I will close this issue.
