### ISSUE TITLE
Airy Live Chat customization: chat bubble colors

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2455]
Currently, the Live Chat has these two colors as the default chat bubble colors.

![Screenshot 2021-10-01 at 13 59 44](https://user-images.githubusercontent.com/74183162/135616418-a2ec1de5-480a-4866-8ffc-bd43b4230185.png)

We should make these customizable, just like background color and the other customization options.

**Comment by AitorAlgorta** [comment]
![Screenshot 2021-11-15 at 16 31 03](https://user-images.githubusercontent.com/6797037/141808974-69030368-31cc-4cb7-a0ff-5c95e3f984ec.png)
