### ISSUE TITLE
Google Cloud Platform Terraform module

### ISSUE THREAD

**Issue by pascal-holy** [airyhq/airy#2556]
We should also support GCP for creating a Kubernetes cluster with Terraform by creating a wrapper module similar to our EKS module for [this](https://github.com/terraform-google-modules/terraform-google-kubernetes-engine).

- [x] Create the module
- [ ] Create the install directory
- [ ] Create a GCP GKE instance from the install/gcp directory
- [ ] Destroy a GCP GKE instance from the instance/gcp directory

**Comment by ljupcovangelski** [comment]
The module should be placed under `infrastructure/terraform/modules` with the name `google`.

After the module is done, there should be also a directory called `google` under `infrastructure/terraform/install`. This directory should later be used by the CLI when invoking the `install.sh` script with `PROVIDER=google` in `install.flags`.
