### ISSUE TITLE
Allow TextArea to display multiple elements to send

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#2562]
## Is your feature request related to a problem? Please describe.

Right now, the `textArea `in the `Messenger` only displays one element at a time: either text, template or attachment.

for example, we cannot send text along with a template:
<img width="661" alt="Screenshot 2021-11-09 at 13 13 55" src="https://user-images.githubusercontent.com/38159391/140922427-a05c456d-8ec9-48fc-80e0-4b174541fd40.png">

## Describe the solution you'd like

We could improve this by allowing the input to accept multiple elements (2 or more is up to discussion), for example:
- text + attachment or template

## Additional context

Below are some screenshots of the way others messaging companies have implemented it:

SLACK 

<img width="1156" alt="Screenshot 2021-11-09 at 12 42 03" src="https://user-images.githubusercontent.com/38159391/140918003-c47391a8-32eb-474b-b4af-f3a5afd9d872.png">

FACEBOOK MESSENGER 

<img width="313" alt="Screenshot 2021-11-09 at 12 46 20" src="https://user-images.githubusercontent.com/38159391/140918588-6bd9bd27-46dd-41ed-aa59-eebd4b007092.png">

**Comment by AudreyKj** [comment]
what do you think @lizhutter @thorstenairy @AitorAlgorta

**Comment by AitorAlgorta** [comment]
It looks pretty good!

**Comment by AitorAlgorta** [comment]
It looks pretty good!
