### ISSUE TITLE
API: Expose Facebook Page Tokens via Channels API

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2622]
## Is your feature request related to a problem? Please describe.

As an Airy developer,
I want to see channel specific credentials (such as Facebook Page Tokens for sources of type `facebook` and `instagram`), 
so that I can monitor the health of the token and send direct API calls, e.g. to edit the messenger profile.

At the same time I would wish for more consistency regarding API calls and responses, e.g. the Channel Connect Request for source type `facebook` returns the `page_id` as `source_channel_id` while the relevant request for source type `instagram` returns the `account_id` as `source_channel_id` and doesn't return the `page_id` at all while the parameter is still required for `POST /channels.instagram.connect` (https://airy.co/docs/core/api/endpoints/channels#instagram).

![Screenshot 2021-11-29 at 11 33 30](https://user-images.githubusercontent.com/9045481/143852394-316c6100-bc3f-442c-87bd-9eb1e2cfe3c4.png)

![Screenshot 2021-11-29 at 11 43 13](https://user-images.githubusercontent.com/9045481/143853813-26c06e84-808c-4e1c-9786-869430398bac.png)

## Describe the solution you'd like

To an authenticated request to `POST /channels.list` return channel-specific credentials and allow for consistency at least in metadata with the corresponding connect-request for the relevant source type. Repeat key-value-pairs if the naming is not consistent, so the developer doesn't have to guess what means what for which source.

```
 {
      "id": "daf6df04-7883-5309-9a33-1fc880ed1567",
      "source": "instagram",
      "source_channel_id": "17841400425075798",
      "connected": true,
      "metadata": {
        "name": "SOMENAME",
        "page_id": "FB-PAGE-ID",
        "page_token": "FB-PAGE-TOKEN",
        "account_id": "17841400425075798"
      }
    }
```

Feel free to rename properties as it makes sense.

## Describe alternatives you've considered

We could provide an API Wrapper that sends authenticated requests to the source API, e.g. to access Messenger Profile, etc. 

## Additional context

-

**Comment by steffh** [comment]
@juan-sebastian ideally the old ones would have the metadata as well. since we are not talking about hundreds of them we could also manually reconnect them.

**Comment by juan-sebastian** [comment]
It would make a cleaner solution if we can reconnect the old ones

**Comment by steffh** [comment]
yes, it should be no problem to do that as we have business user access to all relevant facebook channels for the customers on managed cloud. regarding the instances running on open source, there was no requirement so far in that regard, but we could add it to the docs in the relevant section that we recommend to reconnect a channel in case someone was missing metadata information for the relevant API.

**Comment by juan-sebastian** [comment]
@steffh The PR is merged after the release you can reconnect the users, to have the new metadata
