### ISSUE TITLE
Return delivery error metadata

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#2623]
## Is your feature request related to a problem? Please describe.

In case delivery for a Facebook message fails, I want the reason of failure to be returned async via metadata webhook/websocket.

## Describe the solution you'd like

When sending a message to Facebook using `/messages.send` fails I want to receive the error in the metadata.

**Comment by steffh** [comment]
@chrismatix: can we make the implementation of this generic for all sources? 

The same problem exists for all conversational sources.

**Comment by chrismatix** [comment]
@steffh The mechanism to send metadata back already exists, but actually doing so is, unfortunately, source-specific. But we can expand the ticket to add this to all sources.

The only way to make this source agnostic is by using the [source api](https://airy.co/docs/core/api/source).

**Comment by steffh** [comment]
okay i see, thanks @chrismatix. if it's not too much effort implementing it in all sources + source api in the same way, that would make things easier for the clients not to differentiate between sources.

**Comment by chrismatix** [comment]
@steffh It's implemented for all current sources now (the source API already had this). Here are the new docs https://deploy-preview-2657--docs-airy.netlify.app/api/endpoints/messages#error-handling

**Comment by steffh** [comment]
@chrismatix thank you! perfect!
