### ISSUE TITLE
Webhook firing multiple times and firing still when being unsubscribed

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2642]
## Describe the bug

`POST /webhooks.list` is returning incorrect results

a) The webhook is still firing when all webhooks are unsubscribed in some instances:

![Screenshot 2021-12-08 at 12 58 43](https://user-images.githubusercontent.com/9045481/145214872-9a51799e-ddfa-4ffb-8af0-1de555525740.png)

b) The webhook is firing twice to the same endpoint when only one webhook is subscribed in several instances 

## To Reproduce

1. Subscribe / unsubscribe an endpoint for webhooks
2. Check POST /webhooks.list
3. Observe events arriving at the endpoint URL being inconsistent with 2.

## Expected behavior

- Each webhook should fire only once when subscribed to one endpoint.

- All webhooks being subscribed and unsubscribed should be correctly returned by `POST /webhooks.list`

## Screenshots

see above

## Environment

- Airy instance latest version (0.35.1)

## Additional context

-

**Comment by juan-sebastian** [comment]
I run the following scenarios. during my research

##  Terminate and subscribe 
1. terminate `webhook-publisher` microservice
2. subscribe outbound webhook
3. write something in the chat-plugin that is connected to the cluster
4. restart `webhook-publisher` microservice

The new message is received as expected.

## Terminate and unsubscribe
1. terminate `webhook-publisher` microservice
2. unsubscribe outbound webhook
3. write something in the chat-plugin that is connected to the cluster
4. restart webhook-publisher` microservice

The new message is **not** received as expected.

## Subscribe and unsubscribe
I tried to subscribe and unsubscribe using autogenerated UUID and reusing UUID. in between each action I sent a message on the chat-plugin the outbound webhook behaves as expected

## Conclusion
The `webhook-publisher` and `api-admin` microservices seems to be working just fine. I just find something interesting but I don't know if normal behaviour.

Here below there is one of the webhook's request body. As you can see the `type` **conversation.updated** it is duplicated. this is the case in every response. Is that expected?

```json
{
  "payload": {
    "conversation_id": "7fa31256-b5f1-484d-884e-e4acbf85b6c6",
    "channel_id": "2d854491-1190-4fe2-b68a-a63f49034411",
    "message": {
      "id": "ef602f5b-6c5a-426c-9325-99db997bb950",
      "content": {
        "text": "hola"
      },
      "sent_at": "2021-12-23T16:15:19.306Z",
      "delivery_state": "delivered",
      "source": "chatplugin",
      "metadata": null,
      "from_contact": true
    }
  },
  "timestamp": 1640276119306,
  "type": "message.created"
}
{
  "payload": {
    "conversation_id": "7fa31256-b5f1-484d-884e-e4acbf85b6c6",
    "channel_id": "2d854491-1190-4fe2-b68a-a63f49034411",
    "message": {
      "id": "ef602f5b-6c5a-426c-9325-99db997bb950",
      "content": {
        "text": "hola"
      },
      "sent_at": "2021-12-23T16:15:19.306Z",
      "delivery_state": "delivered",
      "source": "chatplugin",
      "metadata": {},
      "from_contact": true
    }
  },
  "timestamp": 1640276119306,
  "type": "message.updated"
}
{
  "payload": {
    "id": "7fa31256-b5f1-484d-884e-e4acbf85b6c6",
    "created_at": "2021-12-23T16:15:19.306Z",
    "metadata": {
      "contact": {
        "display_name": "Chatplugin 5b6c6"
      },
      "unread_count": 0
    },
    "last_message": {
      "id": "ef602f5b-6c5a-426c-9325-99db997bb950",
      "content": {
        "text": "hola"
      },
      "sent_at": "2021-12-23T16:15:19.306Z",
      "delivery_state": "delivered",
      "source": "chatplugin",
      "metadata": {},
      "from_contact": true
    },
    "channel_id": "2d854491-1190-4fe2-b68a-a63f49034411"
  },
  "timestamp": 1640276119306,
  "type": "conversation.updated"
}
{
  "payload": {
    "id": "7fa31256-b5f1-484d-884e-e4acbf85b6c6",
    "created_at": "2021-12-23T16:15:19.306Z",
    "metadata": {
      "unread_count": 1,
      "contact": {
        "display_name": "Chatplugin 5b6c6"
      }
    },
    "last_message": {
      "id": "ef602f5b-6c5a-426c-9325-99db997bb950",
      "content": {
        "text": "hola"
      },
      "sent_at": "2021-12-23T16:15:19.306Z",
      "delivery_state": "delivered",
      "source": "chatplugin",
      "metadata": {},
      "from_contact": true
    },
    "channel_id": "2d854491-1190-4fe2-b68a-a63f49034411"
  },
  "timestamp": 1640276120475,
  "type": "conversation.updated"
}
```

**Comment by steffh** [comment]
Thank you for looking into this @juan-sebastian! 

Did you check for the cases `Terminate and subscribe` and `Terminate and unsubscribe` whether the state was reflected correctly in the HTTP API via `POST /webhooks.list` after subscribing and unsubscribing?

In regards to the `conversation.updated` duplicate it's an interesting finding indeed. However it doesn't seem to be an exact duplicate as the `timestamp` and `unread_count` values are different for the two events.

It seems the first update is in regards to the `last_message` change, the second one is because the `unread_count` increased from 0 to 1. You are right though that I would have expected both properties to be changed in one event instead of two as the `last_message` change kind of is the reason why the `unread_count` changes.

**Comment by juan-sebastian** [comment]
Yes the output from `POST /webhooks.list` was always the one expected.

So basically the microservice that handles the subscription is `api-admin` when you call `POST /webhooks.list` is `api-admin` that you are calling. In the other hand `webhook-publisher` is the one that publish the data to the outbound webhook.

When you subscribe or unsubscribe `api-admin` push the state to kafka, then this is pick up by `webhook-publish` and reacts accordingly.

> the second one is because the unread_count increased from 0 to 1

Good catch I did not see that. So everything is working as expected.

**Comment by chrismatix** [comment]
Closing this for now as we found an issue in our setup that caused this bug.

**Comment by juan-sebastian** [comment]
Hello @steffh after a long investigation with @chrismatix. and running multiple scenarios we realised that the sources in the demo instances are connected to an other (staging) instance. Basically we look at the `Kafka` logs and beanstalkd everything is working as expected. Then we end up scaling down the web publisher and consumer.

There is when we realise that the sources are connected to two instances and that explains why we had double messages and when the `unsubscribe` was done the web hook still firing.
