### ISSUE TITLE
Expose Users' List via API

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2646]
## Is your feature request related to a problem? Please describe.

As an Airy developer developing a client or custom app,
I want to fetch a list of all users that authenticated successfully towards my Airy instance,
so that I can improve the collaborative work experience by giving more context 

## Describe the solution you'd like

Sending an authenticated request to `POST /users.list` should return a response such as:

```JSON5
{
  "data": [
    {
      "id": "user-id",
      "first_seen": "2022-01-11T16:07:23.602Z",
      "last_seen": "2022-01-12T16:07:23.602Z",
      "name": "Barbara Liskov", // optional
      "avatar": "http://example.org/profile.jpg" // optional
    },
    {
      "id": "user-id",
      "first_seen": "2022-01-11T16:07:23.602Z",
      "last_seen": "2022-01-12T16:07:23.602Z",
      "name": "Ada Lovelace"
    }
  ],
  "pagination_data": {
    "previous_cursor": null,
    "next_cursor": "2",
    "total": 104
  }
}
```

## Describe alternatives you've considered

- 

## Additional context

-

**Comment by chrismatix** [comment]
@steffh Currently we only store the user name, email and avatar in the logs. Would that suffice, too, for now?

**Comment by steffh** [comment]
@chrismatix - okay, just gives us whatever you have. i just assumed you stored the whole `oidc` payload.

**Comment by chrismatix** [comment]
Updated the payload. I think the `active` status should be inferred by clients to keep it flexible.
