### ISSUE TITLE
An older webhook event gets resent

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#2695]
## Describe the bug

An older `message.created` event is sent to a configured webhook.

## To Reproduce

We were not able to reproduce this behavior.

## Expected behavior

When a webhook event is sent and it gets a `200` confirmation that it has been received, it should not be sent again.

## Screenshots

/

## Environment

Version: `0.37.0` and `0.36.1`.

## Additional context

- The issue happens randomly at a certain point in time.
- We cannot correlate it with a crash/restart/deployment of the webhook apps or kafka.
- Might be a Kafka or a Beanstalk issue

**Comment by chrismatix** [comment]
Closing this now as we determined that this was due to a runtime error.
