### ISSUE TITLE
Webhook API: Make webhook subscription editable and resubscribable

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2722]
## Is your feature request related to a problem? Please describe.

Currently, the only way to update a webhook subscription as an Airy developer
e.g. in order to change the name or to modify the subscribed events or the subscribed URL is to 
(1.) unsubscribe an existing webhook via `POST /webhooks.unsubscribe`, and then
(2.) create a new webhook subscription via `POST /webhooks.subscribe`,
eventually leading to a long polluted result list when calling `POST /webhooks.list` 
containing a lot of old webhook subscriptions all having the state `unsubscribed`

## Describe the solution you'd like

(1.) I would suggest to introduce a new route `POST /webhooks.update`

Request:
```JSON5
{
   "id": "SOME_ID", // required, uuid
   "name": "SOME_NAME", // optional, string
   "url": "SOME_URL" // optional, string
   "headers": {} // optional, object
   "events": [] // optional, array.
   "signature_key": "SOME_KEY" // optional, string
}
```
Response: 

`200, returning updated Webhook payload`

AND (2): Resubscribe existing webhooks

Make `POST /webhooks.subscribe` also accepts a body with `{"id": "SOME_ID"}`  to resubscribe an existing webhook subscription (instead of only accepting a full webhook payload, resulting in creating an additional webhook subscription).

Response:  `200, returning updated Webhook payload`

## Describe alternatives you've considered

- (1): We could add `POST /webhooks.delete` with body `{ "id": "SOME_ID" }`  in order to clean up `POST /webhooks.list`; or
- (2): We could remove unsubscribed webhook subscriptions per default from the result of `POST /webhooks.list` so it doesn't contain unsubscribed webhooks anymore

## Additional context

-

**Comment by abhi-airy** [comment]
1) Should it possible to update an unsubscribed webhook through new update API?
	
	2) While resubscribing the event should it be possible to update the event at the same call or just make it subcribed? I mean user can send additional parameter to the resubscribing api along with the id. Please confirm
	
	3) In Subscribe Api call- What if  "id" parameter in subscribe API is Id of an unsubscribed webhook, do we need to show any error message or HttpStatus.BAD_REQUEST

**Comment by steffh** [comment]
hi, i mean all questions are lifecycle related with the biggest issues around this resubscribe behavior.

so it's mostly around whether `POST /webhooks.list` request should also include unsubscribed webhooks or if they should be simply removed and thereby retired.

so your first question would go away if we decided to remove unsubscribed webhooks from the list so you cannot resubscribe but just create new subscriptions and update existing ones but not unsubscribe and resubscribe.

would you agree and change the requirement in that regard?

we could also remove the status parameter as webhooks.list would only contain subscribed webhooks.

>> For reference:

1) Should it possible to update an unsubscribed webhook through new update API?

2) While resubscribing the event should it be possible to update the event at the same call or just make it subscribed? I mean user can send additional parameter to the resubscribing api along with the id. Please confirm

3) In Subscribe Api call- What if  "id" parameter in subscribe API is Id of an unsubscribed webhook, do we need to show any error message or HttpStatus.BAD_REQUEST
