### ISSUE TITLE
Media Resolver health check requires ListAllBuckets permission

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#2742]
The [health check](https://github.com/airyhq/airy/blob/12d2ff5d2a37424ae8a3265fe8792e15f8e544fd/backend/media/src/main/java/co/airy/core/media/services/MediaUpload.java#L81) uses the ListAllBuckets method to check if the S3 credentials are correct.

This requires access to all buckets of the account. In order to follow the Principle of Least Privilege, the health check should try to put a file in the exact `s3bucket` and in the `s3path` as specified in the `media-storage` config map.

**Comment by juan-sebastian** [comment]
Hello @pascal-airy, I just opened a PR for this issue, the health check now list objects in the `s3bucket`.

I don't think it is a good Idea to try to upload an object every time the heath check runs. We don't want to populate the bucket with garbage.

The only issue of this approach is that this only tests the read privileges.

**Comment by pascal-airy** [comment]
Thank you @juan-sebastian !
You are right that uploading is not necessary but could you only list the objects in the `s3path` because I want to limit each customer's access to their own folder.

**Comment by juan-sebastian** [comment]
Ok I can do that 👍
