### ISSUE TITLE
Support Recording Voice Messages from Airy Inbox UI

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#2744]
**Currently**: the Airy Inbox UI does not support recording voice messages.

**Ideally**: if a system user sends an audio recording via their Airy Inbox, it should be displayed (in the proper channel + with the proper contact) with a way to quickly and easily listen to the message. These recorded voice messages should render when communicating via sources that support this feature.

This feature should be bidirectional.

DESIGN ATTACHMENT:
Figma Files:

https://www.figma.com/file/Xy9aaCB3H0ARsDgze0ceDv/Support-Voice-Messages?node-id=0%3A1

**Comment by chrismatix** [comment]
@lizhutter great feature. I would definitely split add one issue per source for the backend though. Perhaps this warrants a 🌈 milestone 🌈

**Comment by lizhutter** [comment]
@chrismatix you used my favorite word, I was thinking the same - good idea💡 I'll create it

**Comment by M-Shorouk** [comment]
@AudreyKj @thorstenairy: @Edoardo333 is done with the design, please feel free to pick this ticket up
