### ISSUE TITLE
Run initial helm job from the CLI

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#2754]
As we want to decouple the Airy CLI from kubernetes, we need to have a way to run an initial helm job or deploy at least the `airy-controller`, so that we can interact later with it to apply the configuration and deploy additional helm jobs.

One way is to Deploy/Install Airy only with Helm and then after we install it, we use the CLI to interact with the cluster, only through the API.

The value that is in `airy create` is for quickly creating a Kubernetes cluster and installing Airy for quickstart and testing purposes. So we can still decide to maintain the `airy create` sub-command and migrate the code to Terraform (for now AWS or we can add multiple providers in the future).

**Comment by chrismatix** [comment]
As discussed back then: The easiest solution to this would be to simply print out the helm command that needs to be run by the user to do this.
