### ISSUE TITLE
Contacts service should be off by default

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#2791]
## Describe the bug

Currently the `api-contacts` service starts by default with a new installation. This should not be the case.

## To Reproduce

1. Install and start a fresh Airy instance

## Expected behavior

To run contacts you have to configure it in the airy yaml first.

**Comment by steffh** [comment]
@chrismatix what's the reasoning for not enabling it per default? saving resources?

what would happen if people switch it on/off later regarding existing conversations? wouldn't it make our life easier to have it on per default?

https://github.com/airyhq/airy/issues/2720

**Comment by chrismatix** [comment]
@steffh so sorry I must have missed that issue and yes the idea is to save resources. It's not a part of the core messaging functionality and the off by default setting does not incur any additional effort on our part.

**Comment by steffh** [comment]
@chrismatix - i just feel we need to give people more control on what is off/on per default. it's hard to find in the docs as the information is scattered in different places and people might not really get e.g. why inbox UI and chat plugin are on per default, but contacts isn't...

when restarted later would it still create contacts pointing to conversations for past messages or only after being switched on?
