### ISSUE TITLE
Chat Plugin: Customize Font

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#2808]
## Is your feature request related to a problem? Please describe.

As a user of the Airy Chat Plugin I want to be able to customize the font. 

## Describe the solution you'd like

Add a config option to:

1. Load a custom font as a resource, e.g. from Google Fonts, default value: `https://fonts.googleapis.com/css?family=Lato:300,400,700,900` giving people the option to change it to other fonts or remove it
2. Set a system font stack as css default: `font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`

## Describe alternatives you've considered

- 

## Additional context

Loading a font from a Google Fonts CDN directly might create some legal issues in certain jurisdictions due to local privacy laws.

**Comment by AitorAlgorta** [comment]
I think we have to do this because having the fonts inside the project is too costly for the bundle size. We have to find a way of disable the loading of the font and using a system font as fallback @thorstenairy
