### ISSUE TITLE
Reorganize Routes

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#2941]
**Problem?** 

Currently after a user or enteprise has successfuly deployed airy instance, the user is redirected to Inbox URL. 

**Solution?**

Creating unprotected URL to allow user to navigate through control center and inbox. 
As a step of creating control center and separating inbox as a component, 
the domain should be as follows:

1- companyName.airy.co = redirects to unprotected view to redirect the user to the following:
 1.1. companyName.airy.co/control-center = redirects user to Control Center to signin. 
 1.2. companyName.airy.co/Inbox = redirects user to inbox to signin. 

_User Story(open source):_ 

1. User successfully deploy air instance. 
2. On CLI, "companyName.airy.co" is provided after deployment. 
3. User is navigated to unprotected view which allows one to :
      3.1. Clicks on "Control center" = "companyName.airy.co/control center" and signin.
      3.2. Clicks on "Inbox" = "companyName.airy.co/inbox" and signin.

_User Story (Enterprise):_

1. Airy Eng. setup company instance and successfully deploy it. 
2. Airy provides customer with the following URLs:
2.1. App routing = "companyName.airy.co"
2.1. Control center route = "companyName.airy.co/control center"
2.2. Inbox route (IF ENABLED) = "companyName.airy.co/inbox"

FIGMA LINK

-------------------------------------------------------------

https://www.figma.com/file/wZoCeZuN9VIMmJ9G2hVvt1/Routing?node-id=0%3A1

-------------------------------------------------------------

**Comment by AitorAlgorta** [comment]
@ljupcovangelski sorry I just saw this. The idea is that the control center lives in `/control-center` and the inbox in `/inbox` (not in `/ui`) and then we have a small webpage in `/` that gives you the option of going to one or the other one
