### ISSUE TITLE
Kafka properties should be configurable from the core tf module

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#2958]
## Current Situation
When we want to make changes to the [configuration](https://github.com/airyhq/airy/blob/develop/infrastructure/images/kafka/config/server.properties) of Kafka we have to build a new image.

## Proposed Solution
Mount the configuration files via Kubernetes config maps.

**Comment by ljupcovangelski** [comment]
Sounds good. Perhaps we can mount the whole `server.properties` file from a configMap? And we can add values to the configmap, depending on parameters submitted to the Kafka helm chart.

**Comment by pascal-airy** [comment]
Currently, all env variables prefixed with `KAFKA_` are already added to the server.properties at startup with [this script](https://github.com/airyhq/airy/blob/develop/infrastructure/images/kafka/scripts/configure-kafka.sh) I think we should keep it like that and instead use the `configurationOverrides` [from Helm](https://github.com/airyhq/airy/blob/develop/infrastructure/helm-chart/charts/prerequisites/charts/kafka/charts/kafka/templates/statefulset.yaml#L92) to add additional configuration on top of the standard ones
