### ISSUE TITLE
Correlation between contacts and conversations in Airy 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3006]
Create endpoint internally for Airy contacts and conversations

**Comment by chrismatix** [comment]
@M-Shorouk While not explicitly stated in the docs, this is already possible using the [contacts update API](https://airy.co/docs/core/api/endpoints/contacts#update-contact). A request to connect a contact to conversation `123` of source `google` would look like so:

```POST /contacts.update````

```json5
{
"id": "contact-id",
"conversations":{
"123": "google"
}
}
```
