### ISSUE TITLE
Add chat plugin

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#302]
Port a minimum version of the Airy Chat Widget from `platform/ui/web/widget` to `core/frontend/chat_plugin`.

- [x] Builds
- [x] update API

**Comment by lucapette** [comment]
@chrismatix @AitorAlgorta can we please extract the docs to their own issue. I believe it would be probably big enough on its own (no strong opinion though. if you prefer to do it here, then please label accordingly)

**Comment by chrismatix** [comment]
WIll extract
