### ISSUE TITLE
Connectors view

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3032]
This entity only shows enabled/installed **Connectors** and the ability to manage the following:
1. Connector Authentication 
2. Connection to external systems 

Successful user story:
1. User signs in Control Center. 
2. User goes to catalog to install/enable a connector. 
3. User follows the installation flow. 
4. Connector has been successfully connected. 
5. New installed connector appears in "Connector" view entity. 
6. Connector card details can allows the user to manage authentication and connection to external system. 
7. Also connector is shown under "Installed" sector in "Catalog" view.

**Comment by AudreyKj** [comment]
https://www.figma.com/file/z6FBMPEDAQTFjGtfpXpOVn/Connectors?node-id=0%3A1
