### ISSUE TITLE
Webhook Subscription 

### ISSUE THREAD

**Issue by Edoardo333** [airyhq/airy#3046]
When the user clicks on the Subscribe button the pop up opens and show the required fields and parameters necessary for the Subscription.  

The view is gonna show the subscription modal. 

DESIGN URL :  https://www.figma.com/file/3HyGCZKQdClU51uu9z8rj9/WebHook?node-id=0%3A1

**Comment by AitorAlgorta** [comment]
this is done right? @Edoardo333 @M-Shorouk

**Comment by M-Shorouk** [comment]
@AitorAlgorta Yes. 

DESIGN URL: https://www.figma.com/file/3HyGCZKQdClU51uu9z8rj9/WebHook?node-id=0%3A1 
Also i added it to the relative FE ticket here: https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3050

**Comment by Edoardo333** [comment]
@M-Shorouk @AitorAlgorta 

Yes it is! Please write me if you have any questions!
