### ISSUE TITLE
Introduce CLI app

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#305]
In the context of this issue, we will:

- add a golang project (we need to decide where to put it in the mono repo)
- build the project with bazel
- `airy version` should reflect the content of `VERSION`

**Comment by chrismatix** [comment]
`infrastructure/cli` comes to mind. `tools` is for project tooling and `backend` is just not right. 

The main use case is controlling the installation, correct? (Off-topic: If that is so I will also suggest in our Enterprise meeting that the CLI is the main mode of delivery to clients).

**Comment by lucapette** [comment]
@chrismatix I think part of the discussion should be scoping the kind of command that the CLI has. In off-line conversations, I've been suggesting `cli` with the argument that the CLI application will be a jack of all trades for interacting/installing/managing the core platform (but `infrastructure/cli` would work anyway I think)

**Comment by pascal-airy** [comment]
I only now found this discussion. I will move the code to `infrastructure/cli`.
@ljupcovangelski was against having the cli do the installation. Also, I'm not sure how the cli will interact with the vagrant helm/kubernetes in Vagrant but also in the cloud. So I'd like to see more discussion here :)
