### ISSUE TITLE
Empty "Connectors" view state 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3091]

**Comment by Edoardo333** [comment]
![0.3_2_Connectors.png](https://images.zenhubusercontent.com/6203f269e0c6a1f80579f4a3/5567df8d-2d72-4ff5-a715-9b6ed3593cc2)

FIGMA ATTACHMENT:

https://www.figma.com/file/M7sKNf22aaA5t6MzHFe1Yz/Control-Center-0.3?node-id=0%3A1
