### ISSUE TITLE
Inbox config view + enabled sources

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3106]
On Control center, we want to show "Inbox" as a component on left nav bar when enabled.

**Comment by Edoardo333** [comment]
![0.7.1 VIEW OF INSTALLED SOURCES.png](https://images.zenhubusercontent.com/6203f269e0c6a1f80579f4a3/e4a5eb87-aca8-4e04-b294-40b045188461)

FIGMA ATTACHMENT: 

https://www.figma.com/file/M7sKNf22aaA5t6MzHFe1Yz/Control-Center-0.3?node-id=6%3A137

**Comment by thorstenairy** [comment]
design is done, just need to clarify how we want to handle channels in general

**Comment by M-Shorouk** [comment]
Sorry for the confusion... Channels are connectors and we should show them on "Connectors" view. @Edoardo333 will update the tickets soon🙌🏻

**Comment by M-Shorouk** [comment]
I will also close this ticket as it was wrong.
