### ISSUE TITLE
Channels new view on control center 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3118]

**Comment by Edoardo333** [comment]
![0.7.2 VIEW OF RUNNING CHANNELS.png](https://images.zenhubusercontent.com/6203f269e0c6a1f80579f4a3/1292f6ad-6a94-4656-b6a4-dafe495f6a78)

FIGMA ATTACHMENT:

https://www.figma.com/file/M7sKNf22aaA5t6MzHFe1Yz/Control-Center-0.3?node-id=6%3A137

**Comment by thorstenairy** [comment]
the new design is already done, we just need to clarify how we want to handle channels in general
