### ISSUE TITLE
Empty/No sources connected view of "Inbox"

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3122]
When a user successfully deploy air, they arrive to the "Routing" URL which allow the user to navigate to "Control Center" OR"Inbox". 

For a new user, they don't have any sources installed so they have to add communicational sources through "Control Center". 

Since "Inbox" is enabled by default and by the previous example it is shown that for an initial inbox config view, it would be empty since no "Source" are connected and the user does not have any enabled channels to config. 

We need to design a view for "Empty" inbox  which allows the user to install communication sources from "Catalog" to be able to config relative channels.

**Comment by Edoardo333** [comment]
![0.7.3 VIEW OF NO SOURCES.png](https://images.zenhubusercontent.com/6203f269e0c6a1f80579f4a3/7d9eadca-2031-4be4-b6e2-321cefac7921)

FIGMA ATTACHMENT

https://www.figma.com/file/M7sKNf22aaA5t6MzHFe1Yz/Control-Center-0.3?node-id=6%3A137

**Comment by thorstenairy** [comment]
design is done, need further discussion regarding channels in general

**Comment by M-Shorouk** [comment]
Sorry for the confusion... Channels are connectors and we should show them on "Connectors" view. @Edoardo333 will update the tickets soon🙌🏻
