### ISSUE TITLE
Enabling and disabling - Components on Control Center

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3178]
We need to allow System user to enable/disable components/features such as Contacts on Control Center.

Success story:

System user is on Control Center, Catalog view.
System user wants to enable a component on their Airy instance. e.g: Contacts, Inbox
System user clicks on "Enable".
The frontend should send such config. to CLI endpoint.
E.g.: "Contacts" is enabled on Airy core.
E.g.: Contacts appear on the left nav bar on control center to allow config.
E.g.: Contacts is Enabled on Inbox by "Contacts" view.
Control Center - DISABILING options:

Disable a "Service" from Status view.
Disable Connector from Connectors view.
Disable Component after installing and config from left nav. bar.
Control Center - ENABLING options:
1- Enable Components/connector from "Catalog" view,

**Comment by ljupcovangelski** [comment]
The enabling/disabling of components in the backend, addresses scaling up/down the deployments of a component, when the configuration is already present in the ConfigMap for that component.

In that sense, I think that it will be a good approach to `annotate` or `label` the configMap with a label `core.airy.co/enabled: true or false`. So the endpoint would only add annotation or label to the `configMap` and then when we receive an event about a changed configMaps in the `airy-controller` - we can:
- on configMap add - don't scale up if this is set to `false`
- on configMap delete - no change to the current code
- on configMap update - check if this value was changed and then scale up or down depending on if it is true of false.

**Comment by juan-sebastian** [comment]
I will do the front-end part in a separate PR
