### ISSUE TITLE
Install/uninstall on "Catalog" view 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3238]
On Catalog view, we need to allow system user to easily install and uninstall components.

1. Check endpoint list of installed components
2. Update component.status with the action of toggle button.
3. Update card segment:
  3.1. if the component was installed > 
      3.1.1. Pop-up message to confirm uninstallation. 
      3.1.2. Move Card back to "Uninstalled" segment and allow user to view the install button on component's card view. 
  3.2. If the components was "Uninstalled" > 
       3.2.1. Success installation message
       3.2.2. User can navigate to component/connector configure from pop up
       3.2.3. User can exist pop-up message and VIEW card moved to "Installed. 
        3.2.4. Allow user to view "Uninstall" button on component's card view.

**Comment by Edoardo333** [comment]
DESIGN RESOURCES: 

https://www.figma.com/file/q2TIfG2mQULdeqvh1C0Mi0/Untitled?node-id=0%3A1
