### ISSUE TITLE
Fixed contacts details view on third column

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3246]
While testing Contacts entity on Inbox, noticed that when a user selects a contact there is no way to exit this view unless the user selects another contact. The third column view stays expanded with no way to close it. 
Besides, when a contact is selected and the user moves to the next view of the list, where technically this contact is not on this list, going from page 1 > page 2, the same contact from page 1 is still shown on the third column. 

FIX: 

Add minimise button to contacts view on third column to allow user exit the contact view. 

ADDING THE DESIGN HERE WHEN ITS DONE.

**Comment by Edoardo333** [comment]
FIGMA LINK: 

 https://www.figma.com/file/aS4AO0yX3dMonNskWD6D77/Contact?node-id=208%3A2
