### ISSUE TITLE
Update Glossary 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3294]
Add following definitions:  

- Apps 
- Catalog > Installed & not Installed 
- Component : Defintion 
- Connectors : Configured/Enabled & Not Configured/Disabled 
- Status view : Green, Yellow, Red 
Glossary link: https://develop.docs.airy.co/getting-started/glossary

**Comment by M-Shorouk** [comment]
@AitorAlgorta can we push this with this release?

**Comment by AitorAlgorta** [comment]
isn't it already done?

**Comment by M-Shorouk** [comment]
@AitorAlgorta nop.. you can check here: https://airy.co/docs/core/getting-started/glossary

**Comment by M-Shorouk** [comment]
@AitorAlgorta will we be able to push these changes in the current release V.0.48.0 since its done already?
