### ISSUE TITLE
Control center status page taking 100% cpu

### ISSUE THREAD

**Issue by juan-sebastian** [airyhq/airy#3346]
## Describe the bug

Control center status page is taking 100% cpu

## To Reproduce

1. just open the control-center on the status page
2. leave it there open for at least 1 hour
3. then put your laptop to sleep and then wake it up
4. you will see that the control-center tab is taking 100% of cpu and slowing down everything. The only solution is to close the tab

## Environment

- OS: MacOS Monterey
- Browser: Chrome
- Version: 103.0.5060.53

**Comment by thorstenairy** [comment]
was solved in #3633
