### ISSUE TITLE
/components.list endpoint to retrieve component details 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3353]
For each component on Control Center, we need to retrieve specific detailed data about the component details such as: 

- Component Name.
- Component Description.
- Status of component "NOT INSTALLED"/Installed, as a tag.
- Available for : "Open-source" / "Enterprise" / "Cloud"
- Categories : "Communication Source" / "API" / "UI" / "Machine learning & Conversational AI" / "Analytics" / "Storage" / 9. "Customer Service" / "Marketing".
- Price : Free

Docs for content: https://docs.google.com/presentation/d/1ecTHtSDABuoKZMDhSw5GWycXFKt7VRMnu5jlzOtfnQQ/edit#slide=id.p 

I WILL ALLOW ACCESS AFTER REVIEWING THE CONTENT ;)

**Comment by AudreyKj** [comment]
```
{
  components: {
    'airy-core/sources-chatplugin': {
      installed: true,
    },
    'airy-core/sources-facebook': {
      installed: true,
    },
    'airy-core/sources-twilio': {
      installed: true,
    },
    'airy-core/sources-google': {
      installed: true,
    },
    'enterprise/dialogflow-connector': {
      repository: 'enterprise',
      installed: true,
    },
  },
};
```
