### ISSUE TITLE
Review sed replacements

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#336]
We need to review how we inject variables into our configmaps and secrets in the provisioning process and standardize it.

Particularly for these two sed replacements:
https://github.com/airyhq/airy/blob/develop/infrastructure/scripts/provision/core.sh#L16
https://github.com/airyhq/airy/blob/develop/infrastructure/scripts/provision/core.sh#L20

**Comment by pascal-airy** [comment]
Fixed by #404
