### ISSUE TITLE
Status is red when component is disabled 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3362]
On Control Center, Status view, when a component is disabled, the status bar is red instead of grey.
 ![Screenshot 2022-07-01 at 16.17.21.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/0553d1b5-7c6d-4fdf-834e-07204139adb9)

**Comment by thorstenairy** [comment]
fixed in #3321
