### ISSUE TITLE
Connector view error 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3474]
## Describe the bug

On Control Center, after installing "Zendesk" from "Catalog", i can't see the component card moved to "Connectors" view to configure connector. 

## To Reproduce

1. Open Catalog view on Control Center. 
2. Click Install button on "Zendesk" component.
3. Exit configuration 
4. See error when clicking on "Connectors" view that "Zendesk" connector card hasn't been shown to configure. 

## Expected behavior

After installation, the component.connector is shown on "Connector" view to allow Airy user configure the connector. The card of the connector should also show the relative health.status of this connector; = "Not Configured" 

## Screenshots

FIG1. HOW IT CURRENTLY LOOK ON CATALOG VIEW > INSTALLED COMPONENTS 
![Screenshot 2022-07-21 at 12.32.46.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/9d85a550-1c74-42e4-85f3-a397708eaeb9)

FIG2. HOW IT CURRENTLY LOOK ON CONNECTOR VIEW > CAN'T SEE CARDS FOR INSTALLED CONNECTORS. 
![Screenshot 2022-07-21 at 12.34.04.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/db2538e4-e636-4d39-9f8b-bcb09252fed5)

## Environment

- Browser: [e.g. Chrome]
- Version: [V.0.47.1]

## Additional context

This behaviour happens for all other components except "Airy Chatplugin"

**Comment by AudreyKj** [comment]
this probably means that the `install `request has failed

**Comment by M-Shorouk** [comment]
@AudreyKj configuration goes well if you click on "To configure" and also the connector gets enabled... Still doesn't show on either "Connector" nor "Status" view..

**Comment by M-Shorouk** [comment]
adding here hot it looks on "Status" view after Installing and Enabling "Zendesk". As you see below, the component is not there also after refreshing for sometime. 

<img width="1423" alt="Screenshot 2022-07-21 at 15 48 33" src="https://user-images.githubusercontent.com/97036817/180229622-7ebdc672-cb8c-4e5e-83f4-a2b2613277f3.png">
