### ISSUE TITLE
Airy CLI airy core host bug 

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#3477]
## Describe the bug

Running a local instance from the latest develop and CLI version (0.27.0) fails with this error: 

`could not apply components config:  Post "http://airy.core/components.update": dial tcp 192.168.59.141:80: connect: connection refused`

## To Reproduce

1 - run a local instance with` scripts/dev_cli.sh create --provider=minikube ../my-airy`
2 - see the error listed above trigged at the end of the process 
3 - see the hosts with `cat /etc/hosts` and observe that airy core points to `192..`
4 - update airy core host with `sudo nano /etc/hosts` to `127.0.0.1 `
5 - restart Docker to delete containers 
6 - run a local instance with` scripts/dev_cli.sh create --provider=minikube ../my-airy`
7 - it now works 

## Environment

- OS: iOS - Big Sur 11.6.6

**Comment by ljupcovangelski** [comment]
The issue was in the `airy.yaml` file, we deprecated `airy.core` as a hostname for the local instance and we moved to `localhost`.

So in the `global` and the `ingress-controller` sections should be like this:

```
global:
  host: localhost
ingress-controller:
  ngrokEnabled: true
```
