### ISSUE TITLE
Component card details on Catalog 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3489]
## Is your feature request related to a problem? Please describe.

As an Airy user, i need to view all available component details on Catalog to learn more about it. 

## Describe the solution you'd like

We need to design card details view for components to present each component details. 

CARD DETAILS VARIABLES from DynamoDB: 

1. Component logo.
2. Component Name. 
3. Component Description. 
4. Available for : "Open-source" / "Enterprise" / "Cloud"
7. Price : Free  
8. Categories : "Communication Source" / "API" / "UI" / "Machine learning & Conversational AI" / "Analytics" / "Storage" / "Customer Service" / "Marketing". 
9. Docs reference.
10. Back button to go to Catalog main view. 
11. Install Button/Uninstall button. 

**Buttons flow:** 

1. Install button on Catalog view > Instant install > Pop-up to confirm Installation and action to either configure component or exist pop-up. 
2. Install button on Card details view > Instant install > Pop-up to confirm Installation and action to either configure component or exist pop-up. 
3. Open button on Catalog view > Navigates to Component configuration > ""/airy.co/control-center/connectors/connected/#componentName".
4. Uninstall button on Card details view > Pop-up to confirm uninstalling this component or exit. 

## Additional context

DESIGN URL: 
++add /components.list info on the attached design.

**Comment by Edoardo333** [comment]
FIGMA LINK: 

https://www.figma.com/file/CRt7x2PjccilajBaPO4HVW/Control-Center-0.6_3?node-id=260%3A300
