### ISSUE TITLE
Whatsapp Cloud  component on Control Center. 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3491]
## Is your feature request related to a problem? Please describe.
As an Airy user, i should be able to connect to with Whatsapp cloud source endpoint. 

## Describe the solution you'd like

Adding Whatsapp Cloud component to Control center to `/components.list` with the following flow: 

### Catalog View

1. Adding Whatsapp Cloud component to "Uninstalled" list to follow the installation process. 
2. Card details. 

**Connectors view** 

Whatsapp Cloud Component To configuration /components.: 

       1. `appId` = Whatsapp Cloud Page ID
       2. `appSecret ` = Token 
       3. `phone_number` = Phone Number
       4. `name` = " Name (optional)
       5. `avatar_url` = "Image URL" (optional)

     
Whatsapp Cloud Component to update after enabling : 

       1. `TO_PHONE_NUMBER` = Phone Number ??
       2.  `name` = Name (optional)
       3. `avatar_url` : Image URL (optional)
   
## Additional context

Reference: https://developers.facebook.com/docs/whatsapp/cloud-api/get-started/

**Comment by chrismatix** [comment]
@M-Shorouk like with the Facebook source I think it makes a bit more sense if users provide their `appId` and `appSecret` and when connecting channels send a token. This way we can handle access token expiry for the users.
