### ISSUE TITLE
Api-configuration design proposal

### ISSUE THREAD

**Issue by juan-sebastian** [airyhq/airy#3525]
# Implementation proposal

This component at its name implies, is going to handle the configuration of all `components`

<img width="683" alt="image" src="https://user-images.githubusercontent.com/36315790/188151313-c895d829-3712-4c0e-a67b-b5a121ea4b41.png">

This will consist on the CRUD endpoints, to configure.

## components.get

Gets the configuration of all installed components

<img width="609" alt="image" src="https://user-images.githubusercontent.com/36315790/188153219-ef00a0a7-3346-4205-bb98-b2e743b77c9b.png">

## components.update

Update the configuration of one or many components. If there is only one component to be updated the response will be 200 on success or 400 on failure. But if there is a group of components passed to the request. it will return always 200 and in the response you will see which components were updated successfully.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/36315790/188152498-b830fc5f-6b2f-41cb-a8f5-043d8cd559c5.png">

## components.delete

Delete will work similar to update it can receive one or more components at a time.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/36315790/188152807-57d1e070-fe31-4757-bcd6-4957b6296258.png">

**Comment by ljupcovangelski** [comment]
What does `components.delete` do? It deletes the configuration, not the component right? I think then the path should be `component.config.delete`.

I recommend we do them to accept one component at a time? It will be more clear and we can have better error handling. And we deprecate the way that `airy config applly` works (accepting multiple components at once). And remove the configuration from the `airy.yaml` file.

If we do that, then I recommend that they are not plural:
- `components.get` -> `component.config.get`
- `components.update` -> `component.config.update`
- `components.delete` -> `component.config.delete`

**Comment by chrismatix** [comment]
Great proposal. Thanks especially for the diagrams 👏 

> What does components.delete do? It deletes the configuration, not the component right? I think then the path should be component.config.delete.

I think it should delete the entire component. If it were the only the configuration then by convention the endpoint would be `components.deleteConfig`

> If we do that, then I recommend that they are not plural:

Given our current API convention, the namespace would stay plural ([example](https://airy.co/docs/core/api/endpoints/conversations#info)). However I do agree and would therefore propose that we don't wrap the data in `"components"`. What do you think?

**Comment by ljupcovangelski** [comment]
> I think it should delete the entire component.

But isn't that what `components.uninstall` does, from the other document proposal?

**Comment by AudreyKj** [comment]
Thanks for drafting this proposal @juan-sebastian 🚀 

I would keep `components.get` plural as an endpoint returning the configuration of all configured components. We need this data in the Control Center and in the frontend, it would be tedious to call the endpoint separately for each configured component. 

For `components.update`,  I remember that we said that in the future, we would need to update several components at the same time. I would leave this endpoint accepting several components as its parameter if this is still valid.

Regarding the naming, I like @ljupcovangelski's suggestion on adding 'config' as a prefix to make the endpoints' role of handling the configuration explicit (which reminds me of [slack's API naming](https://api.slack.com/methods?query=settings)).

**Comment by M-Shorouk** [comment]
Closing this discussion proposal ticket for this ticket [3877](https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3877)
