### ISSUE TITLE
Control Center - Facebook Messenger error to "Create Page" 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3538]
## Describe the bug

On Control Center, when Installing "Facebook Messenger" component from Catalog and I want to configure connector. After filling the channel info, the "Create page" button doesn't take any action.  

## To Reproduce

1. Install "Facebook Messenger" from Catalog on Control Center. 
2. Click to configure and fill channel info. 
3. See error when clicking on "Create Page" > no action is taken; channel hasn't been created & connector is not enabled. 

## Expected behavior

1. After adding a facebook channel for the first time, the connector health.status should be "Enabled". 
2. User is able to disable this channel after creating it. 
3. User should be able to disable the connector after creating at least one channel. 

## Screenshots

FIG1. View after clicking "Create page">> 

![Screenshot 2022-08-04 at 12.32.23.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/a23660fd-8f69-442a-878f-23491ef4becd)

## Environment

- Browser: [e.g. Chrome]
- Version: [V.0.48.0, V.0.49.0 - Support]

**Comment by AudreyKj** [comment]
I'm closing this issue as it is working now
