### ISSUE TITLE
Error in topic provisioning job in Airy Core Installation

### ISSUE THREAD

**Issue by armanjindal** [airyhq/airy#3575]
## Describe the bug

When upgrading from `0.47.0` to the latest version using Terraform, the topic provisioning job fails.
## To Reproduce

1. Take an existing Airy Core instance.
2. `cd terraform`
3. `cd core`
4. `terraform apply`

## Expected behavior

Airy updates without any error. 

## Screenshots
<img width="1294" alt="Screen Shot 2022-08-11 at 5 09 49 PM" src="https://user-images.githubusercontent.com/58370547/184170057-2fcf22a9-4a55-4f0e-891f-11d4bb03c931.png">

**Comment by ljupcovangelski** [comment]
Resolved.
