### ISSUE TITLE
Webhook components doesn't appear on left nav bar when installed

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3622]
## Describe the bug

On Control Center, on Catalog view, when "Webhooks" component is installed, the component configuration view on left navigation bar doesn't appear. 

## To Reproduce

1. Open Control Center, Catalog view. 
2. Find "Webhooks" compnent. 
3. See error that the component is installed but doesn't appear on left navigation bar for configuration. 
   3.1. see error when "Webhooks" component is not installed, the component configuration on left navigation 
         bar still appears. 
4. See another error that "open" button doesn't work; open webhook component configuration view. 

## Expected behavior

- When "Webhook" is installed, the comppnent should appear on left navigation bar for configuratiin. 
- When "Webhook" is not installed, the configuration component should not appear on left navigation bar. 

## Screenshots
![Screenshot 2022-08-22 at 12.37.20.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/1ba15c60-abd4-4a63-81d4-1e9d15cf8cf5)

## Environment
- Browser: [Chrome]
- Version: [Version 0.49.0-alpha]

**Comment by AudreyKj** [comment]
this is already fixed in my Pull Request #3624 (not merged yet, but will be soon!)
