### ISSUE TITLE
Webhook "To configure" error

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3623]
## Describe the bug

On Control Center, on Catalog view, after installing "Webhooks" components, the "To configure" button action doesn't work. 

## To Reproduce

1. Open Control Center, Catalog view. 
2. Install "Webhooks" component. 
3. See error after installation, click on "To configure", it doesn't navigate to webhook configuration view. 

## Expected behavior

After installing "Webhooks" component, Airy user should be able to configure component from "To configure" button found on successful installation pop-up.

## Screenshots

FIG.1. NO ACTION TAKEN WHEN CLICKING "TO CONFIGURE" BUTTON. 
![Screenshot 2022-08-22 at 12.47.39.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/5aaa98df-a867-47d5-af5b-0262a63a490b)

## Environment
- Browser: [Chrome]
- Version: [Version 0.49.0-alpha]

**Comment by AudreyKj** [comment]
this is already fixed in my Pull Request #3624 (not merged yet, but will be soon!)
