### ISSUE TITLE
Search navigation bar - Catalog View 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3641]
## Is your feature request related to a problem? Please describe.

As an Airy user, i need to search for components to Install or already installed on Catalog view. I need to be able to look up components by component.name. I can also filter the catalog view by components status: "Installed", "tag.Soon", "Uninstalled". 

## Describe the solution you'd like

As an airy user: 

1- I want to find a search navigation bar to be able to search for components by name. Navigation placeholder: "By:Name"
2- `/components.list` endpoint should retrieve component.name.
3- I should be able to either find the component i search for or get no results from` /components.list `endpoint. 
4- I should be able to filter Catalog view by `component.status?` > Installed, tag.soon, Not installed. 

## Describe alternatives you've considered

Suggestions? 

## Additional context
We are reusing the same design components for search navigation bar and filter as on Inbox.

**Comment by Edoardo333** [comment]
FIGMA LINK: 

https://www.figma.com/file/fqxGvk4E3dWbmWoJKlVjYU/Control-Center-10?node-id=780%3A7759
