### ISSUE TITLE
Deploy Airy on Google Cloud using Terraform

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#3645]
We need to be able to use the `infrastructure/terraform/modules/core` module to deploy `Airy Core` on the created GCP GKE instance.

**Comment by bilge-cakmak** [comment]
On the previous item the `infrastructure/terraform/modules/gcp-gke` module is using a module named gke_auth for exporting the kube.conf file. This module itself doing the authentication automatically and exporting a kube.conf file with a host, ca_certificate and token. All of them could be valid for an hour (3600s). Therefore my first focus was changing the kube.conf file generation. The work is there partial as using a credentials file is also not my first preference. 

Secondly, using a shared VPC network.. If there is a cluster using the same network terraform doesn't apply. I skipped this section by using a different network name but i think it is another blocker.

The third is using the shared state file with `terraform_remote_state` I think my knowledge on terraform providers is very limited. I was using the same kube.conf file and tfstate file but it is not really working. I will add the error as now. On the cluster I created the instance with helm and I was using a CLI named `terraformer` to get some reverse engineered ideas about the terraform plan. But yeah on core I have a problems with even using helm provider. So the problem starts from beginnninng.
