### ISSUE TITLE
Adding "Notify me" components to Catalog view 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3667]
## Is your feature request related to a problem? Please describe.

As an Airy user, i should be able to see the components in development or still not yet developed and request access to these components. 

## Describe the solution you'd like

Adding the following Components to Catalog: 

1. IBM Watson Assistant
2. Cognigy.AI
3. Amazon S3 

Successful case scenario: 

1. System user is logged in Control Center. 
2. System user navigates to Catalog view. 
3. System user checks components that are ready to Install. One also notice the "request access" button. 
4. System user is able to request access from the component rich card shown on Catalog view. 
5. System user is able to open rich card details and read more info about this component. 
6. System user is able to "request access" from the rich card details view. 
7. System user is eligible to fill a contact form so Airy team can get back to them. 
8. System user get a notification that the request has been sent. 
9. System user is able to see that the "request access" button has been changed to "Requested" after successful request. 

## Describe alternatives you've considered

Suggestions??

**Comment by ljupcovangelski** [comment]
@M-Shorouk "request access" to me sounds like the component is there and can be used, but I am not allowed to. More like it is protected as an enterprise component or similar.

If the component is in development, I don't see why it shouldn't be present in the Catalog, but market that it is `beta` or `unstable`? By default those components can be filtered out in the Catalog and visible through some toggle `Show unstable components`.

**Comment by M-Shorouk** [comment]
@ljupcovangelski True.. 

1. For this feature we wanted to implement a quick solution for both enterprise components and how we could refer to other components in development or as you call them "Unstable" components. As a result, we are for now using request access for both components. 


2. Adding components which are still in development or even planned on our Catalog, as "Coming Soon"/ "Request Access" for now, would help us gather frequent interest from our users and prioritise our component developing plan as per highest component "Request". It would also show that our product is aware of the commonly used "components" in the market. 

3. In the next release we are adding filters to Firstly, Catalog View, and rest of views comes after. Once we start adding a filter component on Connectors view, it would be time for us already to separate the request access feature to "Request Access > for Enterprise" & " Coming soon tag > for " In Development" components.

**Comment by ljupcovangelski** [comment]
Got it :+1: 

Then I think this covers the use-case for enterprise components for which the user doesn't yet have access.

I have few questions:
- What is considered by `successful request`?
- Where should be the `Requested` information be stored?
- What if request is granted, how will the user proceed to install the component? Will he then be able to see an `Install` button?

If that is the desired flow, then we should consider information which uniquely identify the Airy instance in the form that the user submits. Also I think this is as well a backend ticket, since the install/uninstall endpoints currently don't handle any `Request/grant access` requests/replies.
