### ISSUE TITLE
Restructure backend directories

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#3671]
## Is your feature request related to a problem? Please describe.

The current directory structure is a bit arbitrary and it feels pointless to keep moving directories around whenever we change our understanding of component categories.

## Describe the solution you'd like

We, therefore, want to implement this restructuring:

Current:
```
.
└── backend/
    ├── api/
    │   ├── admin
    │   ├── communication
    │   └── ...
    ├── avro
    ├── model
    ├── connectors/
    │   └── rasa
    └── sources/
        ├── api
        ├── facebook
        └── ...
```
New
```
.
└── backend/
    ├── components/
    │   ├── {whatever the component name is}
    │   ├── api-admin
    │   ├── api-communication
    │   ├── rasa
    │   ├── media-resolver
    │   ├── sources-facebook
    │   └── ...
    ├── avro
    └── model
```

**Comment by ljupcovangelski** [comment]
Great initiative and it is good to go now like this. If we have in the future components that have both frontend and backend part (now it is just the sources-chatplugin I think), we can have a structure similar to this:

```
.
└── components/
    ├── api-admin/
    │   ├── backend/
    ├── chatplugin-connector/
    │   ├── backend/
    │   ├── frontend/
    ├── dialogflow-connector/
    │   ├── backend/
    ├── control-center
    │   ├── frontend/
    ├── avro
    └── model
```

But for now, I agree with the proposed directory structure :+1: .
