### ISSUE TITLE
Status view not showing "Not Configured" component 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3715]
## Describe the bug

After Installing Dialogflow o from control center and before configuring the connector, one can't find the component on Status view as an Installed component but Not Configured.

## To Reproduce

1. I installed Dialogflow from Catalog view
2. I opened Status view to find Dialogflow component as not configured. 
3. I kept refreshing the status view.
3. See error when Dialogflow component doesn't appear. 

## Expected behavior
Dialogflow component should appear on Status view with "Not configured" status to give the user indication that this component missing configuration to run. 

+Adding > "Not configured" components don't have "Enable" button visible on Status view since it still needs configuration. 

## Environment

- Browser: [Chrome]
- Version: [0.50.0-alpha]

**Comment by ljupcovangelski** [comment]
@M-Shorouk one suggestion, perhaps we shouldn't allow `Enable` for components that are not configured (and are marked that require configuration in order to run). That way we enforce our desired flow: Install -> Configure (if required) -> Enable.

**Comment by M-Shorouk** [comment]
@ljupcovangelski yes as far as i remember the design flow was covering this sequence; just allowing Disable button when the component is actually Enabled... Otherwise, the component is shown there since its is "Installed" and shows "Not Configured" status.

**Comment by ljupcovangelski** [comment]
> @ljupcovangelski yes as far as i remember the design flow was covering this sequence; just allowing Disable button when the component is actually Enabled... Otherwise, the component is shown there since its is "Installed" and shows "Not Configured" status.

Ok, I'm just pointing out that "Checking whether the component can be enabled or not" is not something that we are doing at the moment.

**Comment by M-Shorouk** [comment]
@ljupcovangelski ah i thought it was done here [3361](https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3361).. 

Also if it is not working for some reason, we can consider this current bug with this ticket [3357](https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3357)

**Comment by ljupcovangelski** [comment]
> [3357](https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3357)

This is a separate issue I think and yes :+1: a very important one!

For enabling a non-configured component, you can try creating a new instance on the latest version (or use an existing instance). Install any source or some component that requires configuration. You are redirected to the Configuration screen after installation, but if you skip the Configuration part - you can still enable the component from the `Status` page.

**Comment by M-Shorouk** [comment]
Solved in v.53.0
