### ISSUE TITLE
Updating all "Source Connector" in Repo 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3719]
## Is your feature request related to a problem? Please describe.

Updating all Source Connectors details information on github repo . 

## Describe the solution you'd like

On `/components.list` doc we can update from SLIDE 5 TO SLIDE 12. 

## Additional context

docs reference: https://docs.google.com/presentation/d/1ecTHtSDABuoKZMDhSw5GWycXFKt7VRMnu5jlzOtfnQQ/edit#slide=id.g14827cc91a0_0_12

**Comment by chrismatix** [comment]
Closing this as the information is no longer in dynamodb

**Comment by AitorAlgorta** [comment]
where did it go then? @chrismatix
