### ISSUE TITLE
Catalog card arrangement 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3723]
## Describe the bug

Components that are ready to be installed comes as second priority after "Coming Soon" components. 

## To Reproduce

1. Open Control Center and click on Catalog. 
2. See error that "Coming soon" components appear in sequence before other available components for install.

## Expected behavior

Always showing components ready to Install first. 

## Screenshots

![Screenshot 2022-09-14 at 18.09.22.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/77695dc0-cafd-49cd-ad17-631e2a1bed26)

## Environment

- Browser: [Chrome]
- Version: [Version 0.50.0-alpha]

**Comment by thorstenairy** [comment]
@M-Shorouk 
we have "COMING SOON", "OPEN" and "INSTALL"

OPEN -> INSTALL -> COMING SOON would be my suggested order, what you think?
