### ISSUE TITLE
Airy chat plugin component not showing on Status view 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3728]
## Describe the bug

Airy chat plugin doesn't appear on Status view after Installation even after refreshing the Status list.  

## To Reproduce

1. I installed Airy chat plugin from Catalog view on Control Center. 
2. After successful installation, you can view Airy chat connector on Connector view as Enabled.
3. See error when you check Status view where you can't see Airy chat plugin component on the list. 

## Expected behavior

Airy chat plugin as a component should appear  on Status view since it has been successfully installed. 

## Screenshots

![Screenshot 2022-09-15 at 12.49.10.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/41f1094f-c8a0-4dfe-8f33-2948c00bb028)

## Environment

- Browser: [Chrome]
- Version: [Version 0.50.0-alpha]

**Comment by thorstenairy** [comment]
@M-Shorouk it is displayed as "sources-chatplugin"

**Comment by M-Shorouk** [comment]
@thorstenairy ah saw it, sorry my mistake 👽
