### ISSUE TITLE
Connectors Configuration form on Control Center 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3744]
## Is your feature request related to a problem? Please describe.

As an Airy user, i should be able to always change connector's configuration after enabling the connector. Currently on Control Center, the Connector details card on Connectors view doesn't contain a configuration view to update after one configures the connector. 

This configuration view is currently only maintained on "Other Connectors" card details view. e.g: Dialogflow/Salesforce, but for other source connectors, such as "Instagram/Whatsapp", we don't have this view. 

## Describe the solution you'd like

Add a tab view on Connectors card details to save the connector's configuration as well as allowing Airy user to update these configuration variables. 

Source connector Configuration values: 

1. Whatsapp : { "appId", "appSecret", "webhookSecret"}'
2. Viber: '{ "authToken": "string"}'
3. Twilio : { "authToken":, "accountSid"}'
4. Google Business messages: '{ "saFile", "partnerKey"}
5. Facebook : { "appId", "appSecret", "webhookSecret"}'

**Comment by Edoardo333** [comment]
FIGMA LINK: 

https://www.figma.com/file/fqxGvk4E3dWbmWoJKlVjYU/Control-Center-10?node-id=959%3A1207

**Comment by AitorAlgorta** [comment]
Reopening to build the popup to add channel @thorstenairy
