### ISSUE TITLE
Connectors in Redux store proposal

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#3775]
We are planning to restructure the redux store for connectors as we have to access different data states to get all necessary values to e.g. display a connector card correctly.

We are getting all values from `components.list`, `components.get` and `client.config`.
For the frontend are the most important ones:

- enabled from `client.config`
- healthy from `client.config`
- installed from `components.list`
- configured from `components.get`

Right now we store the responses as followed: 
-  `client.config` in data.config.components
- `components.list` in data.catalog
- `components.get` in data.connector

which means to get all needed values we need to access three different data states.

Current structure:
<img width="696" alt="Screenshot 2022-09-26 at 17 13 24" src="https://user-images.githubusercontent.com/49147864/192314441-67995937-c290-4358-b3ce-297e45790cbe.png">

<img width="744" alt="Screenshot 2022-09-26 at 17 09 50" src="https://user-images.githubusercontent.com/49147864/192315593-2d41abd1-0829-4fe4-b3ee-e05ff21a21ce.png">
<img width="856" alt="Screenshot 2022-09-26 at 17 10 11" src="https://user-images.githubusercontent.com/49147864/192315600-b69b29ee-2817-449a-95d8-f61f647ffb24.png">
<img width="855" alt="Screenshot 2022-09-26 at 17 10 36" src="https://user-images.githubusercontent.com/49147864/192315610-3a85435a-77b7-4e1f-8a93-0045d75f432b.png">

To keep the future of the frontend team easier and more efficient I would love to feed the connector data state with all necessary values so we just access connectors to get needed values.

e.g. suggested structure:
![Screenshot 2022-09-07 at 16 02 18](https://user-images.githubusercontent.com/49147864/192316102-e3df2263-149f-48fd-86dc-0432c8a58930.png)

This suggestion misses the "installed" value as we discussed to remove the repository name from the response of `components.list` so we are more aligned with `components.get` and `client.config`.

Please feel free to add all your thoughts and suggestions 🙏

**Comment by chrismatix** [comment]
Hey @thorstenairy thanks for identifying and summarising the issue for us 🚀 

> To keep the future of the frontend team easier and more efficient I would love to feed the connector data state with all necessary values so we just access connectors to get needed values.

By this, you mean merging all action payloads from the other API calls into the `connector data state`, right?

This works for me, but I was wondering what you think about using redux selectors to create aggregate views the same way that we already do for conversations?

**Comment by thorstenairy** [comment]
@chrismatix yes, exactly.
tbh, I like the redux selectors approach, totally forgot about that.
What you think about that @AudreyKj?

**Comment by AudreyKj** [comment]
yes, I agree 👍 

we're already using redux selectors in the Control Center to get components and connectors by source, so this is in line with our current approach

**Comment by chrismatix** [comment]
@thorstenairy in which PR was this completed? :)
