### ISSUE TITLE
Status View - Wrong "Needs Configuration" icon 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3805]
## Describe the bug

On Control center, Status View, a component is in "Not Healthy" status and its enabled functionality refers to "Needs Configuration". 

## To Reproduce

1. login on Control Center 
2. View on Status view " enterprise-salesforce-contacts-ingestion" component 
3. See error of having a dependent service, in Not healthy status, and the enabled functionality refers to "Not Configured" 

## Expected behavior

- When "enterprise-salesforce-contacts-ingestion" component shows a dependent service, it means that this component has been previously configured in order to be able to connect to services/connectors. 

- The "Not Configured" reference is wrongly places, it should contain and enable/disable button. 
- ANOTHER EXPECTED BEHAVIOUR : if the component needs configuration, the component's status should be = " Disabled". 

- Clicking on "Not Configured" you will notice that the component has lost its configuration's values. 

## Screenshots

FIG.1. : 
![Screenshot 2022-10-07 at 15.48.20.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/233600d0-ff62-4946-9fb6-e62571124119)
## Environment

- Browser: [e.g. Chrome]
- Version: [Version 0.50.0]

## Additional context

Same for the following components: 

1. sources-google 
2. sources-twilio 
3. sources-viber

![Screenshot 2022-10-12 at 15.22.35.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/92f8e638-a553-4275-8ec2-60dd1821ea1f)

**Comment by AudreyKj** [comment]
We are closing this ticket, as this has already been solved. Find below a screenshot of the latest staging:

<img width="1440" alt="Screenshot 2022-10-17 at 10 52 09" src="https://user-images.githubusercontent.com/38159391/196133768-9e2af197-52a7-44cc-8701-6cd57a4f416e.png">
