### ISSUE TITLE
IBM Watson Assistant 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3819]
## This is how we could improve the [documentation](https://docs.airy.co):

This docs ticket is focused on Scoping "IBM Watson Assistant" as a voice Integration to Airy.

**Comment by AudreyKj** [comment]
IBM Watson Assistant is an easy to use conversational AI platform  that supports both text and voice. IBM Watson can be integrated on webchats and phone to improve customer support.

Watson Assistant Docs Ressources
https://www.ibm.com/uk-en/products/watson-assistant/docs-resources

Chatbot Demo page
https://www.ibm.com/products/watson-assistant/demos/lendyr/demo.html?section=essentials&panel=ask-clarifying-questions

Preparing to install Watson Assistant for Voice Interaction
https://www.ibm.com/docs/en/cloud-paks/cp-data/3.5.0?topic=interaction-preparing-install-watson-assistant-voice
