### ISSUE TITLE
Meta Connector Solution discussion  

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3860]
## Is your feature request related to a problem? Please describe.

As currently Meta Connector's configuration enables Facebook, Instagram, Whatsapp [channel_type] all together, we need to discuss the possible solution for reflecting this setup on our Control Center UI. 

## Describe the solution you'd like

To successfully Install Meta Connector, you need to configure the Meta Connector first and then the 3 { Meta Facebook Messenger, Meta Instagram, Meta whatsapp} [channel-types] are set for configuration.  

**[DISSCUSSION]**

**1. FIRST SOLUTION**

 _[Component : Connector is 1:1]_

Separating [channel_types]  as own components , { Meta Facebook Messenger, Meta Instagram, Meta whatsapp} since each channel_type needs its own configuration. 

In this solution, for a successful install, Airy user will need to Configure Meta Connector for the first time when installing any of the [channel_type] as a component. This would only happens once. 

Technical drawbacks: 

1. We have to package each [channel-type] as a component separately which will create redundancy of Meta connector code. 

**2. SECOND SOLUTION** 

_[Component : Connectors is 1:M]_

Creating one Meta Component which contains 3 separate, view wise,  Connectors { Meta Facebook Messenger, Meta Instagram, Meta whatsapp}. In this solution, it is suggested to treat [channel_types] as connectors of Meta Component since each [channel_type] requires different configuration after Meta Connector Installation.  

In this solution, Airy user configures Meta Connector once when Installing and can configure [channel-types] separately after successful installation. 

Technical drawbacks: 
_[Please list]_
1. 

## Additional context

NOTE: We should keep in mind a solution that would apply to Twilio & Salesforce as well.

**Comment by ljupcovangelski** [comment]
Couple of comments about the description:

> **1. FIRST SOLUTION**
> ...
> In this solution, for a successful install, Airy user will need to Configure Meta Connector for the first time when installing any of the [channel_type] as a component. This would only happens once.

I think that in this case, the components will be installed and configured separately and independently. There will not be a need to `Configure Meta Connector for the first time`. This connector (Meta) will not exist as such I think.
In the `Connectors` view, there will be three separate connectors in this case. Also in `Catalog` and `Status`.

> **2. SECOND SOLUTION**
> ...
> Creating one Meta Component which contains 3 separate, view wise, Connectors { Meta Facebook Messenger, Meta Instagram, Meta whatsapp}. In this solution, it is suggested to treat [channel_types] as connectors of Meta Component since each [channel_type] requires different configuration after Meta Connector Installation.

According to the current design, we will create **one component** with **one connector** (we have a 1-to-1 mapping between connector and component). Then when we need to `connect` a channel, we would need to select a channel type.
In the `Connectors` view, there will be one connector in this case. Also in `Catalog` and `Status`.

A separate discussion is whether to decouple `Connector` from `Component`. I wouldn't mix it here, to avoid any confusions.

**Comment by M-Shorouk** [comment]
Discussion closed and opened [THIS](https://app.zenhub.com/workspaces/airy-61f94fc6acedfd001f39b1d0/issues/airyhq/airy/3902) ticket.
