### ISSUE TITLE
Airy Chat plugin connector view error 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3866]
## Describe the bug

1. When installing "Airy Chat Plugin" Component from Catalog view, exiting the pop-up and navigating to "Connectors".  Connectors card details has error that it contains enabled channels from old configuration. 

2. Connector status is in wrong state; Airy chat plugin is instantly enabled after Installation as it needs no configuration. 

## To Reproduce

1. I installed Airy chatplugin from Catalog. 
2. Navigate to Connectors view, find Airy chat plugin and click on Card details. 
3. See error with the "Disabled" status and already added channels on the channel list view, 

## Expected behavior

Airy chat plugin connector should have been enabled as it needs no configuration and the first connector card details should be the form off adding a channel to Airy plugin NOT already existing enabled channels. 

When a user installs a component for the first time, one can't see old connected channels. 

## Screenshots

FIG1. HOW CONNECTOR CARD LOOKS LIKE; DISABLED CONNECTOR WITH 204 CONNECTED CHANNELS 
![Screenshot 2022-10-21 at 12.52.47.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/095af964-f614-4f9d-91fe-dad6e01dbdcd)

FIG2. HOW CONNECTORS CARD DETAILS LOOK LIKE; OLD CHANNELS WHICH ARE ALREADY ENABLED
![Screenshot 2022-10-21 at 12.43.25.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/f9965d0d-8f74-4389-a50e-3a1aeb60dcb8)

## Environment

- Browser: [Chrome]
- Version: [Version 0.51.0-alpha]

**Comment by AudreyKj** [comment]
@M-Shorouk this is not a frontend issue, but rather an infrastructure/backend issue, as configurations are not wiped out when a user uninstalls a component.

**Comment by M-Shorouk** [comment]
NO LONGER THE CASE IN NEW RELEASE

**Comment by M-Shorouk** [comment]
NO LONGER THE CASE IN NEW RELEASE
