### ISSUE TITLE
javascript hot code reloading not working in demo app

### ISSUE THREAD

**Issue by bitboxer** [airyhq/airy#387]
The hot code reloading does not work if:

* code outside of the ui frontend part, e.g. the libraries, is changed
* scss is changed
* files are added to the ui frontend

**Comment by chrismatix** [comment]
Todo:
- [ ] Serve dev bundle without bazel
- [ ] Integrate the [react hot loader](https://github.com/gaearon/react-hot-loader)
- [ ] Make process a Bazel binary to remove node dependency
- [ ] document and clean up
