### ISSUE TITLE
Adding Spinner loader on some screens 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3878]
## Is your feature request related to a problem? Please describe.

As an Airy user, i need to see an indication that my action is being carried out on Control Center UI. 

## Describe the solution you'd like

Adding a spinner loader to reflect that the following actions are being carried out: 

CATALOG VIEW 

1. Installing a component from rich card.
2. Installing a component from Component card details. 
3. Uninstalling a component from Component card details. 

BUTTON CONTENT: 

Removing the spinner added to the Install/Uninstall button and replacing the spinner with relative status reference: 

1. When user clicks "Install" the button has "Installing" context instead of the spinner. 
2. When user clicks "Uninstall" the button has "Uninstalling" context instead of the spinner. 

CONNECTORS VIEW
1. Adding a channel inside a source connector card details. e.g: Facebook Messenger, Instagram. 
2. Creating a channel inside a source connector card details. e.g: Facebook Messenger, Instagram. 
2. Updating connector configuration from connector card details view.

**Comment by Edoardo333** [comment]
FIGMA LINK 

https://www.figma.com/file/x0gSik73ZGl8bDmK1OYAVp/Control-Center-11?node-id=1203%3A4927

**Comment by AitorAlgorta** [comment]
will move this to In Progress and assign @thorstenairy to it. We will try to make it work with the current design, if it's not good we will need a lottie animation @M-Shorouk @Edoardo333
