### ISSUE TITLE
Enhancing "Install" phase - onboarding on Control Center

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3935]
## Is your feature request related to a problem? Please describe.

In this ticket, we are focused to enhancing the onboarding experience of Airy user on Control center. Mainly the experince is focused on "Catalog View" where Airy user learns and Installs components. 

As well as "Connectors details card" on "Connectors View" where user firstly arrives to configure an installed component. 
 
## Describe the solution you'd like

{Design is in progress}

## Describe alternatives you've considered

Here is a list of the small changes add to "Catalog view": 

1. Create a segmented navigated tab that contains the following: 
  1.1. "ALL" : A view to show ALL Components on Airy (Installed, Coming Soon, and already installed)
  1.2. "Installed" : A view to filter ONLY installed components. 
  1.3. "Coming soon" : A view to filter components which are in development. 
  1.4.  "Installed" : A view to filter all installed Components. 

2. Adjust component name size on Cards. 
3. Add "Read more" reference in the card description to allow user to know that there are more info to read per component. 
4. Adding toolkit to "Search" icon. 
5. Adding a Catalog view description with reference to Catalog docs.

**Comment by Edoardo333** [comment]
FIGMA LINK: 

https://www.figma.com/file/gO41Hgf8zeP5L9idrFJtlC/Oboarding-User-Experience-Improvements?node-id=0%3A1&t=XzQYTqY883ecTHHZ-0

**Comment by AitorAlgorta** [comment]
what about this? will we finish this? @thorstenairy
