### ISSUE TITLE
Broken links in documentation (README.md)

### ISSUE THREAD

**Issue by ogbeche77** [airyhq/airy#394]
Hello everyone, I am trying to get myself familiar with the project and observed two links in [README.md](https://github.com/airyhq/airy) are broken.
They are both links to API and contributing guidelines.

- An [API](https://github.com/airyhq/airy/blob/develop/docs/docs/api.md) to manage the data sets the platform
  handles.

- Our [contributing guidelines](https://github.com/airyhq/airy/blob/develop/docs/guidelines/contributing.md)

**Comment by ogbeche77** [comment]
Can I go ahead to fix it to get a better understanding of the practice?

**Comment by AitorAlgorta** [comment]
Yes, of course. Go for it
