### ISSUE TITLE
Error on Status view for "Disable" button 

### ISSUE THREAD

**Issue by M-Shorouk** [airyhq/airy#3969]
## Describe the bug

On Control Center, on "Status" view, some components are "Disabled" and their health status is "Green" which is Healthy.

## To Reproduce

1. Signin on Airy Control Center 
2. Notice some components their disable button is on and their health status is "Green"  

## Expected behavior

When a component is "Disabled" the component status and relative dependent services are "Grey" referring to the component status = "Disabled". 

Notice in the screenshot below the following components: 
1. Cognigy
2. Rasa
3. Zendesk
4. IBM Watson 

## Screenshots

![Screenshot 2022-11-25 at 10.24.52.png](https://images.zenhubusercontent.com/61d6c337ede24c2a3fdfa338/bb656b7e-adcc-4c8f-9d9a-71bbbdf8d246)

## Environment

- Browser: [Chrome]
- Version: [Staging: Version 0.53.0-alpha]

**Comment by thorstenairy** [comment]
@M-Shorouk can you double check this?
for me everything works as expected

**Comment by M-Shorouk** [comment]
@thorstenairy yes we check it and am closing this ticket.
