### ISSUE TITLE
Filter conversations

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#403]
Create the UI to filter conversations

**Comment by chrismatix** [comment]
This library can be used to construct lucene queries: https://www.npmjs.com/package/lucene-query-string-builder

This file contains the fields that a conversation can be filtered on: https://github.com/airyhq/airy/blob/2b0dda91b411913457cfc3b3b68bc133f4903bb5/backend/api/communication/src/main/java/co/airy/core/api/communication/dto/ConversationIndex.java
