### ISSUE TITLE
Introduce /client.config

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#421]
In the context of this issue, we introduce a new endpoint meant to be consumed by clients:

Example response:

```json5
{
  "components": [
    {"sources.chat_plugin": {"enabled": true}}, // the data model will evolve. For now we can get away with booleans
  ],

  "endpoints": {
     "conversations_list": "/conversations.list" // this way we allow to dynamically change the endpoint of a feature and hook into its behavior while keeping it transparent for the UI
  }
}
```

**Comment by bitboxer** [comment]
Would also be nice if this api returns the `FacebookAppId` that is configured in the `airy.conf`. That way the person installing it only has to configure it in one place.
