### ISSUE TITLE
Introduce metadata stats 

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#422]
Since we are displaying the tags counter in the tagspage, so you can see how often a specific tag is used on conversations. that's one example of the use case.

We should probably provide a generic api for this so that the UI can use it for "counting" many things. for example, the api should be high level enough that you can use it for `unread_count` and for tags usage.

**Comment by lucapette** [comment]
As discussed offline, we should probably put this one on hold as the specific requirement is expensive to build (and the resulting feature doesn't justify it). We'll come up with a more generic solution so for now I'll add the "needs discussion" label and leave it open so we can get back to it as soon as it's a little clearer to us how we want to proceed.
