### ISSUE TITLE
Add media content models

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#496]
We need to expand the content model in `lib/java/mapping` to also include `image`, `video`, `audio`, and `file` messages.

- [ ] Add a generic content model for `video`, `image`, `file` and `audio` each
- [ ] Map all media for Facebook
- [ ] Map all media for Twilio
- [ ] Map all media for Google

**Comment by paulodiniz** [comment]
Media models that are there already

- Image for Twilio #532 
- Image for Google #531 
- Image for Facebook #539 

Since those are already in place, we can start on #497
