### ISSUE TITLE
Introduce eslint

### ISSUE THREAD

**Issue by lucapette** [airyhq/airy#515]
As discussed offline, I played around with `eslint` as we're all happy to introduce it here.

The following configuration: 

```
module.exports = {
    "env": {
        "browser": true,
        "es2021": true,
        "node": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:react/recommended",
        "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaFeatures": {
            "jsx": true
        },
        "ecmaVersion": 12,
        "sourceType": "module"
    },
    "plugins": [
        "react",
        "@typescript-eslint"
    ],
    "rules": {
       "@typescript-eslint/no-unused-vars": ["error", {"varsIgnorePattern": "_" }]
    },
      "settings": {
        "react": {
          "version": "16.12"
        }
    },
  "overrides": [
    {
      "files": [ "frontend/chat-plugin/**/*.tsx" ],
      "settings": {
        "react": {
          "pragma": "h"
        }
    }
    }
  ]
};
```

Solves the two most noisy problems: we need `_` for bazel/typescript to play nice and the `overrides` to avoid confusing eslint about the chat plugin (it uses preact).

You can see the remaining errors [here](https://gist.github.com/lucapette/ed83bfe2a4b1f20fd1bc6995569f3de5)

The most present error `warning  Missing return type on function           @typescript-eslint/explicit-module-boundary-types` seems to be React specific and maybe we can get away with configuration only. And I'm a bit unsure what's the best way to fix `warning  Unexpected any. Specify a different type          @typescript-eslint/no-explicit-any` because we use `Dispatch<any>` in quite a few places.

**Comment by lucapette** [comment]
Reference branch: https://github.com/airyhq/airy/compare/chore/eslint?expand=1

**Comment by bitboxer** [comment]
Maybe we should change the places that use `Dispatch<any>`?
