### ISSUE TITLE
Sync versions of core with the versions of the helm charts

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#542]
> I think this version that we have inside the charts is not used anywhere. The thing is that Helm requires us to have a version in the file describing the charts (example https://github.com/airyhq/airy/blob/develop/infrastructure/helm-chart/charts/apps/charts/api/Chart.yaml#L5).

**Todo**
Template the `VERSION` file into the charts either during the build process or with an automated command.

**Comment by chrismatix** [comment]
Is this resolved now that we are packaging the helm charts in the helm job image? https://github.com/airyhq/airy/compare/feature/1014-deploy-the-helm-charts

**Comment by ljupcovangelski** [comment]
I think this version that we have inside the charts is not used anywhere. The thing is that `Helm` requires us to have a version in the file describing the charts (example https://github.com/airyhq/airy/blob/develop/infrastructure/helm-chart/charts/apps/charts/api/Chart.yaml#L5).
As we will package the charts in the helm image - it is true that we are making sure that we are using always the correct version.
I think a good approach would be if we generate this during the release process. We can also put some generic version in all the charts and close this issue, as this version is not used anywhere.

**Comment by chrismatix** [comment]
I think now I get it better. I would move this out of the milestone though since to me this is related to upgrading running core installations (which is out of scope)

I am removing the "needs discussion" label, updating the description and removing the issue from the milestone.

**Comment by ljupcovangelski** [comment]
We set the version of the helm charts on release time and have a generic version `0-develop` in the repo.
