### ISSUE TITLE
Push go images from Mac

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#545]
Currently only Linux can be used to do build and push `go` images to `Github Packages`, for example with
```
bazel run //backend/webhook/redis-worker:beta
```

We should fix bazel, so that when the command is run on Mac it also uses the Linux toolchains. Then pushing should also work from Mac.

**Comment by lucapette** [comment]
`--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64` should fix the problem in case we need to push the image manually
