### ISSUE TITLE
Change /channels.connect to source specific connect

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#550]
In the demo app currently we use the old endpoint `/channels.connect` but #223 changed the api to source specific endpoints

i.e: We need to check the source type and dispatch it to either

- `/facebook.connect`
- `/google.connect`
- `/twilio.sms.connect`
- `/twilio.whatsapp.connect`

Also we need to change `/channels.explore` to `/facebook.explore`

**Comment by lucapette** [comment]
this was done in #541
