### ISSUE TITLE
Simplify senderType

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#572]
As it's a binary information at first (either the contact sent a message or they didn't), we should reflect this in the data model.

the nuanced data points (which are mostly source specific) should travel through the system via the headers or the metadata

**Comment by lucapette** [comment]
Definitely agree with this. I think the current approach is not in line with the spirit of the core design as it's trying to generalize data from sources. The approach:

- sender_type = 'contact' | 'source'
- any additional information goes into the headers (I believe it's a better place than metadata after giving this some though)

seems more inline with how we're doing this with sources now. Would love to hear more opinions on this

**Comment by chrismatix** [comment]
Agreed. I would suggest that if this information is binary the best distinction we can make is a boolean `isFromAiry`. This is because if we use `isFromContact` we would consider messages that are sent from "source users" (third party apps, the user writing on the facebook inbox etc.) our messages. But perhaps that's what you meant with `sender_type = 'contact' | 'source'
` @lucapette

**Comment by chrismatix** [comment]
Implication: We have to deliver the headers to the client with message payloads and clients need to look up the headers to know whether or not to render a message `left` or `right`

**Comment by lucapette** [comment]
no what I meant to say is the binary information is the contact wrote in the conversation or didn't. `isFromAiry` confuses me.

that should also cover the alignment without having to look into the headers. What am I missing?

**Comment by chrismatix** [comment]
Apologies for the late reply. For all intents and purposes `isFormContact` should suffice. And we add a distinction between `fromAiry` and `fromSourceUser` as a header field 👍

**Comment by lucapette** [comment]
no need to apoligize! It's all async :) I will remove the the label now
