### ISSUE TITLE
Investigate TypeScript httpclient public API

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#591]

**Comment by AudreyKj** [comment]
Research investigation work regarding Core's Http Client Library. 

Goal & Outcome: -> finding inspiration on how we could improve the library's v1, especially regarding its compatibility 

Focus: -> how others companies are releasing public apis 

topics investigated: 
- which naming is used 
- how compatibility is handled (browser / node.js)
- how the lib is structured 
- testing 
- documentation
