### ISSUE TITLE
Rename Demo to UI

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#605]
We will use this issue to also introduce docs for the UI and the Chat Plugin

**Comment by lucapette** [comment]
We introduce a new section in menu (see the google doc attached in #731 for specs)

**Comment by sgarroum** [comment]
This would be the prefect moment to also start doing short gifs/images for the docs to document & visualize the current state.

UI: 
Screenshot: Inbox with multiple conversations & 1 Conversation selected and open
GIF: Inbox, open one conversation, switch to another

Chatplugin:
Screenshot: Chat Plugin on an empty test page, no noisy background, best case only airy light blue as background
GIF: Same as above, type something in the chatplugin, something gets send back
