### ISSUE TITLE
make library compatible with node.js and the browser 

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#628]
**Current state:** 
- the library is only compatible with the browser

**To do:** 
- make library compatible with both node + browser 
- change api request config to make it compatible (fetch vs axios vs superagent to be discussed)
- add appropriate bundling (Webpack)

**Comment by lucapette** [comment]
https://github.com/node-fetch/node-fetch seems to be the closest to how I'd personally solve the problem (but no strong opinion about it)
