### ISSUE TITLE
decide on naming of the library 

### ISSUE THREAD

**Issue by AudreyKj** [airyhq/airy#636]

**Comment by AitorAlgorta** [comment]
what do you think about `@airyhq/httpclient`? @airyhq/codeowners-backend @airyhq/codeowners-frontend

**Comment by AudreyKj** [comment]
yeah I think this naming makes sense, it's also coherent with the components package's naming (@airyhq/components)

**Comment by paulodiniz** [comment]
I agree! We already call it by that and it's descriptive 👍

**Comment by lucapette** [comment]
good name. I think this issue per se can be closed (feel free to reopen if I'm wrong) as we can incorporate it in the npm task
