### ISSUE TITLE
PostgreSQL settings in configuration files not working properly

### ISSUE THREAD

**Issue by ljupcovangelski** [airyhq/airy#639]
When settings for PostgreSQL are added in the configuration file (for example the password) the PostgreSQL server is generated with some initial settings, so the `api-auth` app ends in a broken state.

The requirement is:
- if the settings for postgres are there in the config file before running `scripts/bootstrap.sh`, then the internal PostgreSQL is created with the desired password, from the config file.
- if the settings are added afterwards and the configuration is updated, then we need to update the password in the configMap, but also make sure that the same password is used by PostgreSQL.

**Comment by pascal-airy** [comment]
If I get it right the only use case where this problem occurs is when you do the bootstrap with a password in the config file and then apply the config again with a different password. In which case you could still rerun the bootstrap. Which I think is a manageable workaround for the foreseeable future. Or am I missing something?

**Comment by ljupcovangelski** [comment]
Yes you are correct. But I think we better remove the postgres `password` from the config file and generate one with helm. Then the problem is gone and also we force a certain password policy.

**Comment by pascal-airy** [comment]
Agreed we need to remove it from [here](https://github.com/airyhq/airy/blob/develop/infrastructure/helm-chart/charts/prerequisites/values.yaml#L11)
but we need it in the config file for when people bring their own postgres and want to feed it to the apps

**Comment by ljupcovangelski** [comment]
True. Then we can make a condition, if then parameter is not there - generate a random one.

**Comment by ljupcovangelski** [comment]
But then, if it is present in the configuration, it becomes tricky. Because if you change it or add it later, we get the same problem - we should somehow re-provision the PostgreSQL instance.

Maybe this should not affect the installed PostgreSQL: If we deploy PostgreSQL inside the helm chart - then the password is always random. If not - put your own password. 

Perhaps for the whole `Prerequisites` section we can do something like: If there is configuration present there, then don't create those things inside the Kubernetes cluster. If that block is not present - we generate the default values for kafka, redis, posgresql. But then this concept doesn't work:

```
cp infrastructure/airy.tpl.yaml infrastructure/airy.yaml
./scripts/bootstrap.sh
```

**Comment by lucapette** [comment]
as we're in the process of eliminating postgres from the infrastructure, I will close this one
