### ISSUE TITLE
Enable users to connect via WhatsApp/SMS

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#656]
### Summary
To enhance overall experience, we should offer the ability to connect SMS and WhatsApp channels after the Twilio requirements have been met.

### Twilio Requirement

On Airy Core, it should be an option to connect a number for WhatsApp or SMS messaging. Before this is possible, adding a Twilio Auth Token should be required. Before the Twilio Auth Token is povided and a phone number is purchased, we should inform system users that they cannot connect WhatsApp or SMS channels without these requirements.

![104598079-6d9bf880-5676-11eb-9ad9-f25cc8d232d7](https://user-images.githubusercontent.com/74183162/106778821-a829fd00-6646-11eb-8ce1-737808e35678.png)

**Note**: in relation to the image above, we cannot direct system users to `airy.conf`. Therefore, we should initially direct system users to the correct [documentation](https://github.com/airyhq/airy/blob/develop/docs/docs/api/endpoints/channels.md).

### SMS 
Once a phone number is bought via Twilio, it should be possible to connect that number for SMS messaging. In this instance, it should also be possible to enter an icon and name to differentiate between channels from an Admin aspect.
![2 1 0 Connect SMS@2x](https://user-images.githubusercontent.com/74183162/104598084-712f7f80-5676-11eb-80c0-bbda1bdaa01d.png)
It should be possible for several phone numbers to be added within the SMS channel, and these numbers will all be visibly listed.
![2 2 0 Connect SMS@2x](https://user-images.githubusercontent.com/74183162/104598085-71c81600-5676-11eb-9a9a-404b6054121b.png)
It should be an option to be able to edit the information (phone number, icon, and name) given for each phone number listed within the channel.
![2 2 1 Connect SMS Edit@2x](https://user-images.githubusercontent.com/74183162/104598086-7260ac80-5676-11eb-82aa-7b4b7e9592dd.png)

### WhatsApp
Once a phone number is bought via Twilio, it should be possible to connect that number for WhatsApp messaging. In this instance, it should also be possible to enter an icon and name to differentiate between channels from an Admin aspect.
![4 0 0 Connect Whatsapp@2x](https://user-images.githubusercontent.com/74183162/104598087-72f94300-5676-11eb-96a1-7cfa39c072ac.png)
It should be possible for several phone numbers to be added within the WhatsApp channel. It should also be possible for the same phone number to be used for more than one location, if desired.
![4 1 0 Connect WhatsApp@2x](https://user-images.githubusercontent.com/74183162/104598091-7391d980-5676-11eb-8b42-510a5fafb1a4.png)

**Comment by lucapette** [comment]
depends on #421

**Comment by lizhutter** [comment]
related to #665
