### ISSUE TITLE
Type errors not caught by Typescript

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#685]
**Current state**
@bitboxer has discovered that VSCode catches type errors that are not present on IntelliJ or on our builds.

For instance currently on develop (e6b866017bbdf30641a905b80ed2dd0c8734a336) in `frontend/demo/src/pages/tags/Tag.tsx` the `connect` method accepts a `tagSettings` that is different from the prop types leading to this error that only shows up in VSCode

```
Argument of type '({ tag, expanded, variant, onClick, removeTagFromContact, tagSettings, }: TagProps & tagState) => JSX.Element' is not assignable to parameter of type 'ComponentType<Matching<{ tagSettings: Settings; } & DispatchProp<AnyAction>, TagProps & tagState>>'.
```

**Desired state**
Our typescript builds catch all redux typing errors

**Comment by bitboxer** [comment]
I added a first step, but the second step would mean updating the `redux-starterkit` to `@reduxjs/toolkit`. Sadly it was not possible for me due to an weird error while compiling the code. @chrismatix and I will have to revisit it soon.
