### ISSUE TITLE
Consistency between first_name, last_name and display_name

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#693]
We need consistency between `first_name`, `last_name` and `display_name` because we are getting `first_name` and `last_name` from the endpoints, but we are using `display_name` for the filtering

**Comment by chrismatix** [comment]
@AitorAlgorta that's a good point. Which one would you prefer? `display_name` or the split version

**Comment by AitorAlgorta** [comment]
for the current context, `display_name` is good enough
