### ISSUE TITLE
Transparent send message API implications

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#723]
**Current state**
We decided to implement a send message API that enforces a certain level of control over the outbound content by setting a `type` that resolves to `text|audio|video|image|file` and `source.template`

**Product input**
To make the integration of the Airy Core Platform with existing message workflows as easy as possible `/messages.send` should work with whatever source-specific message payload you send to it.

I.e. to send a Google message that is structured [like so](https://developers.google.com/business-communications/business-messages/guides/build/send), you would call `/messages.send` like so:

```
{
   "conversation_id": "UUID",
   "message": {
      "text": "some string with **markdown**",
      "fallback": "some string without markdown",
      "containsRichText": "true"
   }
}
```

This means that everything on the `message` field gets forwarded to the source as-is, which means that **clients are responsible for building the correct source message payload**

**Backend implications**

This means that the backend should not parse source data to any schema whatsoever. The advantage of this is, that the messaging system becomes just a pipe. This is a trade-off as it makes Airy more transparent at the cost of making features depending on message content harder to build.

- [x] API: Replace all typed `Content` message content with a simple `String` so that clients also get the message content as-is
- [x] Media resolving: Don't replace URLs on the fly; instead, write resolved URLs to the message headers and return them in the API
→ This means that the media resolver will be the only place where the `mapping` library is currently needed.
- [x] Prepare a sample ~folder~ gist with request and response payloads for the frontend team

**UI implications**

For now, the message rendering library and the send message code will have to become a lot smarter until we figure out a way to dynamically load the right information necessary to construct and render payloads. Details TBD

**Comment by AitorAlgorta** [comment]
Actually I have a question: This means that a text message from Google, a text message from Twilio and a text message from Facebook will have different payloads right?

**Comment by lucapette** [comment]
@AitorAlgorta yes that's correct and it's the "trade-off" of this design. While we make the api more transparent for a client dealing with a single source, our own UI will have to take over the construction of those payload (at least short term). There are ideas on the table to improve this as well (like loading bundles by source via `/client.config`) but it's probably better to wait a little and see how this develops
