### ISSUE TITLE
RFC650 Compliance of API Bearer JWT Authentication

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#729]
Authentication for the HTTP API currently works as follows, but is undocumented (https://docs.airy.co/api/http#authentication):

```
     POST /resource HTTP/1.1
     Host: server.example.com
     Authorization: SOME_VALID_JWT
```

According to the RFC6750 standard (https://tools.ietf.org/html/rfc6750#section-2.1) the client should us the "Bearer" authentication scheme to transmit the access token as follows:

```
     POST /resource HTTP/1.1
     Host: server.example.com
     Authorization: Bearer SOME_VALID_JWT
```

The documentation should also be amended accordingly to tell users how to authenticate.

**Comment by lucapette** [comment]
I don't know how I missed this was part of the standard. We'll adhere to it

**Comment by lucapette** [comment]
We should also provide an example in authorization.md
