### ISSUE TITLE
URL Change: docs.airy.co -> airy.co/docs

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#733]
Let's switch to the industry standard for easier tracking & extensibility. 
Should later be extended in an easy fashion to airy.co/docs/enterprise etc

**Comment by sgarroum** [comment]
For the menu to work properly we should have the structure
airy.co/docs/airycore
airy.co/docs/airyenterprise

Could also be done easily with url fwds, as long both of them have a base url (so airy.co/docs for the core one, airy.co/docs/airyenterprise for the enterprise one)

**Comment by ljupcovangelski** [comment]
Issue resolved, the following URLs are active now:
- https://airy.co/docs
- https://airy.co/docs/core
- https://airy.co/docs/enterprise
- https://docs.airy.co (with redirect to https://airy.co/docs/core/)
- https://enterprise.airy.co (with redirect to https://airy.co/docs/enterprise/)
