### ISSUE TITLE
Navbar 2.0: Links to Airy Core, Airy Enterprise, Github, Need Help?, Darkmode

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#772]
Navbar should have:

Left aligned:
Links as simple text to:
- Airy Core: https://airy.co/docs/airycore
- Airy Enterprise: https://airy.co/docs/airyenterprise

Right aligned:
- Github: Github Logo linking to https://github.com/airyhq/airy
[GitHub-Mark.zip](https://github.com/airyhq/airy/files/5892819/GitHub-Mark.zip)
- Need Help? https://airy.co/docs/getting-started/troubleshooting
- Darkmode Toggle

**Comment by sgarroum** [comment]
Please keep the Search in the same location (most right item) - as it can't be moved to the sidebar https://github.com/airyhq/airy/issues/773

**Comment by lucapette** [comment]
done in #838
