### ISSUE TITLE
Search: Move from Navbar to top of Left Sidebar

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#773]
Search currently gets lost a bit in the Navbar, and with Navbar 2.0 it will get quite busy, so we should move it above the left Sidebar, similar to how Rasa does it https://rasa.com/docs/rasa/installation/

**Comment by AudreyKj** [comment]
moving the searchbar placement is not currently supported by docusaurus v2

cc: https://github.com/facebook/docusaurus/issues/4157
(so the only option would be to swizzle the navbar component but this is not recommended by docusaurus since it can make breaking changes)

**Comment by lucapette** [comment]
added the waiting label as we're waiting for docusaurus to ship a new release (they did implement the missing feature 🎉)

**Comment by lucapette** [comment]
so the primary reason for #1302 is this issue. As we can't do this one without owning the theme, I will close this one and update the description of #1302
