### ISSUE TITLE
Changelog: add a Changelog page & copy paste or automate from Github Changelog

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#783]
Changelog should be the reposted version of https://github.com/airyhq/airy/releases/tag/0.6.0

**Comment by chrismatix** [comment]
@sgarroum How do you imagine this to look? One large page that includes all releases like [Rasa does it](https://rasa.com/docs/rasa/changelog/)?

**Comment by sgarroum** [comment]
@chrismatix yes that would be the best way, long list of all releases and changes with each release
