### ISSUE TITLE
CLI: GIF 

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#784]
For the CLI Doc Intro the best thing is a small very nice GIF. 
Preferably an Airy Version of this:
![stripe_cli_demo](https://user-images.githubusercontent.com/12533283/106285046-47fd1a80-6244-11eb-89de-9867131b881b.gif)

**Comment by lucapette** [comment]
Labeled as waiting as I think it makes sense we wait for https://github.com/airyhq/airy/milestone/22 to be done

**Comment by chrismatix** [comment]
Useful resource: https://github.com/asciinema/asciicast2gif

**Comment by chrismatix** [comment]
@sgarroum Just to be clear. By CLI Doc intro do you mean https://airy.co/docs/core/cli/installation or https://airy.co/docs/core/getting-started/installation/minikube? The former currently doesn't use a command that we could illustrate with a gif so perhaps you mean a different page altogether.

**Comment by bitboxer** [comment]
I would vote for using asciinemas player. I cannot stop GIFs or go back to a specific point. I have to rewatch the complete GIF...which I hate because it wastes my time.

**Comment by sgarroum** [comment]
@chrismatix this ticket was created before  https://airy.co/docs/core/getting-started/installation/minikube existed, so I meant https://airy.co/docs/core/cli/installation, I think the one for Minikube is great.

**Comment by chrismatix** [comment]
Ok so given @bitboxer comment - which we seem to agree on - this issue is done. If you agree @sgarroum I will close it.
