### ISSUE TITLE
Facebook System User Token as system variable

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#790]
### Summary
As an alternative to a user filling out [this form](https://user-images.githubusercontent.com/74183162/106301005-73d5cb80-6257-11eb-8e8d-175d695dc637.png), I as a user want to use a system user token so that I can establish a stable connection between Airy and my Facebook page since that token is not subject to expire.

We should ask for the system user token and then use that to `channels.facebook.explore` pages. With this, we can add the pages that we get from there. Using this method, the form from the following image could already be pre-filled with the information provided.
![106301005-73d5cb80-6257-11eb-8e8d-175d695dc637](https://user-images.githubusercontent.com/74183162/106315203-354a0c00-626b-11eb-9aa2-843a27211576.png)

### Product Requirements

- Add a configuration variable for the system user token in `airy.yaml`. We could then show a list of pages for such system user token -- the user just needs to select the page in a new view and the connection would be stable.
- When the system user token is stored in `airy.yaml`, the end user experience could look similar to the one in seen in the image below.
<img width="1231" alt="Screenshot 2021-01-29 at 18 50 37" src="https://user-images.githubusercontent.com/74183162/106309888-0891f680-6263-11eb-8310-98917af260a8.png">

This means that when a user clicks on "create", the user gets a list of all pages the system user has access to (no further data entry would be necessary and we can skip the requirement of filling the form).

This experience is generated by querying `channels.facebook.explore` to get the list of all pages, then `channels.facebook.connectto` to connect the page the system user selected.

### Note
These images are only for illustrative purposes - this feature does not need to be built to look identical to this.

**Comment by lizhutter** [comment]
#659

**Comment by lucapette** [comment]
by the time we get to this, the endpoint should be called `channels.facebook.explore` (because of #794)

**Comment by AitorAlgorta** [comment]
we have this https://github.com/airyhq/airy/pull/2617

we either closed the issue and forget about it or we find a solution that works for core and cloud. But we cannot leave this hanging here. @steffh @lizhutter @M-Shorouk
