### ISSUE TITLE
Demo app infinite crash on redux update

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#812]
**Description**
When you open the demo app right now (http://demo.pascal.cloud.airy.co/), there is an infinite crash loop with the error seen in the screenshot.

![image](https://user-images.githubusercontent.com/4403838/106473687-5ba6bc00-64a4-11eb-956e-6a584f18e3be.png)

![image](https://user-images.githubusercontent.com/4403838/106473524-28fcc380-64a4-11eb-9057-90b79ba933b3.png)

**Comment by lucapette** [comment]
fixed in #821
