### ISSUE TITLE
Chatplugin uses its own payload

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#827]
Currently the `chat plugin` has it's own response mapper, causing the response of `/chatplugin.send` to be different from the other sources.

Should `/source.send` endpoints have different response payloads?

**Comment by lucapette** [comment]
In general, I'm not so sure about it. But for the message payload, I think we're kind of forced into sharing the same payload by the decisions we took (and I think make sense) about the way we render content on the frontend

**Comment by chrismatix** [comment]
Agree with what Luca said. For messagse the chat plugin client will have to use the message rendering library (otherwise the source template tickets don't make a lot of sense) so conceptually the chat plugin message has to be the same as the core message.

**Comment by lucapette** [comment]
We can/should use the message repository for this then
