### ISSUE TITLE
Introduce dynamic page titles

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#849]
We want to have dynamic page titles depending on the section we are in (Inbox, Channels, Tags, etc)

**Comment by lucapette** [comment]
Short term, i think it would be enough to do:

- title reflects current page 
- presents somehow (that's something we should discuss I think) the number of unread messages if any. Something like `Inbox (42)` would be already very functional

**Comment by bitboxer** [comment]
Extracted the total count to [another ticket](https://github.com/airyhq/airy/issues/989)
