### ISSUE TITLE
Introduce end to end testing

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#866]
The smoke test script was a good first step to test the API while we were developing it but we want to introduce a much more complete testing framework in the future

I played around with [Cypress](https://www.cypress.io/) a bit today and I liked it a lot. I could do a full test of the Login with a couple of lines of code and Cypress integrates well with CI.

We should also be able to generate gifs in the tests and use them in the docs. For what we could use [cypress](https://github.com/bahmutov/cypress-movie)

**Comment by lucapette** [comment]
so I agree with @pascal-airy that we can use cypress for the "actual testing". What I mean is that there's more to it in the long run. Let me recap all we want to do:

- test "everything":
  - the UI flows
  - the chat plugin integration
  - the webhook integration
- Generate gifs automatically for the flows (so we can reuse in the docs)
- At some point in the future, run the whole integration suite on CI (maybe not on push. Say once per day). Of course that assumes we can spin the whole airy core "somewhere". I don't consider this a requirement for a first working version of the end to end testing (being able to programmatically end to end test things already provides a lot of benefits)

The last point, as I see it, heavily depends on https://github.com/airyhq/airy/milestone/22 so there's that as well.

The whole end to end testing topic has a further dimension that complicates matters: sources. As we own the chat plugin (and soon enough a "custom source"), I propose we start the milestone with the happy paths of the chat plugin integration and add to the milestone we create a "testing sources" issue and discuss there how we can approach it (before even splitting it further).

As for the tech we want to use, I think it's ok to start with cypress but want to underline a few things:

- not all the code we have to write is cypress "friendly". For example, how would we test the webhook integration?
- While I love TypeScript, not a big fan of nodejs for the code that orchestrate things. Like creating airy core, waiting for things. 

So I can imagine we would do something like:

- introduce a top level dir called `integration` that has a dir per component we want to test (that's a proposal, not a requirement so happy to hear opinions about this)
- We glue the code together when we need to with some `integration/scripts/test_all_the_things.sh` which brings together the nodejs part, our own cli (which I assume it will simplify creating/configuring the test instance), and "some other tests" which we may/may not write with Typescript.

I think I'm good with this plan for now but felt compelled to make it explicit. If we agree on this sketch, @pascal-airy and I will transform this issue into a milestone and organise the work for the coming weeks

**Comment by pascal-airy** [comment]
As said this will be addressed in #1050
