### ISSUE TITLE
httpclient methods need return value

### ISSUE THREAD

**Issue by bitboxer** [airyhq/airy#871]
also maybe we can configure typescript that it yells when the return value is not defined?

**Comment by chrismatix** [comment]
@bitboxer I think this issue could be a bit more descriptive, but I get what you want. So there is one thing I can imagine this working: We define a [functional interface](https://www.typescriptlang.org/docs/handbook/interfaces.html#function-types) like so:
```
interface ApiRequest<T,K> {
   (requestPaylod: T) => Promise<K>
}

const myRequest: ApiRequest<IRequestPayload, IResponsePayload> = ...
```

Now we could say by convention that all methods need to implement this interface. If you want a programmatic way to enforce this you could put them all into a dictionary and enforce the interface as the value type.
