### ISSUE TITLE
Blockquote/Highlight: Add Color to it and Highlight Intro Sentence in every doc

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#874]
Blockquote background color should be #F1FAFF, Left side bar should be #4BB3FD

Please make so that each Page now has a highlighted Blockquote under the Headline:

Introduction:
- [x] Airy Core is an **open source, fully-featured, production-ready messaging platform**.

Installation:
- [x] You can install Airy from **many possible installation options**, locally or in the cloud.

Deployment:
- [x] You can deploy Airy Core in many different ways: **locally or production-ready in your cloud**.

Quickstart:
 - [x] In this Quickstart we are **setting up our first source, listen to conversations & consume directly from Kafka**.

CLI:
- [x] The Airy CLI is a developer tool to help you **build, test, and manage Airy directly from your terminal**.

Troubleshooting: 
- [x] There are 2 ways to get help quickly: **Community Support & Enterprise Support** by the founding engineers.

Glossary: 
- [x] Airy Core allows its **users** to process messaging data from a variety of **sources**, which are integrated via **source providers**. Users connect sources via **channels**. Once the channel is connected, Airy Core ingests source data and transforms them into **conversations**, **contacts**, and **messages**.
Here keep the links included please.

Sources Intro:
-[ ] Airy Core allows you to connect **many different sources**, from our Live Chat Plugin to Messaging Sources like Facebook Messenger & Whatsapp to your own custom sources.

Airy Live Chat Plugin:
- [x] Airy’s Live Chat Plugin is an **open-source chat widget** that you can put on your website to chat with your visitors.

Facebook Messenger:
- [x] **Connect your Facebook Pages** and send and receive messages from Facebook’s 1,3 Billion users.

Google’s Business Messages:
- [x] Start receiving and sending messages from **Google Maps & Google Search**.

SMS:
- [x] **Sending and receiving SMS** with every phone on the planet. 

WhatsApp:
- [x] Connect with **2 Billion WhatsApp users** via messages and templates.

API:
- [x] Interact with your Airy Core via **HTTP Endpoints, WebSockets or Webhooks**.

Authentication:
- [x] To start using the API you need to **authenticate first**.

WebSocket:
- [x] Airy Core offers a WebSocket server that allows clients to **connect and receive near real-time updates**.

Webhook:
- [x] Use Webhooks to receive events to notify you when a variety of interactions or events happen.

Rasa:
- [x] Update already grey blockquote

**Comment by lucapette** [comment]
this was done in #887
