### ISSUE TITLE
Installation: Add Revamped Installation Intro & UI Link Section

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#875]
- [ ] Add Installation Intro from here: https://docs.google.com/document/d/1Zt5rpGCT5aKG-IpRJwcx81LYPe1uPcikr_5NhtWy_os/edit

- [ ] Build UI Link Section as mocked here:
![image](https://user-images.githubusercontent.com/12533283/106883760-b62c5c00-66e0-11eb-9f21-b5933a172187.png)
Good implementation on docusaurus of this can be found here: https://vector.dev/docs/setup/installation/package-managers/

**Comment by pascal-airy** [comment]
@lucapette and I introduced a Box component [here](https://github.com/airyhq/airy/pull/896/commits/bb8f1e6035779c965a7a25d14227883e0e8419ff#diff-06a123fd378ecc9bfd2e7795c15568741e2c8ac824f30633380d3d5d70a2d6c3) 
which could be used for this ticket in a way of a BoxList component that you pass a list of Boxes but we need some help. So reach out when you are starting with this ticket, please
