### ISSUE TITLE
Feature Proposal: Custom Sources 

### ISSUE THREAD

**Issue by steffh** [airyhq/airy#877]
As an Airy developer trying to connect source types that are not yet supported by Airy Core,
I want to be able to create custom sources (and effectively channels of the relevant custom source type),
so that I can ingest conversational data in my Airy cluster
via a webhook from a third party system that produces conversational data

## Requirements

- there needs to be a way to create, update and delete/deactivate the custom source
- the custom source should have a distinguishable name, so that we can create multiple custom sources and differentiate between them
- there needs to be a way to define the data model for events to be received from such custom source (e.g. message payloads) and a map so we can extract metadata from it
- there needs to be a way to define how to send requests back to the custom source, e.g. how to send messages and authorize the relevant API requests (unless the integration was read only for such relevant custom source e.g. to extract conversational analytics, but no responses were required from Airy)
- there needs to be a way to connect a channel to an Airy cluster of the source type of the relevant custom source including defining a unique identifier in order to map incoming events accordingly, e.g. `channel_id`, `members.user_id`, `team_id`, `app_id`, `ALL_MESSAGES_FOR_SOURCE`

**Comment by steffh** [comment]
splitting this ticket in a general request / feature proposal for how to do sources and the suggested getstream.io source

**Comment by chrismatix** [comment]
This is covered by [this milestone](https://github.com/airyhq/airy/milestone/33) and already possible using the [Source API](https://airy.co/docs/core/api/source). Therefore I am closing this ticket.
