### ISSUE TITLE
Deployment: Introduction: Add Box Button section

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#878]
As Mocked here & Copy already written
https://docs.google.com/document/d/1Zt5rpGCT5aKG-IpRJwcx81LYPe1uPcikr_5NhtWy_os/edit#bookmark=id.n7gdz2jfpzvc

also UI Link section should reuse: https://github.com/airyhq/airy/issues/875

**Comment by sgarroum** [comment]
Intro section should be:
You can choose to deploy Airy in many different ways: locally with Vagrant or production ready in your cloud or in AWS, Google, Azure or Digital Ocean.

The following documentation covers how to develop locally with Airy or deploy Airy with various hosting options.



The text of the Box Button Section should be:

Deployment Guides

Step by step guides for deployment on various platforms, for installation please see our installation guides. 

https://www.vectorlogo.zone/logos/vagrantup/vagrantup-icon.svg 
Local test environment with Vagrant
Step by step guide to run Airy Core on your local machine

https://www.vectorlogo.zone/logos/apache_kafka/apache_kafka-vertical.svg 
Production ready environment with Kafka
Manual step by step guide for running Airy in production

**Comment by lucapette** [comment]
done in #924
