### ISSUE TITLE
Suggested Replies Endpoint

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#880]
In order for this feature to work properly, we need to be able to suggest replies and return them in the `messages.list` endpoint.

**Comment by lucapette** [comment]
Based on how the feature is supposed to work, I think we want:

- `/messages.suggest` (or something along the lines of that) which requires a content payload and a message id
- add these payloads to the message metadata (so that they show up in the json response of the `/messages.list` endpoint)
