### ISSUE TITLE
Metadata object mapper

### ISSUE THREAD

**Issue by chrismatix** [airyhq/airy#881]
The metadata model library `backend/model/metadata` needs these two functionalities
- We want to serialize metadata records (= list of dotted k v updates) to a `JSON` object for all subjects
- We want to turn a `JSON` payload into a series of metadata records that reflect an upsert merge on the metadata object

The API could looks something like this:
```java
class MetadataObjectMapper {
    public JsonNode getMetadataPayload(Iterable<Metadata> metadata); // construct JSON from metadata 
    public Stream<Metadata> getMetadataRecords(Subject subject, JsonNode updatePayload); // construct update metadata from update json paylod
}
```

**Comment by lucapette** [comment]
@chrismatix (honest question) why Stream? I like the idea  lot though. I wonder if we "solve" the writing side of the endpoint in the library (it could be in the controller though because maybe it's not so "metadata specific")

**Comment by chrismatix** [comment]
@lucapette because library consumers may want to update the stream of metadata records, i.e. to add the public prefix to every metadata key. On the controller the code would be used like so:
```java
getMetadataRecords(subject, updatePayload).map((metadata) → {
  metadata.setKey(publicNamespace + metadata.getKey());
  return metadata;
})
```
Adding the namespace is specific to the `/metadata.upsert` route so I would separate the concerns :)

**Comment by lucapette** [comment]
ok I think I get it now 👍
