### ISSUE TITLE
New /metadata.upsert API endpoint

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#882]
We need a new endpoint `/metadata.upsert` that takes a `subject` (conversation | message | channel) and a `data` object.

`POST /metadata.upsert`

```json5
{
  "subject": "conversation|message|channel",
  "data": {
    "contact": {
      "displayName": "Roy McBride"
     },
    "isUserTyping": false
  }
}
```

We also need to remove the following endpoints

- [ ] `/metadata.set`
- [ ] `/metadata.remove`

**Comment by lucapette** [comment]
I'd prefer the more generic `update` (I get why `upsert` though... it feels a little overloaded for an api endpoint name)

**Comment by paulodiniz** [comment]
How about `/metadata.set` then? Because we're always passing the object right?

**Comment by lucapette** [comment]
it works for me!

**Comment by paulodiniz** [comment]
So I gave some thought, and I have one question about  `metadata.update`: An `update` action implies that the "entity" is already there.

Is this the case with our metadata?

**Comment by lucapette** [comment]
that's a valid argument to go for `upsert` actually :) so I would say we go for that and see how it resonates with other people <3

**Comment by steffh** [comment]
just a little question about `/metadata.remove` being removed. how would an airy api user remove a metadata field then that is no longer needed?

would something like POST `/metadata.upsert` with body `{"subject": "ID", "data": { "key", {}}` work?

**Comment by chrismatix** [comment]
@steffh we could not come up with a use case where a user would like to remove metadata rather than overwrite it. If you can come up with one, we would probably add a route that is a bit more granular. 

I.e. they would have to give us the path to the key to remove. Like POST `/metadata.remove` with body `{"subject": "ID", "key": "contact.display_name"}`
