### ISSUE TITLE
Add metadata field to channels API 

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#883]
Add `metadata` to the channels API.

We can use this library to output the JSON https://github.com/airyhq/airy/pull/891

**Comment by lucapette** [comment]
the thing with the naming here is that the endpoints should be called `userdata.upsert` (which is 100% horrible :D). So I can't really propose anything better than:

- `/metadata.upsert` 
- `{metadata: {contact, tags..., custom: {}}`

I don't love it... but less confusing than what we have already. My fav solution would be:

`{name_i_dont_have_yet: {contact, tags, ..., metadata: {}}}` (but maybe there's really not a good name for this

**Comment by chrismatix** [comment]
`userMetadata` is overly descriptive. Perhaps that works?

**Comment by lucapette** [comment]
@chrismatix it does... but my point is also that it should stay in sync with the endpoint. So I'm not sure you're suggesting `/usermetadata.update` (or maybe this is a non-requirement? That's also a valid answer I think)

**Comment by chrismatix** [comment]
It seems intuitive, but if the request payload already contains `userMetadata`, I think we can keep the endpoint's name `/metadata.upsert` and it still makes sense.

**Comment by lucapette** [comment]
yeah I think it's reasonable!
