### ISSUE TITLE
New Airy Event for Webhook

### ISSUE THREAD

**Issue by paulodiniz** [airyhq/airy#885]
We need to introduce an AiryEvent to the webhook payload that contains the following information

    event_type: conversation| message| channel
    data: event payload

**Comment by lucapette** [comment]
this also needs a metadata one. I'm not sure about `conversation`. As I understand it now, that doesn't really exist yet. 

going down that route then we'd have a `AiryMetadataPayload`? (to represent id plus actual metadata...)
