### ISSUE TITLE
airy.yaml restructuring 

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#892]
- [x] `jwtSecret` should be in `components.api.http.jwtSigningKey` to make it clearer what it is for
- [x] `apps` should be `components` to be aligned with our naming convention
- [x] `global` should be `kubernetes`

**Comment by ljupcovangelski** [comment]
We had a discussion about the structure of the `airy.yaml` file, related to the refactoring of the `airy config apply` command.

The file should be treated by the `airy config apply` command to apply the configuration for all the mandatory and optional components. In that sense, the `tools` perhaps should be treated like optional components and we can have them under

```
components:
  tools:
    akhq:
      ...
    prometheus:
      ...
```

For the `global` section, those items are now part of the `~/.airy/cli.yaml` file, so they can be removed from the `airy.yaml` file I guess. Also the "global" kubernetes options, such as the ingress url are injected by the providers at "create time". 

As for the `prerequisites` section, this is mostly used when we install and setup `Airy Core`, so I'm not sure if it is a configuration topic. Perhaps also it makes sense to split this section, into multiple configuration files, in the `~/.airy` directory (ex. kafka.yaml, redis.yaml, postgres.yaml) and keep the `airy.yaml` file only for the actual Airy `components`.

**Comment by ljupcovangelski** [comment]
About the prerequisites, one option would be when we do `airy create` that the command looks for `kafka.yaml`, `postgres.yaml`, ... in the {config-dir} and check whether to create kafka/postgres or use an existing ones.

**Comment by chrismatix** [comment]
@ljupcovangelski since #1544 resolves this issue, should we have these ideas in a follow up ticket?

**Comment by ljupcovangelski** [comment]
> @ljupcovangelski since #1544 resolves this issue, should we have these ideas in a follow up ticket?

Yes, I opened a new issue for the prerequisites. Not sure if there is anything else left
https://github.com/airyhq/airy/issues/1575
