### ISSUE TITLE
Contact avatar doesn't get displayed properly in UI

### ISSUE THREAD

**Issue by thorstenairy** [airyhq/airy#903]

**Comment by thorstenairy** [comment]
As you see in the screenshot, the avatar is missing for the incoming message

![Screenshot 2021-02-08 at 10 00 21](https://user-images.githubusercontent.com/49147864/107198280-34487580-69f5-11eb-8bcd-b48509817ce0.png)

**Comment by lucapette** [comment]
done in #1011
