### ISSUE TITLE
Introduction: Get Started Section on the Introduction Page

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#913]
After the What is Airy Core? Section, and before Airy Core Components, add a section called Get Started with this content

>> Means Clickable Box Component, or whatever this button thing is called

**Get Started**

If you’re interested in trying Airy you need to install it first. 

https://www.zwicon.com/img/icons/svg/development/deploy.svg
>> Start Installation 
Install Airy with our CLI, locally or in the cloud

Once you have Airy installed, follow our Quick Start for guidance.

https://www.zwicon.com/img/icons/svg/finance/diamond.svg
>> To the Quick Start
Learn the Airy Basics with our Quick Start

We'll guide you through the following journey:
- Connect your first Source
- Send Messages
- Use the API to list conversations
- Consume directly from Kafka

**Comment by sgarroum** [comment]
This is the button/ Clickable Box Component I mentioned
https://github.com/airyhq/airy/issues/875

**Comment by lucapette** [comment]
done in #924
