### ISSUE TITLE
stable.txt in S3 should be updated automatically during release

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#926]
https://s3.console.aws.amazon.com/s3/object/airy-core-binaries?region=us-east-1&prefix=stable.txt

this file is used to get the latest release version string

we could also think about using `curl -sL https://api.github.com/repos/airyhq/airy/releases/latest | jq '.tag_name'` instead but it needs jq like this

**Comment by lucapette** [comment]
this was done in #943
