### ISSUE TITLE
Airy Live Chat: End Chat option

### ISSUE THREAD

**Issue by lizhutter** [airyhq/airy#929]
### Summary

To enhance the Airy Live Chat experience, we should offer contacts the option to end the current chat permanently. We could offer this option with an X at the top righthand side of the chat, next to a (-) symbol as a means of minimizing the conversation. If a contact chooses to click this button, the next interaction with this user will create an entirely new conversation.
![wine com end chat](https://user-images.githubusercontent.com/74183162/107388116-c6d03e00-6af5-11eb-8cd5-09ea4d168daf.png)

### Design Notes

These images are only for illustrative purposes - this feature does not need to be built to look identical to this.

**Comment by lucapette** [comment]
What's the exact UI interaction we expect to happen when someone clicks the button?

**Comment by lizhutter** [comment]
When someone clicks the button, we can prompt something like the following image:

<img width="341" alt="Screenshot 2021-02-12 at 15 53 17" src="https://user-images.githubusercontent.com/74183162/107786338-11e48e00-6d4e-11eb-93a3-d6abeae7d759.png">

And if the contact clicks "`End`", we can display a message saying something like "_Your conversation has ended. Thank you for chatting with us today_."

Below this, we can also offer the option to `Start a New Conversation` if the contact would like to.

**Comment by lizhutter** [comment]
To reiterate, the X will prompt the contact to end the chat, and the minus symbol will prompt the contact to minimize the chat. Please use the minus symbol I've attached from [this website](https://www.zwicon.com/cheatsheet.html) for the design.

![Screenshot 2021-03-23 at 18 13 16](https://user-images.githubusercontent.com/74183162/112188656-76272700-8c03-11eb-919b-1e01784f62ec.png)

**Comment by bitboxer** [comment]
Also: what will the agent see in the app? Do we send a special crafted message type saying "conversation ended" / "conversation restarted" ?

**Comment by lizhutter** [comment]
I think that would make the most sense in this situation. This way, the agent is aware of how to approach the conversation from that point forward (whether to treat it as an extension of the current conversation or the beginning of a new conversation).

**Comment by bitboxer** [comment]
As discussed in #1436 we might want to change the "auto open" setting if the chat has ended. So don't open the chat automatically when opening the page and the chat is defined as closed.
