### ISSUE TITLE
Users can't disconnect channels if authorisation token has not been previously saved

### ISSUE THREAD

**Issue by ogbeche77** [airyhq/airy#931]
Say I login, obtain a token and connect a channel. I repeat the process again and connect another channel.
However, In a few hours I choose to disconnect the first channel I had earlier connected, the token available to me is that of the most recent connected channel.
Though another authorisation token can obtained when I login again, but it returns `404 Page not found` when a user attempts to disconnect with this recently token using `http://api.airy/channels.chatplugin.disconnect` endpoint

**Comment by pascal-airy** [comment]
You are never required to save an old token. The new one should also work for disconnecting the new channel. We return a 404 when the channel you are trying to disconnect doesn't exist. Could that be the issue?

If not please provide the curls you used to connect and disconnect the channel including responses.

**Comment by ogbeche77** [comment]
Apparently, the issue had to do with my PC. After restarting my PC and running the bootstrap again today. I could disconnect channels that were previously connected with the token obtained after on Login
