### ISSUE TITLE
Quickstart: Change Info box to Button Box

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#935]
Change 

INFO
To get going with the Quickstart, you must install Airy first. Once you installed Airy and have the CLI up and running you are good to go.

from an info box to one of our new fancy buttons

https://www.zwicon.com/img/icons/svg/development/deploy.svg
Install Airy first
Before you can start with the Quick Start, you must install Airy first. Once Airy is installed you are good to go.

**Comment by lucapette** [comment]
done in #924
