### ISSUE TITLE
Automate Homebrew formula release

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#950]
Since the homebrew formula needs to be in its own [repository](https://github.com/airyhq/homebrew-airy) and the version is hardcoded in there I need to update it somehow during the release process. The best approach would probably be to include this step in the release script but it felt wrong to clone the repo somewhere and then do bash karate.

Maybe someone has a better idea of how to solve that.

**Comment by paulodiniz** [comment]
Personally, I don't think automating this (for now) is the way to go. Our release spans different repositories and it's ok that we have manual processes, specially between different applications.

Currently our release consists of:
- core release (which dictates the VERSION)
- AWS binaries

I propose we add an extra step of updating the version on the brew tap formula, and leave the release script as only part of the first step of the process.

What do you think?

**Comment by lucapette** [comment]
I'm with @paulodiniz on this one. I think the process is very simple and we can rely on doing it manually for a few weeks. I would probably keep the issue open though so we can track how we feel about it
