### ISSUE TITLE
Add ErrorBoundaries for the RenderLibrary

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#957]
We don't want unexpected behaviours in the render library, and if we have, we would like to have a backup plan for this and not crash the page or render something undesirable. So the best approach is using ErrorBoundaries and wrap the component in it, so we are sure that even in case of crash or error, we will display something that is under our control.

**Comment by bitboxer** [comment]
[See here for error boundaries](https://reactjs.org/docs/error-boundaries.html#introducing-error-boundaries)
