### ISSUE TITLE
Fix >> icons that show/hide the sidebar in the docs

### ISSUE THREAD

**Issue by bitboxer** [airyhq/airy#960]
We need to add some spacing to the >> icon that is used to show and hide the sidebar in the docs:

<img width="127" alt="Screen Shot 2021-02-12 at 10 55 49" src="https://user-images.githubusercontent.com/56195/107753920-0dee4700-6d21-11eb-9823-5a1d8afa8ed6.png">

<img width="65" alt="Screen Shot 2021-02-12 at 10 56 03" src="https://user-images.githubusercontent.com/56195/107753930-0fb80a80-6d21-11eb-9800-e0d87c344950.png">

Screenshots taken in latest Firefox

**Comment by lucapette** [comment]
that's probably a docusaurus problem? We don't do this on our own, it's a config docusaurus where we say "make this hideable"
