### ISSUE TITLE
Improve the Quick Start section for UI Docs

### ISSUE THREAD

**Issue by AitorAlgorta** [airyhq/airy#967]
Write the necessary documentation for the Setup section. Adding the screenshoots and GIF that display all the features and functionalities of that part of the UI.

https://docs.google.com/document/d/1hQIZNOwJ_s4ltkvErhVenoRcJYyAJ1Q4VhiHLiLE2jY/edit

**Comment by lucapette** [comment]
There's not really a setup? So I'm not sure what we're supposed to do here

**Comment by AitorAlgorta** [comment]
How to create and account and be able to login inside

**Comment by lucapette** [comment]
yeah that's fair!
