### ISSUE TITLE
Chatplugin messages are super slow

### ISSUE THREAD

**Issue by bitboxer** [airyhq/airy#994]
I am currently having a strange issue with the chat plugin and the ui frontend. I try to send a message using the chat plugin, but sadly the chat plugin does not show the sent message. The UI frontend also does not show the message directly. It takes sometimes up to a couple of minutes for the conversation to appear. Sending a response using the UI does not make it show up in the chatplugin, too.

Sometimes, when I reload the chat plugin example page, the messages appear.

**Comment by AitorAlgorta** [comment]
isn't this machine dependant? I've never experienced something like this

**Comment by bitboxer** [comment]
Okay, cannot reproduce this anymore today...weird. Will close now and reopen if this happens again.
