### ISSUE TITLE
Messages in Inbox for Facebook channel are not in the correct order

### ISSUE THREAD

**Issue by pascal-airy** [airyhq/airy#997]
The "release" message was sent before the "Hello" messages and should therefore be the first message

<img width="2283" alt="Screenshot 2021-02-16 at 15 40 23" src="https://user-images.githubusercontent.com/54705263/108083729-afec9700-7073-11eb-8227-de0193abc6ac.png">

**Comment by bitboxer** [comment]
Cannot reproduce anymore.
