### ISSUE TITLE
Box Button V3: Upgrade

### ISSUE THREAD

**Issue by sgarroum** [airyhq/airy#999]
We will upgrade the button to a seethrough style, now that we have colorful SVGs as Icons

**Normal mode**
Container Light
    background-color: white;
    border: 3px solid #4BB3FD;
    
h4
Color should be black

p
Color should be #303030

highlight
New color #98d3fd

**Dark Mode**
Container Light
    background-color: #20201D;
    border: 3px solid #4BB3FD;
    
h4
Color should be white

p
Color should be white

Highlight: leave as it

**Comment by sgarroum** [comment]
Mock of the end result
<img width="881" alt="Screenshot 2021-02-16 at 16 51 58" src="https://user-images.githubusercontent.com/12533283/108087047-55553a00-7077-11eb-8ab0-315d7622d41d.png">

**Comment by lucapette** [comment]
this was done in #1013
